export type LibraryEntrySeed = {
  id: string;
  slug: string;
  title: string;
  entityType: "crystal" | "herb" | "candle" | "symbol" | "deity" | "stone" | "mineral" | "metal" | "earth" | "water" | "liquid" | "tool" | "charm" | "organic";
  summary: string;
  spiritualProperties: string;
  correspondences: string;
  cleansingMethod: string;
  careNote: string;
  isPremium?: boolean;
};

// ── Herbs (50 from seed_library.json + 4 not covered by JSON) ───────────────

const HERB_SEEDS: LibraryEntrySeed[] = [
  {
    id: "acacia",
    slug: "acacia",
    title: "Acacia",
    entityType: "herb",
    summary: "A protective plant used to ward off evil and stimulate the psychic mind.",
    spiritualProperties: "Protection, Psychic Powers",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Burn the wood with sandalwood as incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "agrimony",
    slug: "agrimony",
    title: "Agrimony",
    entityType: "herb",
    summary: "Protects against goblins and evil, and is used to reverse hexes and send them back to the caster.",
    spiritualProperties: "Protection, Sleep",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "Sprinkle around the area to banish negative energies.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "alfalfa",
    slug: "alfalfa",
    title: "Alfalfa",
    entityType: "herb",
    summary: "Kept in the home to protect against poverty and hunger, and used in money spells.",
    spiritualProperties: "Prosperity, Anti-Hunger, Money",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "Burn and scatter the ashes around the property.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "allspice",
    slug: "allspice",
    title: "Allspice",
    entityType: "herb",
    summary: "Used to attract money and luck, as well as to promote healing.",
    spiritualProperties: "Money, Luck, Healing",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burn as an incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "almond",
    slug: "almond",
    title: "Almond",
    entityType: "herb",
    summary: "Brings success in business ventures, money, and grants the partaker wisdom.",
    spiritualProperties: "Money, Prosperity, Wisdom",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "Bitter almond is not for internal use due to cyanogenic glycosides.",
    isPremium: false,
  },
  {
    id: "aloe",
    slug: "aloe",
    title: "Aloe",
    entityType: "herb",
    summary: "Guards against evil influences and prevents household accidents when grown in the home.",
    spiritualProperties: "Protection, Luck",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "althea",
    slug: "althea",
    title: "Althea",
    entityType: "herb",
    summary: "A good 'spirit-puller' that brings good spirits in during rituals when placed on the altar.",
    spiritualProperties: "Protection, Psychic Powers",
    correspondences: "Element: Water",
    cleansingMethod: "Burn as incense or carry in a sachet.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "amaranth",
    slug: "amaranth",
    title: "Amaranth",
    entityType: "herb",
    summary: "A crown of amaranth flowers worn on the head speeds healing and protects.",
    spiritualProperties: "Healing, Protection, Invisibility",
    correspondences: "Planet: Saturn, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "angelica",
    slug: "angelica",
    title: "Angelica",
    entityType: "herb",
    summary: "Used to remove curses, hexes, and spells that have been cast against you.",
    spiritualProperties: "Exorcism, Protection, Healing, Visions",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Add to bath water or sprinkle around the perimeter of the house.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "anise",
    slug: "anise",
    title: "Anise",
    entityType: "herb",
    summary: "Placed in a pillowcase to prevent nightmares and placed around the magic circle to ward off evil.",
    spiritualProperties: "Protection, Purification, Youth",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "Use in purification baths.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "apple",
    slug: "apple",
    title: "Apple",
    entityType: "herb",
    summary: "A fruit heavily associated with love spells, immortality, and Samhain rituals.",
    spiritualProperties: "Love, Healing, Garden Magic, Immortality",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Seeds are poisonous in large amounts.",
    isPremium: false,
  },
  {
    id: "asafoetida",
    slug: "asafoetida",
    title: "Asafoetida",
    entityType: "herb",
    summary: "Destroys manifestations of spirits if thrown onto a fire or censer during magical rites.",
    spiritualProperties: "Exorcism, Purification, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burn small amounts in exorcism and protection incenses.",
    careNote: "Horrid odor; can cause vomiting.",
    isPremium: false,
  },
  {
    id: "ash",
    slug: "ash",
    title: "Ash",
    entityType: "herb",
    summary: "A staff of ash wards off malign influences, and its leaves induce prophetic dreams.",
    spiritualProperties: "Protection, Prosperity, Sea Rituals, Health",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "basil",
    slug: "basil",
    title: "Basil",
    entityType: "herb",
    summary: "Soothes tempers between lovers and brings wealth to those who carry it.",
    spiritualProperties: "Love, Exorcism, Wealth, Flying, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "Not safe for infants and toddlers in large quantities.",
    isPremium: false,
  },
  {
    id: "bay",
    slug: "bay",
    title: "Bay",
    entityType: "herb",
    summary: "Induces prophetic dreams, offers protection against poltergeists, and grants physical strength.",
    spiritualProperties: "Protection, Psychic Powers, Healing, Purification, Strength",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Burned or scattered during exorcism rituals.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "belladonna",
    slug: "belladonna",
    title: "Belladonna",
    entityType: "herb",
    summary: "Once used to encourage astral projection and produce visions, but generally avoided today.",
    spiritualProperties: "Astral Projection, Visions",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Extremely poisonous; all parts can be fatal.",
    isPremium: false,
  },
  {
    id: "benzoin",
    slug: "benzoin",
    title: "Benzoin",
    entityType: "herb",
    summary: "Used to clear out negative energy and attract prosperity to a business or home.",
    spiritualProperties: "Purification, Prosperity",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Burn as an incense to purify.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "wood-betony",
    slug: "wood-betony",
    title: "Wood Betony",
    entityType: "herb",
    summary: "Protects against nightmares and helps reunite quarreling couples when added to food.",
    spiritualProperties: "Protection, Purification, Love",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Scatter around doors and windows to form a protective wall.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "birch",
    slug: "birch",
    title: "Birch",
    entityType: "herb",
    summary: "A purificatory herb used to exorcise spirits and protect against the evil eye and lightning.",
    spiritualProperties: "Protection, Exorcism, Purification",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Gently strike possessed people or animals with birch twigs.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "blackberry",
    slug: "blackberry",
    title: "Blackberry",
    entityType: "herb",
    summary: "Used for magical healing by crawling through its natural arches, and wards off evil spirits.",
    spiritualProperties: "Healing, Money, Protection",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bloodroot",
    slug: "bloodroot",
    title: "Bloodroot",
    entityType: "herb",
    summary: "Carried or worn to draw love, avert evil spells, and protect the home.",
    spiritualProperties: "Love, Protection, Purification",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Cast a circle of powdered root around the home.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "borage",
    slug: "borage",
    title: "Borage",
    entityType: "herb",
    summary: "Carried to strengthen courage, protect outdoors, and induce psychic powers.",
    spiritualProperties: "Courage, Psychic Powers",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "broom",
    slug: "broom",
    title: "Broom",
    entityType: "herb",
    summary: "Hung in the home to keep evil out and used in spells to raise winds.",
    spiritualProperties: "Purification, Protection, Wind Spells, Divination",
    correspondences: "Planet: Mars, Element: Air",
    cleansingMethod: "Sprinkle the infusion through the house to exorcise poltergeists.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "burdock",
    slug: "burdock",
    title: "Burdock",
    entityType: "herb",
    summary: "Used to ward off negativity and to heal conditions like gout.",
    spiritualProperties: "Protection, Healing",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Cast around the home to ward off negativity.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "caraway",
    slug: "caraway",
    title: "Caraway",
    entityType: "herb",
    summary: "Prevents theft, protects children from illness, and incites lust.",
    spiritualProperties: "Protection, Lust, Health, Anti-theft, Mental Powers",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "carnation",
    slug: "carnation",
    title: "Carnation",
    entityType: "herb",
    summary: "Gives strength and energy to a healing patient and offers protection.",
    spiritualProperties: "Protection, Strength, Healing",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Use dried blossoms in incenses.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "catnip",
    slug: "catnip",
    title: "Catnip",
    entityType: "herb",
    summary: "Creates a psychic bond with cats, attracts good spirits, and forms lasting friendships.",
    spiritualProperties: "Cat Magic, Love, Beauty, Happiness",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cedar",
    slug: "cedar",
    title: "Cedar",
    entityType: "herb",
    summary: "Protects against lightning, draws money, and heals head colds through purification.",
    spiritualProperties: "Healing, Purification, Money, Protection",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Smoulder twigs or burn as incense to purify.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "roman-chamomile",
    slug: "roman-chamomile",
    title: "Roman Chamomile",
    entityType: "herb",
    summary: "Used to attract money, induce sleep, and remove curses cast against you.",
    spiritualProperties: "Money, Sleep, Love, Purification",
    correspondences: "Planet: Sun, Element: Water",
    cleansingMethod: "Sprinkle around property to remove curses.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cherry",
    slug: "cherry",
    title: "Cherry",
    entityType: "herb",
    summary: "Used to attract or stimulate love and to divine the number of years left in one's life.",
    spiritualProperties: "Love, Divination",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Seed and wilted leaf are poisonous.",
    isPremium: false,
  },
  {
    id: "cinnamon",
    slug: "cinnamon",
    title: "Cinnamon",
    entityType: "herb",
    summary: "Raises high spiritual vibrations, draws money, stimulates psychic powers, and offers protection.",
    spiritualProperties: "Spirituality, Success, Healing, Power, Psychic Powers, Lust, Protection, Love",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Burn as an incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cinquefoil",
    slug: "cinquefoil",
    title: "Cinquefoil",
    entityType: "herb",
    summary: "Grants eloquence when asking for favors and ensures restful sleep when placed under the bed.",
    spiritualProperties: "Money, Protection, Prophetic Dreams, Sleep",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Add to purificatory bath sachets.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "clove",
    slug: "clove",
    title: "Clove",
    entityType: "herb",
    summary: "Attracts riches, stops gossip, and drives away hostile or negative forces.",
    spiritualProperties: "Protection, Exorcism, Love, Money",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Burn as an incense to purify an area.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "clover",
    slug: "clover",
    title: "Clover",
    entityType: "herb",
    summary: "Different leaves bring different powers: two for love, three for protection, four for magic, five for money.",
    spiritualProperties: "Protection, Money, Love, Fidelity, Exorcism, Success",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Sprinkle red clover infusion to remove negative spirits.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "comfrey",
    slug: "comfrey",
    title: "Comfrey",
    entityType: "herb",
    summary: "Protects travelers and safeguards luggage from being lost or stolen.",
    spiritualProperties: "Safety during Travel, Money",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "coriander",
    slug: "coriander",
    title: "Coriander",
    entityType: "herb",
    summary: "Added to love sachets and warm wine for lust, and worn to ease headaches.",
    spiritualProperties: "Love, Health, Healing",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "corn",
    slug: "corn",
    title: "Corn",
    entityType: "herb",
    summary: "A symbol of plenty and fertility, used to bless areas and used in divination.",
    spiritualProperties: "Protection, Luck, Divination",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cypress",
    slug: "cypress",
    title: "Cypress",
    entityType: "herb",
    summary: "Eases the mind and allays grief during times of crisis and death.",
    spiritualProperties: "Longevity, Healing, Comfort, Protection",
    correspondences: "Planet: Saturn, Element: Earth",
    cleansingMethod: "Burn dried greenery as incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "daffodil",
    slug: "daffodil",
    title: "Daffodil",
    entityType: "herb",
    summary: "Attracts love and good luck, and increases fertility when placed in the bedroom.",
    spiritualProperties: "Love, Fertility, Luck",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "daisy",
    slug: "daisy",
    title: "Daisy",
    entityType: "herb",
    summary: "A flower of coquetry that brings love and can return an absent lover if slept upon.",
    spiritualProperties: "Lust, Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "dandelion",
    slug: "dandelion",
    title: "Dandelion",
    entityType: "herb",
    summary: "Divines lifespan and is used to send messages of love upon the wind.",
    spiritualProperties: "Divination, Wishes, Calling Spirits",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "dill",
    slug: "dill",
    title: "Dill",
    entityType: "herb",
    summary: "Protects homes from envious individuals, draws money, and stimulates lust.",
    spiritualProperties: "Protection, Money, Lust, Love",
    correspondences: "Planet: Mercury, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "dragons-blood",
    slug: "dragons-blood",
    title: "Dragon's Blood",
    entityType: "herb",
    summary: "A potent resin burned to entice errant lovers to return and to cure impotency.",
    spiritualProperties: "Love, Protection, Exorcism, Potency",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burned to clear spaces and protect.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "elder",
    slug: "elder",
    title: "Elder",
    entityType: "herb",
    summary: "Wards off attackers and evil magic, and forces witches to release enchantments.",
    spiritualProperties: "Exorcism, Protection, Healing, Prosperity, Sleep",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Scatter leaves and berries to bless a person, place, or thing.",
    careNote: "All parts except the ripe fruit are poisonous.",
    isPremium: false,
  },
  {
    id: "eucalyptus",
    slug: "eucalyptus",
    title: "Eucalyptus",
    entityType: "herb",
    summary: "Stuffs healing poppets and maintains good health when worn or placed beneath the bed.",
    spiritualProperties: "Healing, Protection",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Do not use on the faces of small children.",
    isPremium: false,
  },
  {
    id: "eyebright",
    slug: "eyebright",
    title: "Eyebright",
    entityType: "herb",
    summary: "Clears the mind, aids memory, and induces magical clairvoyance.",
    spiritualProperties: "Mental Powers, Psychic Powers",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "fennel",
    slug: "fennel",
    title: "Fennel",
    entityType: "herb",
    summary: "Guards against evil spirits, prevents tick bites, and is used in purificatory sachets.",
    spiritualProperties: "Protection, Healing, Purification",
    correspondences: "Planet: Mercury, Element: Fire",
    cleansingMethod: "Use in purification sachets.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "lavender",
    slug: "lavender",
    title: "Lavender",
    entityType: "herb",
    summary: "Attracts men, induces peaceful sleep, and guards against cruelty and depression.",
    spiritualProperties: "Love, Protection, Sleep, Chastity, Longevity, Purification, Happiness, Peace",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Burn to purify or add to purification baths.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "rosemary",
    slug: "rosemary",
    title: "Rosemary",
    entityType: "herb",
    summary: "Ensures good sleep, prevents nightmares, preserves youthfulness, and aids memory.",
    spiritualProperties: "Protection, Love, Lust, Mental Powers, Exorcism, Purification, Healing, Sleep, Youth",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Smoulder to rid a place of negativity, especially prior to performing magic.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "sage",
    slug: "sage",
    title: "Sage",
    entityType: "herb",
    summary: "Ensures a long life, promotes wisdom, and is heavily utilized in healing spells.",
    spiritualProperties: "Immortality, Longevity, Wisdom, Protection, Wishes",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "adders-tongue",
    slug: "adders-tongue",
    title: "Adder's Tongue",
    entityType: "herb",
    summary: "Used primarily in healing magic to cure wounds or bruises by applying it soaked in cold water.",
    spiritualProperties: "Healing",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "Wrap in cloth, apply to wound until warm, then bury in a muddy place.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "african-violet",
    slug: "african-violet",
    title: "African Violet",
    entityType: "herb",
    summary: "Grown in the home to promote spirituality and provide a slightly protective energy.",
    spiritualProperties: "Spirituality, Protection",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "agaric",
    slug: "agaric",
    title: "Agaric",
    entityType: "herb",
    summary: "Used to encourage fertility by being placed on the altar or in the bedroom.",
    spiritualProperties: "Fertility",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "Poisonous (Death Angel/Death Cap). Do not consume.",
    isPremium: false,
  },
  {
    id: "anemone",
    slug: "anemone",
    title: "Anemone",
    entityType: "herb",
    summary: "Red blossoms are used in healing rituals and carried to prevent disease.",
    spiritualProperties: "Health, Protection, Healing",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Wrap the fresh blossoms in a red cloth and wear or carry.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "apricot",
    slug: "apricot",
    title: "Apricot",
    entityType: "herb",
    summary: "The fruit and leaves are utilized in spells and potions to attract love.",
    spiritualProperties: "Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "arabic-gum",
    slug: "arabic-gum",
    title: "Arabic Gum",
    entityType: "herb",
    summary: "Burned as an incense to purify an area of negativity and evil.",
    spiritualProperties: "Spirituality, Purification",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Smoulder alone on charcoal or add to purification incenses.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "arbutus",
    slug: "arbutus",
    title: "Arbutus",
    entityType: "herb",
    summary: "Protects little children and is used in exorcisms to chase away evil entities.",
    spiritualProperties: "Exorcism, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "aster",
    slug: "aster",
    title: "Aster",
    entityType: "herb",
    summary: "Used in love sachets or grown in the garden with a wish to attract love.",
    spiritualProperties: "Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Carry the bloom to win love.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "avens",
    slug: "avens",
    title: "Avens",
    entityType: "herb",
    summary: "Used in exorcisms, purification rites, and as an amulet against venomous beasts.",
    spiritualProperties: "Exorcism, Purification, Love",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Sprinkle around the area to be exorcised.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "avocado",
    slug: "avocado",
    title: "Avocado",
    entityType: "herb",
    summary: "Carried to promote beauty, while the seed is grown or carried to attract love.",
    spiritualProperties: "Love, Lust, Beauty",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bachelors-buttons",
    slug: "bachelors-buttons",
    title: "Bachelor's Buttons",
    entityType: "herb",
    summary: "Worn on the breast or kept in the pocket to attract the love of a man.",
    spiritualProperties: "Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "balm-lemon",
    slug: "balm-lemon",
    title: "Lemon Balm",
    entityType: "herb",
    summary: "Soaked in wine or carried to influence and attract love, and used in healing.",
    spiritualProperties: "Love, Success, Healing",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "Soak the herb in wine for several hours, strain, and share with a friend.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "balm-of-gilead",
    slug: "balm-of-gilead",
    title: "Balm of Gilead",
    entityType: "herb",
    summary: "Used to mend a broken heart, attract a new love, and burned to manifest spirits.",
    spiritualProperties: "Love, Manifestations, Protection, Healing",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Burn as a material basis for spirits.",
    careNote: "Ensure you have the correct botanical species.",
    isPremium: false,
  },
  {
    id: "barley",
    slug: "barley",
    title: "Barley",
    entityType: "herb",
    summary: "Used in love spells and scattered on the ground to keep evil and negativity away.",
    spiritualProperties: "Love, Healing, Protection",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "Scatter on the ground to ward off evil.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bedstraw-fragrant",
    slug: "bedstraw-fragrant",
    title: "Fragrant Bedstraw",
    entityType: "herb",
    summary: "Worn or carried in magical applications to attract love.",
    spiritualProperties: "Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "beet",
    slug: "beet",
    title: "Beet",
    entityType: "herb",
    summary: "Beet juice is used as a magical ink in love magic or as a blood substitute.",
    spiritualProperties: "Love",
    correspondences: "Planet: Saturn, Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "Large amounts of the leaf can be harmful.",
    isPremium: false,
  },
  {
    id: "bergamot-orange",
    slug: "bergamot-orange",
    title: "Orange Bergamot",
    entityType: "herb",
    summary: "Slipped into wallets and purses to attract money and success.",
    spiritualProperties: "Money",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Rub fresh leaves onto money before spending it to ensure its return.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bistort",
    slug: "bistort",
    title: "Bistort",
    entityType: "herb",
    summary: "Carried in sachets to attract wealth and burned to drive out poltergeists.",
    spiritualProperties: "Psychic Powers, Prophetic Dreams",
    correspondences: "Planet: Saturn, Element: Earth",
    cleansingMethod: "Place under the pillow for prophetic dreams.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bittersweet",
    slug: "bittersweet",
    title: "Bittersweet",
    entityType: "herb",
    summary: "Placed beneath the pillow to forget past loves, or worn to heal and protect.",
    spiritualProperties: "Protection, Healing",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "American Bittersweet is poisonous.",
    isPremium: false,
  },
  {
    id: "bladderwrack",
    slug: "bladderwrack",
    title: "Bladderwrack",
    entityType: "herb",
    summary: "A seaweed used in sea spells, wind spells, and to attract money or psychic powers.",
    spiritualProperties: "Protection, Sea Spells, Wind Spells, Money, Psychic Powers",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bleeding-heart",
    slug: "bleeding-heart",
    title: "Bleeding Heart",
    entityType: "herb",
    summary: "Used in love spells or grown to attract love into one's life.",
    spiritualProperties: "Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "boneset",
    slug: "boneset",
    title: "Boneset",
    entityType: "herb",
    summary: "Used to ward off evil spirits and heavily utilized in exorcisms.",
    spiritualProperties: "Protection, Exorcism",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "Make an infusion and sprinkle about the house to drive away evil.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bracken",
    slug: "bracken",
    title: "Bracken",
    entityType: "herb",
    summary: "Burned outside to bring rain, or placed beneath the pillow for prophetic dreams.",
    spiritualProperties: "Healing, Rain Magic, Prophetic Dreams",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Burn outside to invoke rain.",
    careNote: "Can be poisonous in large amounts.",
    isPremium: false,
  },
  {
    id: "brazil-nut",
    slug: "brazil-nut",
    title: "Brazil Nut",
    entityType: "herb",
    summary: "Carried as a talisman to bring good luck in love affairs.",
    spiritualProperties: "Love",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "Eat only the processed nut.",
    isPremium: false,
  },
  {
    id: "briony",
    slug: "briony",
    title: "Briony",
    entityType: "herb",
    summary: "Used as a substitute for mandrake in money and protection spells.",
    spiritualProperties: "Image Magic, Money, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "bromeliad",
    slug: "bromeliad",
    title: "Bromeliad",
    entityType: "herb",
    summary: "Grown in the home to attract luxury, money, and provide protection.",
    spiritualProperties: "Protection, Money",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "buchu",
    slug: "buchu",
    title: "Buchu",
    entityType: "herb",
    summary: "Drunk as an infusion to foretell the future or burned to produce prophetic dreams.",
    spiritualProperties: "Psychic Powers, Prophetic Dreams",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "Burn a small amount with frankincense in the bedroom.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "buckthorn",
    slug: "buckthorn",
    title: "Buckthorn",
    entityType: "herb",
    summary: "Placed near doors or windows to drive away enchantments, sorceries, and evil.",
    spiritualProperties: "Protection, Exorcism, Wishes, Legal Matters",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "R. frangula bark must be aged two years prior to internal use.",
    isPremium: false,
  },
  {
    id: "buckwheat",
    slug: "buckwheat",
    title: "Buckwheat",
    entityType: "herb",
    summary: "Scattered around the house to keep evil out and used in money incenses.",
    spiritualProperties: "Money, Protection",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "Use the seeds to form magic circles on the floor.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cabbage",
    slug: "cabbage",
    title: "Cabbage",
    entityType: "herb",
    summary: "Planted in the garden right after marriage to ensure good luck for a couple.",
    spiritualProperties: "Luck",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cactus",
    slug: "cactus",
    title: "Cactus",
    entityType: "herb",
    summary: "Protective plants grown indoors or outdoors to banish negative energies and prevent burglaries.",
    spiritualProperties: "Protection, Chastity",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "calamus",
    slug: "calamus",
    title: "Calamus",
    entityType: "herb",
    summary: "Strung as beads for healing or kept in kitchen corners to protect against poverty.",
    spiritualProperties: "Luck, Healing, Money, Protection",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Some species are dangerous; avoid taking internally.",
    isPremium: false,
  },
  {
    id: "camellia",
    slug: "camellia",
    title: "Camellia",
    entityType: "herb",
    summary: "Placed in vessels of water on the altar to bring riches and luxury.",
    spiritualProperties: "Riches",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "camphor",
    slug: "camphor",
    title: "Camphor",
    entityType: "herb",
    summary: "Smelled to lessen sexual desire, or placed by the bed to prevent colds.",
    spiritualProperties: "Chastity, Health, Divination",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "caper",
    slug: "caper",
    title: "Caper",
    entityType: "herb",
    summary: "Eaten to cure impotency and used in love and lust formulas.",
    spiritualProperties: "Potency, Lust, Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "carrot",
    slug: "carrot",
    title: "Carrot",
    entityType: "herb",
    summary: "The seeds are eaten to help women become pregnant and to promote lust.",
    spiritualProperties: "Fertility, Lust",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cashew",
    slug: "cashew",
    title: "Cashew",
    entityType: "herb",
    summary: "Used in magical spells to attract money and prosperity.",
    spiritualProperties: "Money",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "castor",
    slug: "castor",
    title: "Castor",
    entityType: "herb",
    summary: "Used to absorb disease and protect against the evil eye.",
    spiritualProperties: "Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "The beans are deadly poisonous.",
    isPremium: false,
  },
  {
    id: "cat-tail",
    slug: "cat-tail",
    title: "Cat Tail",
    entityType: "herb",
    summary: "Carried by women who dislike sex to help arouse sexual desire.",
    spiritualProperties: "Lust",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "celandine",
    slug: "celandine",
    title: "Celandine",
    entityType: "herb",
    summary: "Aids in escaping unwarranted entrapments and imparts good spirits to cure depression.",
    spiritualProperties: "Protection, Escape, Happiness, Legal Matters",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Wear next to the skin and replace every three days.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "celery",
    slug: "celery",
    title: "Celery",
    entityType: "herb",
    summary: "Seeds are chewed for concentration or burned with orris root to increase psychic powers.",
    spiritualProperties: "Mental Powers, Lust, Psychic Powers",
    correspondences: "Planet: Mercury, Element: Fire",
    cleansingMethod: "Burn with orris root to increase psychic powers.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "centaury",
    slug: "centaury",
    title: "Centaury",
    entityType: "herb",
    summary: "The smoke from burning this herb is traditionally used to drive off snakes.",
    spiritualProperties: "Snake-Removing",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Burn or fume to drive off snakes.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chamomile-german",
    slug: "chamomile-german",
    title: "German Chamomile",
    entityType: "herb",
    summary: "Used in calming and sleep incenses, and to combat curses and spells.",
    spiritualProperties: "Calm, Sleep, Money",
    correspondences: "Planet: Sun, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chestnut",
    slug: "chestnut",
    title: "Chestnut",
    entityType: "herb",
    summary: "Used in love spells and fed to a loved one to encourage affection.",
    spiritualProperties: "Love",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chickweed",
    slug: "chickweed",
    title: "Chickweed",
    entityType: "herb",
    summary: "Carried or used in spells designed to attract a love or maintain a relationship.",
    spiritualProperties: "Fidelity, Love",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Harvest from fertilizer-free environments.",
    isPremium: false,
  },
  {
    id: "chicory",
    slug: "chicory",
    title: "Chicory",
    entityType: "herb",
    summary: "Used to remove obstacles and obtain favors from great persons.",
    spiritualProperties: "Removing Obstacles, Invisibility, Favors, Frugality",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Anoint your body with chicory juice.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chili-pepper",
    slug: "chili-pepper",
    title: "Chili Pepper",
    entityType: "herb",
    summary: "Used to ensure a mate's fidelity or to break curses and hexes.",
    spiritualProperties: "Fidelity, Hex-Breaking, Love",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Cross two peppers, tie with a red ribbon, and place beneath the pillow.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chrysanthemum",
    slug: "chrysanthemum",
    title: "Chrysanthemum",
    entityType: "herb",
    summary: "Protects against the wrath of gods, guards gardens from evil, and cures drunkenness.",
    spiritualProperties: "Protection",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "citron",
    slug: "citron",
    title: "Citron",
    entityType: "herb",
    summary: "Eaten to increase psychic powers and used in healing spells.",
    spiritualProperties: "Psychic Powers, Healing",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "club-moss",
    slug: "club-moss",
    title: "Club Moss",
    entityType: "herb",
    summary: "Carried for protection and to receive blessings from the Gods.",
    spiritualProperties: "Protection, Power",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "Take a purification bath before uprooting the plant with a silver blade.",
    careNote: "None specified.",
    isPremium: false,
  },
];

// ── Crystals, Stones & Minerals (50) ─────────────────────────────────────────

const CRYSTAL_SEEDS: LibraryEntrySeed[] = [
  {
    id: "clear-quartz-crystal",
    slug: "clear-quartz-crystal",
    title: "Clear Quartz Crystal",
    entityType: "crystal",
    summary: "A versatile crystal used to empower tools, enhance psychic abilities, and act as a spiritual vacuum cleaner.",
    spiritualProperties: "Psychic Powers, Empowering, Cleansing, Aura Repair",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "Bathe in salt water or Florida Water, or expose to sunlight/moonlight.",
    careNote: "Requires periodic cleansing as it absorbs negative energy like a vacuum.",
    isPremium: false,
  },
  {
    id: "holed-stone",
    slug: "holed-stone",
    title: "Holed Stone (Hag Stone)",
    entityType: "stone",
    summary: "Naturally perforated pebbles considered priceless gifts from Earth, used to prevent nightmares and protect against malevolent spirits.",
    spiritualProperties: "Protection, Psychic Powers, Fertility, Dream Magic",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "Cannot be manufactured; must be found in nature.",
    isPremium: false,
  },
  {
    id: "lodestone",
    slug: "lodestone",
    title: "Lodestone (Magnetite)",
    entityType: "mineral",
    summary: "Magnetic iron ore utilized to attract money, success, and love, or to draw physical pain out of the body.",
    spiritualProperties: "Money, Love, Success, Healing, Drawing Power",
    correspondences: "Element: Earth",
    cleansingMethod: "Bathe in wine or spring water, or place in dirt to rest when depleted.",
    careNote: "Must be regularly 'fed' with magnetic sand (iron filings) to maintain its life-force.",
    isPremium: false,
  },
  {
    id: "amethyst",
    slug: "amethyst",
    title: "Amethyst",
    entityType: "crystal",
    summary: "A purple crystal used for spiritual cleansing, preventing intoxication, breaking bad habits, and relieving headaches.",
    spiritualProperties: "Healing, Protection, Breaking Habits, Space Cleansing",
    correspondences: "Deity: Dionysus",
    cleansingMethod: "Cleanse and recharge when the stone begins to look dull.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "malachite",
    slug: "malachite",
    title: "Malachite",
    entityType: "crystal",
    summary: "Known as the merchant's stone, it is used to attract business success and act as a spiritual vacuum in room corners.",
    spiritualProperties: "Money, Business Success, Space Cleansing",
    correspondences: "Astrological Sign: Libra",
    cleansingMethod: "Cleanse and recharge when it looks dull.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "obsidian",
    slug: "obsidian",
    title: "Obsidian",
    entityType: "stone",
    summary: "A rare volcanic glass historically used by the Aztecs to craft magic mirrors for divination and spirit communication.",
    spiritualProperties: "Divination, Spirit Summoning",
    correspondences: "Deity: Tezcatlipoca",
    cleansingMethod: "Pass through incense smoke or wash with spring water.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "iron-pyrite",
    slug: "iron-pyrite",
    title: "Iron Pyrite (Fool's Gold)",
    entityType: "mineral",
    summary: "Often used as a substitute for obsidian in Aztec magic mirrors and carried as a charm for financial luck.",
    spiritualProperties: "Money, Luck, Divination",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bloodstone",
    slug: "bloodstone",
    title: "Bloodstone",
    entityType: "crystal",
    summary: "A green stone flecked with red, used to heal blood disorders, enhance fertility, and bring success in court.",
    spiritualProperties: "Healing, Fertility, Legal Matters",
    correspondences: "Deity: Isis",
    cleansingMethod: "Soak in rosemary water or hydrosol.",
    careNote: "Must be in direct contact with skin or laid over the womb for active healing.",
    isPremium: false,
  },
  {
    id: "lapis-lazuli",
    slug: "lapis-lazuli",
    title: "Lapis Lazuli",
    entityType: "crystal",
    summary: "Provides eloquence in speech, relieves speech disorders, attracts love, and is used to prevent miscarriage.",
    spiritualProperties: "Eloquence, Healing, Protection, Love",
    correspondences: "Deity: Ishtar, Planet: Venus",
    cleansingMethod: "None specified.",
    careNote: "Most effective when worn over the throat chakra.",
    isPremium: false,
  },
  {
    id: "serpentine",
    slug: "serpentine",
    title: "Serpentine",
    entityType: "stone",
    summary: "A serpent stone worn to regulate milk supply, protect against snakebites, and evoke past-life memories.",
    spiritualProperties: "Healing, Lactation, Past-Life Regression, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "agate",
    slug: "agate",
    title: "Agate",
    entityType: "stone",
    summary: "A protective talisman carried to prevent falls while riding and to provide safety from snakes and scorpions.",
    spiritualProperties: "Protection, Safety",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "More potent when engraved with specific imagery.",
    isPremium: false,
  },
  {
    id: "turquoise",
    slug: "turquoise",
    title: "Turquoise",
    entityType: "crystal",
    summary: "Perceived as a piece of the sky, this stone provides general protection, good fortune, and fades to warn of illness.",
    spiritualProperties: "Protection, Health Warning, Good Fortune",
    correspondences: "Element: Air/Water",
    cleansingMethod: "None specified.",
    careNote: "It is believed to physically fade or crack in the presence of ill-health.",
    isPremium: false,
  },
  {
    id: "coral",
    slug: "coral",
    title: "Coral",
    entityType: "stone",
    summary: "Metaphysically perceived as the ocean's menstrual blood, it offers protection and pales to warn of illness.",
    spiritualProperties: "Protection, Health Warning, Lactation",
    correspondences: "Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "amber",
    slug: "amber",
    title: "Amber",
    entityType: "stone",
    summary: "Fossilized tree resin used as a wishing stone, a charm for romantic luck, and to absorb body heat to ward off chills.",
    spiritualProperties: "Love, Luck, Health, Wishes",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "Not a true mineral, but treated as one magically.",
    isPremium: false,
  },
  {
    id: "diamond",
    slug: "diamond",
    title: "Diamond",
    entityType: "crystal",
    summary: "Promotes self-confidence in sexual matters, relieves inhibitions, and provides a cleansing, purifying energy.",
    spiritualProperties: "Fidelity, Healing, Purification",
    correspondences: "None specified.",
    cleansingMethod: "Bathe in spring water enhanced with hibiscus flower essence.",
    careNote: "Often extracts negative emotions from its mining history; requires thorough cleansing.",
    isPremium: false,
  },
  {
    id: "emerald",
    slug: "emerald",
    title: "Emerald",
    entityType: "crystal",
    summary: "A precious green stone used to attract and stabilize love, and to soothe and heal weakness of the eyes.",
    spiritualProperties: "Love, Fidelity, Healing",
    correspondences: "None specified.",
    cleansingMethod: "Steep in spring water overnight, exposed to moonlight.",
    careNote: "Often carries traumatic historical energy from its extraction; needs profound cleansing.",
    isPremium: false,
  },
  {
    id: "ruby",
    slug: "ruby",
    title: "Ruby",
    entityType: "crystal",
    summary: "Empowers the blood system, prevents miscarriage, draws wealth, and fades or grows dull in the presence of anemia.",
    spiritualProperties: "Health Warning, Wealth, Fertility",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Steep in pure spring water to create a healing elixir.",
    careNote: "Must be in direct contact with skin to provide health warnings.",
    isPremium: false,
  },
  {
    id: "sapphire",
    slug: "sapphire",
    title: "Sapphire",
    entityType: "crystal",
    summary: "A protective talisman against violence, skin disorders, and a powerful attractor of wealth and financial stability.",
    spiritualProperties: "Protection, Wealth, Healing",
    correspondences: "None specified.",
    cleansingMethod: "Place in spring water under the light of the Full Moon.",
    careNote: "Can cause fluctuations in fortune for some individuals.",
    isPremium: false,
  },
  {
    id: "star-sapphire",
    slug: "star-sapphire",
    title: "Star Sapphire",
    entityType: "crystal",
    summary: "A luxurious gemstone used specifically as a powerful tool for scrying and divination.",
    spiritualProperties: "Divination, Psychic Powers",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Gaze at the center of the gemstone's cross with unfocused eyes to scry.",
    isPremium: false,
  },
  {
    id: "aquamarine",
    slug: "aquamarine",
    title: "Aquamarine",
    entityType: "crystal",
    summary: "A soothing stone used for scrying and placed on the body to ease the transition of death.",
    spiritualProperties: "Divination, Transition, Healing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "smoky-quartz",
    slug: "smoky-quartz",
    title: "Smoky Quartz",
    entityType: "crystal",
    summary: "Beneficial for communicating with ghosts, protecting night travelers, and shielding against microwave radiation.",
    spiritualProperties: "Spirit Summoning, Protection, Divination",
    correspondences: "None specified.",
    cleansingMethod: "Cleanse frequently when used for radiation protection.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "jet",
    slug: "jet",
    title: "Jet",
    entityType: "stone",
    summary: "Crystallized botanical material used to induce sleep, banish malevolent spirits, and protect against acts of violence.",
    spiritualProperties: "Protection, Banishing, Sleep",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "True jet can be pierced with a needle; avoid plastic replications.",
    isPremium: false,
  },
  {
    id: "petrified-wood",
    slug: "petrified-wood",
    title: "Petrified Wood",
    entityType: "stone",
    summary: "Fossilized wood believed to retain ancient memories, used to access past-life regression in dreams.",
    spiritualProperties: "Past-Life Memories, Psychic Powers",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Hold in hand or wear around the neck while sleeping.",
    isPremium: false,
  },
  {
    id: "cuprite",
    slug: "cuprite",
    title: "Cuprite",
    entityType: "crystal",
    summary: "A brown-toned crystal believed to evoke long-buried memories and assist in past-life regression.",
    spiritualProperties: "Past-Life Memories",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "garnet",
    slug: "garnet",
    title: "Garnet",
    entityType: "crystal",
    summary: "A vividly red crystal used to evoke past-life memories and placed in medicine bags for vitality and protection.",
    spiritualProperties: "Past-Life Memories, Protection, Vitality",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "jasper",
    slug: "jasper",
    title: "Jasper",
    entityType: "crystal",
    summary: "Especially the brown variety, this stone is strongly associated with aiding astral travel and accessing past lives.",
    spiritualProperties: "Astral Projection, Past-Life Memories",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "variscite",
    slug: "variscite",
    title: "Variscite",
    entityType: "crystal",
    summary: "A stone recognized for its ability to help the user recall and access past-life memories.",
    spiritualProperties: "Past-Life Memories",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "moldavite",
    slug: "moldavite",
    title: "Moldavite",
    entityType: "crystal",
    summary: "A delicate green meteorite-impact crystal that blends terrestrial and extraterrestrial energies for astral travel.",
    spiritualProperties: "Astral Projection, Psychic Powers",
    correspondences: "None specified.",
    cleansingMethod: "Bathe in spring water with emergency flower remedy (e.g., Rescue Remedy).",
    careNote: "Fragile; salt may damage this delicate crystal.",
    isPremium: false,
  },
  {
    id: "staurolite",
    slug: "staurolite",
    title: "Staurolite (Cross-stone)",
    entityType: "crystal",
    summary: "Known as 'fairy tears', these twinned cross-crystals are used for scrying and to protect against car accidents.",
    spiritualProperties: "Protection, Divination",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Lacks the luminosity of sapphires, making scrying more difficult.",
    isPremium: false,
  },
  {
    id: "amazonite",
    slug: "amazonite",
    title: "Amazonite",
    entityType: "crystal",
    summary: "Bestows the courage of Amazon warriors, enhances personal psychic power, and is steeped to make healing eye-washes.",
    spiritualProperties: "Courage, Healing, Psychic Powers",
    correspondences: "None specified.",
    cleansingMethod: "Place in pure spring water overnight to create an eye-wash.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "topaz",
    slug: "topaz",
    title: "Topaz",
    entityType: "crystal",
    summary: "A crystal used to repel nightmares and applied over bandaged areas to speed the healing of burns.",
    spiritualProperties: "Healing, Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "angelite",
    slug: "angelite",
    title: "Angelite",
    entityType: "crystal",
    summary: "A blue crystal utilized to repel nightmares and summon angels or other beneficial spirits during sleep.",
    spiritualProperties: "Spirit Summoning, Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chrysolite",
    slug: "chrysolite",
    title: "Chrysolite",
    entityType: "crystal",
    summary: "Repels nightmares and, when filled with donkey's mane hair, is tied to the left arm to ease irrational fears.",
    spiritualProperties: "Courage, Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "citrine",
    slug: "citrine",
    title: "Citrine",
    entityType: "crystal",
    summary: "A bright crystal traditionally used in sleep magic to repel and relieve nightmares.",
    spiritualProperties: "Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "onyx",
    slug: "onyx",
    title: "Onyx",
    entityType: "crystal",
    summary: "A black crystal generally used to halt nightmares, though it evokes unpredictable personal reactions in some.",
    spiritualProperties: "Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Can occasionally cause nightmares instead of curing them; monitor reactions.",
    isPremium: false,
  },
  {
    id: "flint",
    slug: "flint",
    title: "Flint",
    entityType: "stone",
    summary: "Perceived metaphysically as Earth's bones, it provides unfailing, perpetually vigilant magical protection.",
    spiritualProperties: "Protection",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "black-tourmaline",
    slug: "black-tourmaline",
    title: "Black Tourmaline",
    entityType: "crystal",
    summary: "Creates a powerful shield against psychic vampires and actively repels anger, danger, and malevolent energy.",
    spiritualProperties: "Protection, Banishing",
    correspondences: "None specified.",
    cleansingMethod: "Cleanse frequently to maintain full strength.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "labradorite",
    slug: "labradorite",
    title: "Labradorite",
    entityType: "crystal",
    summary: "Repairs, cleanses, and strengthens the aura while protecting against psychic vampires and encouraging perseverance.",
    spiritualProperties: "Aura Repair, Protection, Perseverance",
    correspondences: "None specified.",
    cleansingMethod: "Maintain a regular cleansing schedule if used frequently.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "beryl",
    slug: "beryl",
    title: "Beryl",
    entityType: "crystal",
    summary: "Used to cement romance, restore hostile friendships, and summon water elementals when engraved.",
    spiritualProperties: "Love, Friendship, Spirit Summoning",
    correspondences: "Deity: Poseidon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "rose-quartz",
    slug: "rose-quartz",
    title: "Rose Quartz",
    entityType: "crystal",
    summary: "A romantic stone that draws lovers towards you and transforms anger and resentment into affection.",
    spiritualProperties: "Love, Peace",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Can draw lovers overwhelmingly fast; pair with amethyst for stability.",
    isPremium: false,
  },
  {
    id: "jade",
    slug: "jade",
    title: "Jade",
    entityType: "crystal",
    summary: "Carved into auspicious shapes, it is worn slung around the hips to protect and heal kidney function.",
    spiritualProperties: "Healing",
    correspondences: "None specified.",
    cleansingMethod: "Pass through sandalwood smoke periodically.",
    careNote: "Empower by exposing it to moonlight.",
    isPremium: false,
  },
  {
    id: "hematite",
    slug: "hematite",
    title: "Hematite",
    entityType: "crystal",
    summary: "A stone that magically enhances courage and daring, while stimulating the healing of physical wounds.",
    spiritualProperties: "Courage, Healing, Protection",
    correspondences: "Planet: Mars",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "anachitis",
    slug: "anachitis",
    title: "Anachitis",
    entityType: "crystal",
    summary: "A gemstone historically held in the hand or placed on an altar to summon water elementals (undines).",
    spiritualProperties: "Spirit Summoning",
    correspondences: "Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "synochitis",
    slug: "synochitis",
    title: "Synochitis",
    entityType: "crystal",
    summary: "A stone used in conjunction with anachitis to keep summoned water elementals in place for communication.",
    spiritualProperties: "Spirit Summoning, Binding",
    correspondences: "Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "eaglestone",
    slug: "eaglestone",
    title: "Eaglestone",
    entityType: "stone",
    summary: "A ferruginous pebble containing a smaller stone within, used to aid conception, ease childbirth, and prevent miscarriage.",
    spiritualProperties: "Fertility, Healing, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Cannot be bought; must be found in nature (usually streams) to be effective.",
    isPremium: false,
  },
  {
    id: "sugilite",
    slug: "sugilite",
    title: "Sugilite",
    entityType: "crystal",
    summary: "A crystal gemstone allegedly beneficial for individuals suffering from autism and communication barriers.",
    spiritualProperties: "Healing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "pearl",
    slug: "pearl",
    title: "Pearl",
    entityType: "mineral",
    summary: "An organic gemstone used to enhance the immune system, encourage longevity, and promote healthy lactation.",
    spiritualProperties: "Health, Longevity, Lactation",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Run fingers through a bowl of real pearls to stimulate health.",
    isPremium: false,
  },
  {
    id: "fluorite",
    slug: "fluorite",
    title: "Fluorite",
    entityType: "crystal",
    summary: "A crystal placed over the Third Eye to open the gates of psychic reception and encourage deep meditation.",
    spiritualProperties: "Psychic Powers, Dream Magic",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "sodalite",
    slug: "sodalite",
    title: "Sodalite",
    entityType: "crystal",
    summary: "A stone believed capable of magically protecting the wearer against high frequency antennae and microwave radiation.",
    spiritualProperties: "Protection",
    correspondences: "None specified.",
    cleansingMethod: "Intensely cleanse on a frequent basis.",
    careNote: "Does not replace practical safety measures but enhances them.",
    isPremium: false,
  },
  {
    id: "herkimer-diamond",
    slug: "herkimer-diamond",
    title: "Herkimer Diamond",
    entityType: "crystal",
    summary: "A specialized quartz used for distance healing and to protect the user from radiation and negative energy.",
    spiritualProperties: "Healing, Protection",
    correspondences: "None specified.",
    cleansingMethod: "Intensely cleanse on a frequent basis.",
    careNote: "Often attached to ritual wands for added protection during use.",
    isPremium: false,
  },
];

// ── Metals, Earth, Waters, Liquids, Tools, Charms & Organics (50) ────────────

const MISC_SEEDS: LibraryEntrySeed[] = [
  {
    id: "iron",
    slug: "iron",
    title: "Iron",
    entityType: "metal",
    summary: "Known as the Metal of Heaven, it repels evil, enhances personal magic power, and invigorates physical vitality.",
    spiritualProperties: "Protection, Power, Vitality",
    correspondences: "None specified.",
    cleansingMethod: "Impervious to spiritual tarnish; does not require cleansing.",
    careNote: "Malevolent spirits cannot bear to be in its presence.",
    isPremium: false,
  },
  {
    id: "gold",
    slug: "gold",
    title: "Gold",
    entityType: "metal",
    summary: "A precious metal utilized in magical rites to project energies of prosperity and life force.",
    spiritualProperties: "Wealth, Vitality",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "silver",
    slug: "silver",
    title: "Silver",
    entityType: "metal",
    summary: "A protective metal highly utilized in lunar magic and fertility charms.",
    spiritualProperties: "Protection, Fertility",
    correspondences: "None specified.",
    cleansingMethod: "Impervious to spiritual tarnish; does not require cleansing.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "copper",
    slug: "copper",
    title: "Copper",
    entityType: "metal",
    summary: "A versatile metal used to attract affection and physically soothe aches when worn.",
    spiritualProperties: "Love, Healing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Attached to red garters or worn as bracelets for arthritis relief.",
    isPremium: false,
  },
  {
    id: "brass",
    slug: "brass",
    title: "Brass",
    entityType: "metal",
    summary: "An alloy metal utilized primarily to create a shield of safety and invite romance.",
    spiritualProperties: "Protection, Love",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "lead",
    slug: "lead",
    title: "Lead",
    entityType: "metal",
    summary: "A heavy metal historically favored for crafting curse tablets and binding spells.",
    spiritualProperties: "Domination, Binding",
    correspondences: "Planet: Saturn",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "tin",
    slug: "tin",
    title: "Tin",
    entityType: "metal",
    summary: "The metal of luck and expansion, often engraved with auspicious words or numbers.",
    spiritualProperties: "Wealth, Luck, Divination",
    correspondences: "Planet: Jupiter",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "moonstone",
    slug: "moonstone",
    title: "Moonstone",
    entityType: "crystal",
    summary: "A lunar stone given as a gift to protect loved ones while they travel.",
    spiritualProperties: "Protection, Psychic Powers, Travel Safety",
    correspondences: "Planet: Moon",
    cleansingMethod: "Activate by exposing it to moonbeams overnight.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "carnelian",
    slug: "carnelian",
    title: "Carnelian",
    entityType: "crystal",
    summary: "Worn on a cord over the umbilical region to prevent and block psychic attacks.",
    spiritualProperties: "Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "tigers-eye",
    slug: "tigers-eye",
    title: "Tiger's Eye",
    entityType: "crystal",
    summary: "A protective gemstone frequently kept in vehicles to prevent accidents and ensure safe journeys.",
    spiritualProperties: "Protection, Travel Safety",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "alexandrite",
    slug: "alexandrite",
    title: "Alexandrite",
    entityType: "crystal",
    summary: "A highly esteemed crystal used to create talismans for powerful distance healing.",
    spiritualProperties: "Healing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "chalcedony",
    slug: "chalcedony",
    title: "Chalcedony",
    entityType: "crystal",
    summary: "Included in psychic charm bags and worn over the breasts to regulate and encourage lactation.",
    spiritualProperties: "Psychic Powers, Healing, Lactation",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Must make contact with the skin for physical healing.",
    isPremium: false,
  },
  {
    id: "sea-salt",
    slug: "sea-salt",
    title: "Sea Salt",
    entityType: "mineral",
    summary: "A fundamental purifying agent used to cast circles, cleanse spaces, and banish negative energies.",
    spiritualProperties: "Purification, Protection, Exorcism",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "Avoid using on fragile crystals like moldavite, as it can damage them.",
    isPremium: false,
  },
  {
    id: "crossroads-dirt",
    slug: "crossroads-dirt",
    title: "Crossroads Dirt",
    entityType: "earth",
    summary: "Soil gathered from a three-way or four-way intersection, utilized in charms to repel the Evil Eye.",
    spiritualProperties: "Protection, Elemental Power",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "Inherent energy is transmitted through contact with the dirt itself.",
    isPremium: false,
  },
  {
    id: "graveyard-dirt",
    slug: "graveyard-dirt",
    title: "Graveyard Dirt",
    entityType: "earth",
    summary: "Soil gathered from an ancestor's grave to achieve success in endeavors or assist in fertility spells.",
    spiritualProperties: "Success, Fertility, Power",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "footprint-dirt",
    slug: "footprint-dirt",
    title: "Footprint Dirt",
    entityType: "earth",
    summary: "Earth collected from someone's footprint to directly interact with their personal energy in spells.",
    spiritualProperties: "Binding, Connection",
    correspondences: "Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "magnetic-sand",
    slug: "magnetic-sand",
    title: "Magnetic Sand",
    entityType: "mineral",
    summary: "Fine iron filings used to 'feed' lodestones and act as a drawing powder for good fortune.",
    spiritualProperties: "Money, Luck, Drawing Power",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Often dyed in colors like gold or green for a festive, optimistic appearance.",
    isPremium: false,
  },
  {
    id: "cascarilla-powder",
    slug: "cascarilla-powder",
    title: "Cascarilla Powder",
    entityType: "mineral",
    summary: "Powdered eggshell added to floor washes and protection spells to seal and enhance cleansing efforts.",
    spiritualProperties: "Protection, Cleansing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "red-brick-dust",
    slug: "red-brick-dust",
    title: "Red Brick Dust",
    entityType: "earth",
    summary: "Dissolved in water with lye and urine to violently scrub away hexes and crossed conditions.",
    spiritualProperties: "Hex-Breaking, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "alum",
    slug: "alum",
    title: "Alum",
    entityType: "mineral",
    summary: "Placed strategically in dishes around a room to eliminate negative feelings and angry behavior.",
    spiritualProperties: "Banishing, Peace",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Must be replaced at least once a week to remain effective.",
    isPremium: false,
  },
  {
    id: "sulfur",
    slug: "sulfur",
    title: "Sulfur",
    entityType: "mineral",
    summary: "A potent banishing agent used in exorcisms to dispel anger, negative entities, and blockages to success.",
    spiritualProperties: "Exorcism, Banishing, Success",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Has a foul odor that forcefully clears an area of both spirits and people.",
    isPremium: false,
  },
  {
    id: "saltpeter",
    slug: "saltpeter",
    title: "Saltpeter",
    entityType: "mineral",
    summary: "Incorporated into intensive protection baths and love-drawing powders for explosive energetic shifts.",
    spiritualProperties: "Protection, Cleansing, Love",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "epsom-salts",
    slug: "epsom-salts",
    title: "Epsom Salts",
    entityType: "mineral",
    summary: "Used alongside sea salt in deeply purifying and protective indigo baths.",
    spiritualProperties: "Purification, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "charcoal",
    slug: "charcoal",
    title: "Charcoal",
    entityType: "mineral",
    summary: "The combustible base utilized to burn loose resins, powders, and botanical incenses for magic.",
    spiritualProperties: "Activation, Exorcism",
    correspondences: "Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "Requires fire safety precautions when lit.",
    isPremium: false,
  },
  {
    id: "i-ching-coins",
    slug: "i-ching-coins",
    title: "I-Ching Coins",
    entityType: "metal",
    summary: "Antique coins treated with deep reverence, flipped or cast for intricate divination purposes.",
    spiritualProperties: "Divination",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Treated with the care shown to prized tarot cards or runes.",
    isPremium: false,
  },
  {
    id: "ocean-water",
    slug: "ocean-water",
    title: "Ocean Water",
    entityType: "water",
    summary: "Living salt water drawn directly from the sea, utilized in profound cleansing baths dedicated to Yemaya.",
    spiritualProperties: "Cleansing, Healing, Lunar Magic",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Gather from distinct waves when multiple bottles are needed.",
    isPremium: false,
  },
  {
    id: "spring-water",
    slug: "spring-water",
    title: "Spring Water",
    entityType: "water",
    summary: "Pure natural water used to steep crystals, wash scrying tools, and prepare healing elixirs.",
    spiritualProperties: "Healing, Scrying, Cleansing",
    correspondences: "Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "rainwater",
    slug: "rainwater",
    title: "Rainwater",
    entityType: "water",
    summary: "Natural precipitation collected and specifically used to spiritually cleanse and charge magic mirrors.",
    spiritualProperties: "Cleansing, Renewal",
    correspondences: "Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "florida-water",
    slug: "florida-water",
    title: "Florida Water",
    entityType: "liquid",
    summary: "A commercially prepared scented water that cleanses areas and massively empowers any formula it is added to.",
    spiritualProperties: "Cleansing, Empowering, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Dispose of stationary bowls when the scent fades or changes.",
    isPremium: false,
  },
  {
    id: "holy-water",
    slug: "holy-water",
    title: "Holy Water",
    entityType: "liquid",
    summary: "Consecrated water utilized to asperge spaces, bless tools, and provide intense personal purification.",
    spiritualProperties: "Purification, Blessings",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "marie-laveau-water",
    slug: "marie-laveau-water",
    title: "Marie Laveau Water",
    entityType: "liquid",
    summary: "A specialized charged water formulation used extensively in New Orleans traditions for aura and space cleansing.",
    spiritualProperties: "Cleansing, Purification",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "notre-dame-water",
    slug: "notre-dame-water",
    title: "Notre Dame Water",
    entityType: "liquid",
    summary: "A highly recommended cleansing water used to wash crystal balls and asperge sick rooms.",
    spiritualProperties: "Cleansing, Healing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "war-water",
    slug: "war-water",
    title: "War Water",
    entityType: "liquid",
    summary: "A dual-purpose formula of psychic warfare that causes hexes, but also effectively repels and removes them.",
    spiritualProperties: "Hexing, Hex-Breaking, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "peace-water",
    slug: "peace-water",
    title: "Peace Water",
    entityType: "liquid",
    summary: "A magically charged fluid formulation dispersed through the environment to encourage peace and tranquility.",
    spiritualProperties: "Peace, Calm",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "indigo-water",
    slug: "indigo-water",
    title: "Indigo Water",
    entityType: "liquid",
    summary: "Blue-tinted water added to baths to cleanse the aura and guard against the Evil Eye.",
    spiritualProperties: "Cleansing, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Will stain fabrics blue; use with appropriate caution.",
    isPremium: false,
  },
  {
    id: "rose-of-jericho-water",
    slug: "rose-of-jericho-water",
    title: "Rose of Jericho Water",
    entityType: "liquid",
    summary: "Water in which a Rose of Jericho has rested, used as an extremely effective spiritual asperging cleanser.",
    spiritualProperties: "Cleansing, Resurrection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "tar-water",
    slug: "tar-water",
    title: "Tar Water",
    entityType: "liquid",
    summary: "A potent liquid formula dispersed through homes to provide heavy-duty space cleansing.",
    spiritualProperties: "Cleansing, Banishing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "magic-mirror",
    slug: "magic-mirror",
    title: "Magic Mirror",
    entityType: "tool",
    summary: "Used to capture the sun's reflection to banish demons, or for deep scrying and spirit communication.",
    spiritualProperties: "Divination, Protection, Banishing",
    correspondences: "Element: Fire",
    cleansingMethod: "Wash with salt water or pass through incense smoke.",
    careNote: "Keep covered in dark silk or velvet reserved for ritual use alone.",
    isPremium: false,
  },
  {
    id: "broom-besom",
    slug: "broom-besom",
    title: "Broom (Besom)",
    entityType: "tool",
    summary: "A tool crafted from specific magical branches to physically and spiritually sweep away debris and negativity.",
    spiritualProperties: "Purification, Cleansing",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Single-use purification brooms should be disassembled and buried outside after use.",
    isPremium: false,
  },
  {
    id: "crystal-ball",
    slug: "crystal-ball",
    title: "Crystal Ball",
    entityType: "tool",
    summary: "A sphere used for divination, scrying, and summoning spirits from its depths.",
    spiritualProperties: "Divination, Psychic Powers",
    correspondences: "None specified.",
    cleansingMethod: "Cleanse with vinegar water, mugwort infusion, or charged waters.",
    careNote: "Must be kept physically dust-free; cover with dark cloth when not in use.",
    isPremium: false,
  },
  {
    id: "magic-wand",
    slug: "magic-wand",
    title: "Magic Wand",
    entityType: "tool",
    summary: "An implement carved from woods like hawthorn or ash used to direct magical energy.",
    spiritualProperties: "Power Direction, Evocation",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Attaching a clear quartz crystal enhances its effectiveness.",
    isPremium: false,
  },
  {
    id: "cauldron",
    slug: "cauldron",
    title: "Cauldron",
    entityType: "tool",
    summary: "An iron vessel utilized to brew potions, simmer botanicals, or act as a safe incense burner.",
    spiritualProperties: "Transformation, Creation",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "singing-bowl",
    slug: "singing-bowl",
    title: "Singing Bowl",
    entityType: "tool",
    summary: "A metallic bowl that generates sound vibrations to clear space and replenish energy following a cleansing.",
    spiritualProperties: "Cleansing, Energizing",
    correspondences: "None specified.",
    cleansingMethod: "Pass through incense smoke to cleanse.",
    careNote: "Store in soft, heavy fabric like velvet; improves with frequent use.",
    isPremium: false,
  },
  {
    id: "sistrum",
    slug: "sistrum",
    title: "Sistrum",
    entityType: "tool",
    summary: "A sacred rattle representing the Eye of Ra, shaken to chase away evil and produce a cleansed atmosphere.",
    spiritualProperties: "Cleansing, Banishing",
    correspondences: "Deity: Hathor / Ra",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "mojo-bag",
    slug: "mojo-bag",
    title: "Mojo Bag",
    entityType: "tool",
    summary: "A small drawstring bag filled with botanical and mineral charms to serve as a portable spell or personal altar.",
    spiritualProperties: "Versatile (Protection, Love, Money)",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Often anointed or 'fed' with condition oils to keep the spell active.",
    isPremium: false,
  },
  {
    id: "poppet",
    slug: "poppet",
    title: "Poppet",
    entityType: "tool",
    summary: "A figure formed from clay, cloth, or roots utilized in image magic to represent an individual.",
    spiritualProperties: "Image Magic, Healing, Binding",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "milagro",
    slug: "milagro",
    title: "Milagro",
    entityType: "charm",
    summary: "Small metal charms shaped like human anatomical parts, used to petition spirits for targeted healing or protection.",
    spiritualProperties: "Healing, Votive Offering",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Often pinned to a fabric-covered board alongside quartz crystals.",
    isPremium: false,
  },
  {
    id: "zuni-stone-fetish",
    slug: "zuni-stone-fetish",
    title: "Zuni Stone Fetish",
    entityType: "charm",
    summary: "Miniature animal carvings that act as vessels for guardian animal spirits to provide protection and power.",
    spiritualProperties: "Protection, Animal Communication",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Must be kept in a protected magic box and regularly 'fed' with corn pollen.",
    isPremium: false,
  },
  {
    id: "maneki-neko",
    slug: "maneki-neko",
    title: "Maneki Neko",
    entityType: "charm",
    summary: "A Japanese beckoning cat amulet that draws prosperity, with black variations used to ward off stalkers.",
    spiritualProperties: "Prosperity, Protection",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Variations in color and detail create different magical impacts.",
    isPremium: false,
  },
  {
    id: "egg",
    slug: "egg",
    title: "Egg",
    entityType: "organic",
    summary: "Highly absorbent natural items used to remove psychic debris, diagnose issues, and remove the Evil Eye.",
    spiritualProperties: "Cleansing, Fertility, Evil Eye Removal",
    correspondences: "None specified.",
    cleansingMethod: "None specified.",
    careNote: "Discard immediately outside the home without touching the broken contents directly.",
    isPremium: false,
  },
];

// ── Combined export ───────────────────────────────────────────────────────────

export const LIBRARY_ENTRY_SEEDS: LibraryEntrySeed[] = [...HERB_SEEDS, ...CRYSTAL_SEEDS, ...MISC_SEEDS];
