export type LibraryEntrySeed = {
  id: string;
  slug: string;
  title: string;
  entityType: "crystal" | "herb" | "candle" | "symbol" | "deity";
  summary: string;
  spiritualProperties: string;
  correspondences: string;
  cleansingMethod: string;
  careNote: string;
  isPremium?: boolean;
};

// ── Herbs (50 from seed_library.json + 4 not covered by JSON) ───────────────

const HERB_SEEDS: LibraryEntrySeed[] = [
  {
    id: "acacia",
    slug: "acacia",
    title: "Acacia",
    entityType: "herb",
    summary: "A protective plant used to ward off evil and stimulate the psychic mind.",
    spiritualProperties: "Protection, Psychic Powers",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Burn the wood with sandalwood as incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "agrimony",
    slug: "agrimony",
    title: "Agrimony",
    entityType: "herb",
    summary: "Protects against goblins and evil, and is used to reverse hexes and send them back to the caster.",
    spiritualProperties: "Protection, Sleep",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "Sprinkle around the area to banish negative energies.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "alfalfa",
    slug: "alfalfa",
    title: "Alfalfa",
    entityType: "herb",
    summary: "Kept in the home to protect against poverty and hunger, and used in money spells.",
    spiritualProperties: "Prosperity, Anti-Hunger, Money",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "Burn and scatter the ashes around the property.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "allspice",
    slug: "allspice",
    title: "Allspice",
    entityType: "herb",
    summary: "Used to attract money and luck, as well as to promote healing.",
    spiritualProperties: "Money, Luck, Healing",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burn as an incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "almond",
    slug: "almond",
    title: "Almond",
    entityType: "herb",
    summary: "Brings success in business ventures, money, and grants the partaker wisdom.",
    spiritualProperties: "Money, Prosperity, Wisdom",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "Bitter almond is not for internal use due to cyanogenic glycosides.",
    isPremium: false,
  },
  {
    id: "aloe",
    slug: "aloe",
    title: "Aloe",
    entityType: "herb",
    summary: "Guards against evil influences and prevents household accidents when grown in the home.",
    spiritualProperties: "Protection, Luck",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "althea",
    slug: "althea",
    title: "Althea",
    entityType: "herb",
    summary: "A good 'spirit-puller' that brings good spirits in during rituals when placed on the altar.",
    spiritualProperties: "Protection, Psychic Powers",
    correspondences: "Element: Water",
    cleansingMethod: "Burn as incense or carry in a sachet.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "amaranth",
    slug: "amaranth",
    title: "Amaranth",
    entityType: "herb",
    summary: "A crown of amaranth flowers worn on the head speeds healing and protects.",
    spiritualProperties: "Healing, Protection, Invisibility",
    correspondences: "Planet: Saturn, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "angelica",
    slug: "angelica",
    title: "Angelica",
    entityType: "herb",
    summary: "Used to remove curses, hexes, and spells that have been cast against you.",
    spiritualProperties: "Exorcism, Protection, Healing, Visions",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Add to bath water or sprinkle around the perimeter of the house.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "anise",
    slug: "anise",
    title: "Anise",
    entityType: "herb",
    summary: "Placed in a pillowcase to prevent nightmares and placed around the magic circle to ward off evil.",
    spiritualProperties: "Protection, Purification, Youth",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "Use in purification baths.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "apple",
    slug: "apple",
    title: "Apple",
    entityType: "herb",
    summary: "A fruit heavily associated with love spells, immortality, and Samhain rituals.",
    spiritualProperties: "Love, Healing, Garden Magic, Immortality",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Seeds are poisonous in large amounts.",
    isPremium: false,
  },
  {
    id: "asafoetida",
    slug: "asafoetida",
    title: "Asafoetida",
    entityType: "herb",
    summary: "Destroys manifestations of spirits if thrown onto a fire or censer during magical rites.",
    spiritualProperties: "Exorcism, Purification, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burn small amounts in exorcism and protection incenses.",
    careNote: "Horrid odor; can cause vomiting.",
    isPremium: false,
  },
  {
    id: "ash",
    slug: "ash",
    title: "Ash",
    entityType: "herb",
    summary: "A staff of ash wards off malign influences, and its leaves induce prophetic dreams.",
    spiritualProperties: "Protection, Prosperity, Sea Rituals, Health",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "basil",
    slug: "basil",
    title: "Basil",
    entityType: "herb",
    summary: "Soothes tempers between lovers and brings wealth to those who carry it.",
    spiritualProperties: "Love, Exorcism, Wealth, Flying, Protection",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "Not safe for infants and toddlers in large quantities.",
    isPremium: false,
  },
  {
    id: "bay",
    slug: "bay",
    title: "Bay",
    entityType: "herb",
    summary: "Induces prophetic dreams, offers protection against poltergeists, and grants physical strength.",
    spiritualProperties: "Protection, Psychic Powers, Healing, Purification, Strength",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Burned or scattered during exorcism rituals.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "belladonna",
    slug: "belladonna",
    title: "Belladonna",
    entityType: "herb",
    summary: "Once used to encourage astral projection and produce visions, but generally avoided today.",
    spiritualProperties: "Astral Projection, Visions",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Extremely poisonous; all parts can be fatal.",
    isPremium: false,
  },
  {
    id: "benzoin",
    slug: "benzoin",
    title: "Benzoin",
    entityType: "herb",
    summary: "Used to clear out negative energy and attract prosperity to a business or home.",
    spiritualProperties: "Purification, Prosperity",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "Burn as an incense to purify.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "wood-betony",
    slug: "wood-betony",
    title: "Wood Betony",
    entityType: "herb",
    summary: "Protects against nightmares and helps reunite quarreling couples when added to food.",
    spiritualProperties: "Protection, Purification, Love",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Scatter around doors and windows to form a protective wall.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "birch",
    slug: "birch",
    title: "Birch",
    entityType: "herb",
    summary: "A purificatory herb used to exorcise spirits and protect against the evil eye and lightning.",
    spiritualProperties: "Protection, Exorcism, Purification",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Gently strike possessed people or animals with birch twigs.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "blackberry",
    slug: "blackberry",
    title: "Blackberry",
    entityType: "herb",
    summary: "Used for magical healing by crawling through its natural arches, and wards off evil spirits.",
    spiritualProperties: "Healing, Money, Protection",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "bloodroot",
    slug: "bloodroot",
    title: "Bloodroot",
    entityType: "herb",
    summary: "Carried or worn to draw love, avert evil spells, and protect the home.",
    spiritualProperties: "Love, Protection, Purification",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Cast a circle of powdered root around the home.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "borage",
    slug: "borage",
    title: "Borage",
    entityType: "herb",
    summary: "Carried to strengthen courage, protect outdoors, and induce psychic powers.",
    spiritualProperties: "Courage, Psychic Powers",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "broom",
    slug: "broom",
    title: "Broom",
    entityType: "herb",
    summary: "Hung in the home to keep evil out and used in spells to raise winds.",
    spiritualProperties: "Purification, Protection, Wind Spells, Divination",
    correspondences: "Planet: Mars, Element: Air",
    cleansingMethod: "Sprinkle the infusion through the house to exorcise poltergeists.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "burdock",
    slug: "burdock",
    title: "Burdock",
    entityType: "herb",
    summary: "Used to ward off negativity and to heal conditions like gout.",
    spiritualProperties: "Protection, Healing",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Cast around the home to ward off negativity.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "caraway",
    slug: "caraway",
    title: "Caraway",
    entityType: "herb",
    summary: "Prevents theft, protects children from illness, and incites lust.",
    spiritualProperties: "Protection, Lust, Health, Anti-theft, Mental Powers",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "carnation",
    slug: "carnation",
    title: "Carnation",
    entityType: "herb",
    summary: "Gives strength and energy to a healing patient and offers protection.",
    spiritualProperties: "Protection, Strength, Healing",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Use dried blossoms in incenses.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "catnip",
    slug: "catnip",
    title: "Catnip",
    entityType: "herb",
    summary: "Creates a psychic bond with cats, attracts good spirits, and forms lasting friendships.",
    spiritualProperties: "Cat Magic, Love, Beauty, Happiness",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cedar",
    slug: "cedar",
    title: "Cedar",
    entityType: "herb",
    summary: "Protects against lightning, draws money, and heals head colds through purification.",
    spiritualProperties: "Healing, Purification, Money, Protection",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Smoulder twigs or burn as incense to purify.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "roman-chamomile",
    slug: "roman-chamomile",
    title: "Roman Chamomile",
    entityType: "herb",
    summary: "Used to attract money, induce sleep, and remove curses cast against you.",
    spiritualProperties: "Money, Sleep, Love, Purification",
    correspondences: "Planet: Sun, Element: Water",
    cleansingMethod: "Sprinkle around property to remove curses.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cherry",
    slug: "cherry",
    title: "Cherry",
    entityType: "herb",
    summary: "Used to attract or stimulate love and to divine the number of years left in one's life.",
    spiritualProperties: "Love, Divination",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Seed and wilted leaf are poisonous.",
    isPremium: false,
  },
  {
    id: "cinnamon",
    slug: "cinnamon",
    title: "Cinnamon",
    entityType: "herb",
    summary: "Raises high spiritual vibrations, draws money, stimulates psychic powers, and offers protection.",
    spiritualProperties: "Spirituality, Success, Healing, Power, Psychic Powers, Lust, Protection, Love",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Burn as an incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cinquefoil",
    slug: "cinquefoil",
    title: "Cinquefoil",
    entityType: "herb",
    summary: "Grants eloquence when asking for favors and ensures restful sleep when placed under the bed.",
    spiritualProperties: "Money, Protection, Prophetic Dreams, Sleep",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Add to purificatory bath sachets.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "clove",
    slug: "clove",
    title: "Clove",
    entityType: "herb",
    summary: "Attracts riches, stops gossip, and drives away hostile or negative forces.",
    spiritualProperties: "Protection, Exorcism, Love, Money",
    correspondences: "Planet: Jupiter, Element: Fire",
    cleansingMethod: "Burn as an incense to purify an area.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "clover",
    slug: "clover",
    title: "Clover",
    entityType: "herb",
    summary: "Different leaves bring different powers: two for love, three for protection, four for magic, five for money.",
    spiritualProperties: "Protection, Money, Love, Fidelity, Exorcism, Success",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Sprinkle red clover infusion to remove negative spirits.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "comfrey",
    slug: "comfrey",
    title: "Comfrey",
    entityType: "herb",
    summary: "Protects travelers and safeguards luggage from being lost or stolen.",
    spiritualProperties: "Safety during Travel, Money",
    correspondences: "Planet: Saturn, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "coriander",
    slug: "coriander",
    title: "Coriander",
    entityType: "herb",
    summary: "Added to love sachets and warm wine for lust, and worn to ease headaches.",
    spiritualProperties: "Love, Health, Healing",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "corn",
    slug: "corn",
    title: "Corn",
    entityType: "herb",
    summary: "A symbol of plenty and fertility, used to bless areas and used in divination.",
    spiritualProperties: "Protection, Luck, Divination",
    correspondences: "Planet: Venus, Element: Earth",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "cypress",
    slug: "cypress",
    title: "Cypress",
    entityType: "herb",
    summary: "Eases the mind and allays grief during times of crisis and death.",
    spiritualProperties: "Longevity, Healing, Comfort, Protection",
    correspondences: "Planet: Saturn, Element: Earth",
    cleansingMethod: "Burn dried greenery as incense.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "daffodil",
    slug: "daffodil",
    title: "Daffodil",
    entityType: "herb",
    summary: "Attracts love and good luck, and increases fertility when placed in the bedroom.",
    spiritualProperties: "Love, Fertility, Luck",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "daisy",
    slug: "daisy",
    title: "Daisy",
    entityType: "herb",
    summary: "A flower of coquetry that brings love and can return an absent lover if slept upon.",
    spiritualProperties: "Lust, Love",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Poisonous.",
    isPremium: false,
  },
  {
    id: "dandelion",
    slug: "dandelion",
    title: "Dandelion",
    entityType: "herb",
    summary: "Divines lifespan and is used to send messages of love upon the wind.",
    spiritualProperties: "Divination, Wishes, Calling Spirits",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "dill",
    slug: "dill",
    title: "Dill",
    entityType: "herb",
    summary: "Protects homes from envious individuals, draws money, and stimulates lust.",
    spiritualProperties: "Protection, Money, Lust, Love",
    correspondences: "Planet: Mercury, Element: Fire",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "dragons-blood",
    slug: "dragons-blood",
    title: "Dragon's Blood",
    entityType: "herb",
    summary: "A potent resin burned to entice errant lovers to return and to cure impotency.",
    spiritualProperties: "Love, Protection, Exorcism, Potency",
    correspondences: "Planet: Mars, Element: Fire",
    cleansingMethod: "Burned to clear spaces and protect.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "elder",
    slug: "elder",
    title: "Elder",
    entityType: "herb",
    summary: "Wards off attackers and evil magic, and forces witches to release enchantments.",
    spiritualProperties: "Exorcism, Protection, Healing, Prosperity, Sleep",
    correspondences: "Planet: Venus, Element: Water",
    cleansingMethod: "Scatter leaves and berries to bless a person, place, or thing.",
    careNote: "All parts except the ripe fruit are poisonous.",
    isPremium: false,
  },
  {
    id: "eucalyptus",
    slug: "eucalyptus",
    title: "Eucalyptus",
    entityType: "herb",
    summary: "Stuffs healing poppets and maintains good health when worn or placed beneath the bed.",
    spiritualProperties: "Healing, Protection",
    correspondences: "Planet: Moon, Element: Water",
    cleansingMethod: "None specified.",
    careNote: "Do not use on the faces of small children.",
    isPremium: false,
  },
  {
    id: "eyebright",
    slug: "eyebright",
    title: "Eyebright",
    entityType: "herb",
    summary: "Clears the mind, aids memory, and induces magical clairvoyance.",
    spiritualProperties: "Mental Powers, Psychic Powers",
    correspondences: "Planet: Sun, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "fennel",
    slug: "fennel",
    title: "Fennel",
    entityType: "herb",
    summary: "Guards against evil spirits, prevents tick bites, and is used in purificatory sachets.",
    spiritualProperties: "Protection, Healing, Purification",
    correspondences: "Planet: Mercury, Element: Fire",
    cleansingMethod: "Use in purification sachets.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "lavender",
    slug: "lavender",
    title: "Lavender",
    entityType: "herb",
    summary: "Attracts men, induces peaceful sleep, and guards against cruelty and depression.",
    spiritualProperties: "Love, Protection, Sleep, Chastity, Longevity, Purification, Happiness, Peace",
    correspondences: "Planet: Mercury, Element: Air",
    cleansingMethod: "Burn to purify or add to purification baths.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "rosemary",
    slug: "rosemary",
    title: "Rosemary",
    entityType: "herb",
    summary: "Ensures good sleep, prevents nightmares, preserves youthfulness, and aids memory.",
    spiritualProperties: "Protection, Love, Lust, Mental Powers, Exorcism, Purification, Healing, Sleep, Youth",
    correspondences: "Planet: Sun, Element: Fire",
    cleansingMethod: "Smoulder to rid a place of negativity, especially prior to performing magic.",
    careNote: "None specified.",
    isPremium: false,
  },
  {
    id: "sage",
    slug: "sage",
    title: "Sage",
    entityType: "herb",
    summary: "Ensures a long life, promotes wisdom, and is heavily utilized in healing spells.",
    spiritualProperties: "Immortality, Longevity, Wisdom, Protection, Wishes",
    correspondences: "Planet: Jupiter, Element: Air",
    cleansingMethod: "None specified.",
    careNote: "None specified.",
    isPremium: false,
  },
];

// ── Combined export ───────────────────────────────────────────────────────────

export const LIBRARY_ENTRY_SEEDS: LibraryEntrySeed[] = [...HERB_SEEDS];
