// AUTO-GENERATED from main_data/seed-ritual.json
// Do not edit by hand — regenerate from source JSON if needed.

export const MATERIAL_SEEDS = [
  { id: "egg", slug: "egg", name: "Whole Egg", linkedEntryId: "egg" },
  { id: "florida-water", slug: "florida-water", name: "Florida Water", linkedEntryId: "florida-water" },
  { id: "sea-salt", slug: "sea-salt", name: "Sea Salt", linkedEntryId: "sea-salt" },
  { id: "four-thieves-vinegar", slug: "four-thieves-vinegar", name: "Four Thieves Vinegar", linkedEntryId: null },
  { id: "rosemary-essential-oil", slug: "rosemary-essential-oil", name: "Rosemary Essential Oil", linkedEntryId: null },
  { id: "ocean-water", slug: "ocean-water", name: "Ocean Water", linkedEntryId: "ocean-water" },
  { id: "pine-needles", slug: "pine-needles", name: "Pine Needles", linkedEntryId: null },
  { id: "juniper-hydrosol", slug: "juniper-hydrosol", name: "Juniper Hydrosol", linkedEntryId: null },
  { id: "yarrow-hydrosol", slug: "yarrow-hydrosol", name: "Yarrow Hydrosol", linkedEntryId: null },
  { id: "dried-juniper-berries", slug: "dried-juniper-berries", name: "Dried Juniper Berries", linkedEntryId: null },
  { id: "broom", slug: "broom", name: "Broom", linkedEntryId: "broom-besom" },
  { id: "coconut-candle", slug: "coconut-candle", name: "Coconut Candle", linkedEntryId: null },
  { id: "dried-basil", slug: "dried-basil", name: "Dried Basil", linkedEntryId: "basil" },
  { id: "frankincense", slug: "frankincense", name: "Frankincense", linkedEntryId: null },
  { id: "rosemary", slug: "rosemary", name: "Rosemary", linkedEntryId: "rosemary" },
  { id: "rue", slug: "rue", name: "Rue", linkedEntryId: null },
  { id: "yarrow", slug: "yarrow", name: "Yarrow", linkedEntryId: null },
  { id: "arrowroot-powder", slug: "arrowroot-powder", name: "Arrowroot Powder", linkedEntryId: null },
  { id: "dried-betony", slug: "dried-betony", name: "Dried Betony", linkedEntryId: "wood-betony" },
  { id: "birch-bark-twigs", slug: "birch-bark-twigs", name: "Birch Bark and Twigs", linkedEntryId: "birch" },
  { id: "camphor", slug: "camphor", name: "Camphor", linkedEntryId: "camphor" },
  { id: "cinnamon", slug: "cinnamon", name: "Cinnamon", linkedEntryId: "cinnamon" },
  { id: "myrrh", slug: "myrrh", name: "Myrrh", linkedEntryId: null },
  { id: "sandalwood", slug: "sandalwood", name: "Sandalwood", linkedEntryId: null },
  { id: "dragons-blood-resin", slug: "dragons-blood-resin", name: "Dragon's Blood Resin", linkedEntryId: "dragons-blood" },
  { id: "garlic-peel", slug: "garlic-peel", name: "Garlic Peel", linkedEntryId: null },
  { id: "brown-sugar", slug: "brown-sugar", name: "Brown Sugar", linkedEntryId: null },
  { id: "liquidambar", slug: "liquidambar", name: "Liquidambar", linkedEntryId: null },
  { id: "mastic", slug: "mastic", name: "Mastic", linkedEntryId: null },
  { id: "silver-bell", slug: "silver-bell", name: "Silver or Iron Bell", linkedEntryId: null },
  { id: "singing-bowl", slug: "singing-bowl", name: "Singing Bowl", linkedEntryId: "singing-bowl" },
  { id: "rice-vinegar", slug: "rice-vinegar", name: "Rice Vinegar", linkedEntryId: null },
  { id: "glowing-coals", slug: "glowing-coals", name: "Glowing Coals", linkedEntryId: null },
  { id: "dried-agrimony", slug: "dried-agrimony", name: "Dried Agrimony", linkedEntryId: "agrimony" },
  { id: "peppermint", slug: "peppermint", name: "Peppermint", linkedEntryId: null },
  { id: "dragons-tears", slug: "dragons-tears", name: "Dragon's Tears (Annatto)", linkedEntryId: null },
  { id: "cascarilla-powder", slug: "cascarilla-powder", name: "Cascarilla Powder", linkedEntryId: "cascarilla-powder" },
  { id: "kelp-powder", slug: "kelp-powder", name: "Powdered Kelp", linkedEntryId: null },
  { id: "rum", slug: "rum", name: "Rum", linkedEntryId: null },
  { id: "whole-coconut", slug: "whole-coconut", name: "Whole Coconut", linkedEntryId: null },
  { id: "jessamine-petals", slug: "jessamine-petals", name: "Jessamine Petals", linkedEntryId: null },
  { id: "lodestones", slug: "lodestones", name: "Lodestones", linkedEntryId: "lodestone" },
  { id: "chamomile", slug: "chamomile", name: "Chamomile", linkedEntryId: "roman-chamomile" },
  { id: "elder", slug: "elder", name: "Elder", linkedEntryId: "elder" },
  { id: "mint", slug: "mint", name: "Mint", linkedEntryId: null },
  { id: "mugwort", slug: "mugwort", name: "Mugwort", linkedEntryId: null },
  { id: "high-john-root", slug: "high-john-root", name: "High John the Conqueror Root", linkedEntryId: null },
  { id: "white-onion", slug: "white-onion", name: "White Onion", linkedEntryId: null },
  { id: "raw-white-rice", slug: "raw-white-rice", name: "Raw White Rice", linkedEntryId: null },
  { id: "white-vinegar", slug: "white-vinegar", name: "White Vinegar", linkedEntryId: null },
  { id: "desert-sage", slug: "desert-sage", name: "Desert Sage", linkedEntryId: "sage" },
  { id: "fumitory", slug: "fumitory", name: "Earth Smoke (Fumitory)", linkedEntryId: null },
  { id: "indigo-water", slug: "indigo-water", name: "Indigo Water", linkedEntryId: "indigo-water" },
  { id: "blue-eye-beads", slug: "blue-eye-beads", name: "Blue Eye Beads", linkedEntryId: null },
  { id: "lavender-essential-oil", slug: "lavender-essential-oil", name: "Lavender Essential Oil", linkedEntryId: "lavender" },
  { id: "lovage-root", slug: "lovage-root", name: "Lovage Root", linkedEntryId: null },
  { id: "mandrake-root", slug: "mandrake-root", name: "Mandrake Root", linkedEntryId: null },
  { id: "mate-tea", slug: "mate-tea", name: "Maté Tea", linkedEntryId: null },
  { id: "oak-leaves", slug: "oak-leaves", name: "Oak Leaves", linkedEntryId: null },
  { id: "parsley", slug: "parsley", name: "Parsley", linkedEntryId: null },
  { id: "bay-leaves", slug: "bay-leaves", name: "Bay Leaves", linkedEntryId: "bay" },
  { id: "yucca-root", slug: "yucca-root", name: "Yucca Root", linkedEntryId: null },
  { id: "benzoin", slug: "benzoin", name: "Benzoin", linkedEntryId: "benzoin" },
  { id: "anise-seeds", slug: "anise-seeds", name: "Anise Seeds", linkedEntryId: "anise" },
  { id: "baking-soda", slug: "baking-soda", name: "Baking Soda", linkedEntryId: null },
  { id: "red-roses", slug: "red-roses", name: "Red Roses", linkedEntryId: null },
  { id: "lemon-juice", slug: "lemon-juice", name: "Lemon Juice", linkedEntryId: null },
] as const;

export const RITUAL_SEEDS = [
  {
    id: "egg-personal-cleansing",
    slug: "egg-personal-cleansing",
    title: "Egg Personal Cleansing Spell",
    summary: "Use a whole egg to absorb negative energy and spiritual debris from your aura.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "waning-moon",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 0,
    isPremium: false,
  },
  {
    id: "destroy-all-evil-bath",
    slug: "destroy-all-evil-bath",
    title: "Destroy All Evil Bath",
    summary: "A powerful bath to destroy evil influences and protect the bather.",
    category: "protection",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in protection. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 1,
    isPremium: false,
  },
  {
    id: "ocean-water-asperging",
    slug: "ocean-water-asperging",
    title: "Ocean Water Asperging Spell",
    summary: "Cleanse your space using the elemental power of the ocean.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 2,
    isPremium: false,
  },
  {
    id: "pine-asperging-spell",
    slug: "pine-asperging-spell",
    title: "Pine Asperging Spell",
    summary: "A simple water-based cleanse using pine needles.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 3,
    isPremium: false,
  },
  {
    id: "yarrow-juniper-cleanser",
    slug: "yarrow-juniper-cleanser",
    title: "Yarrow Juniper Cleanser",
    summary: "A potent liquid formula used for space and altar cleansing.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 4,
    isPremium: false,
  },
  {
    id: "broom-cleansing-spell",
    slug: "broom-cleansing-spell",
    title: "Broom Cleansing Spell",
    summary: "Sweep away spiritual dust and negativity from your home.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "waning-moon",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 5,
    isPremium: false,
  },
  {
    id: "coconut-candle-cleanser",
    slug: "coconut-candle-cleanser",
    title: "Coconut Candle Cleanser",
    summary: "Burn coconut-scented candles for long-term spiritual purification.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 60,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 6,
    isPremium: false,
  },
  {
    id: "exorcism-powder",
    slug: "exorcism-powder",
    title: "Exorcism Powder Spell",
    summary: "Eliminate negative emotions and low-level spirit emanations with herbal powder.",
    category: "protection",
    difficulty: "intermediate",
    moonPhase: "waning-moon",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in protection. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 7,
    isPremium: false,
  },
  {
    id: "basic-botanic-fumigation",
    slug: "basic-botanic-fumigation",
    title: "Basic Botanic Fumigation Spell",
    summary: "Burn botanicals to release magical and spiritual antiseptic effects.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 8,
    isPremium: false,
  },
  {
    id: "betony-cleansing-incense",
    slug: "betony-cleansing-incense",
    title: "Betony Cleansing Incense",
    summary: "Disperse negative energy and lurking entities using betony.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 9,
    isPremium: false,
  },
  {
    id: "birch-cleansing-incense",
    slug: "birch-cleansing-incense",
    title: "Birch Cleansing Incense",
    summary: "Burn birch to remove negative energy from your space.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 10,
    isPremium: false,
  },
  {
    id: "cast-out-evil-incense",
    slug: "cast-out-evil-incense",
    title: "Cast Out Evil Incense",
    summary: "A powerful formula to cleanse areas profaned by evil or violence.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "waning-moon",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 11,
    isPremium: false,
  },
  {
    id: "dragons-blood-cleansing-incense",
    slug: "dragons-blood-cleansing-incense",
    title: "Dragon\'s Blood Cleansing Incense",
    summary: "Use dragon\'s blood resin to neutralize negative energy.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 12,
    isPremium: false,
  },
  {
    id: "garlic-cleansing-spell",
    slug: "garlic-cleansing-spell",
    title: "Garlic Cleansing Spell",
    summary: "A potent spiritual formula using garlic peel to flush out negative entities.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "waning-moon",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 13,
    isPremium: false,
  },
  {
    id: "liquidambar-cleansing-incense",
    slug: "liquidambar-cleansing-incense",
    title: "Liquidambar Cleansing Incense",
    summary: "Enhance cleansing power by blending liquidambar with other botanicals.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 14,
    isPremium: false,
  },
  {
    id: "sacred-purification-incense",
    slug: "sacred-purification-incense",
    title: "Sacred Purification Incense",
    summary: "Remove the negative and tainted, leaving an aura of holiness behind.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 15,
    isPremium: false,
  },
  {
    id: "cleansed-by-the-bell",
    slug: "cleansed-by-the-bell",
    title: "Cleansed by the Bell",
    summary: "Use the sound of bells to provide an extremely powerful space cleansing.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 16,
    isPremium: false,
  },
  {
    id: "singing-bowls-cleansing",
    slug: "singing-bowls-cleansing",
    title: "Singing Bowls Cleansing",
    summary: "Wash the space using the serene harmonies of singing bowls.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 17,
    isPremium: false,
  },
  {
    id: "chinese-vinegar-steam-cleanser",
    slug: "chinese-vinegar-steam-cleanser",
    title: "Chinese Vinegar Steam Cleanser",
    summary: "A weekly standard cleansing using the merged powers of water and fire.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 18,
    isPremium: false,
  },
  {
    id: "glittering-coals-vapor-cleanser",
    slug: "glittering-coals-vapor-cleanser",
    title: "Glittering Coals Vapor Cleanser",
    summary: "A quick burst of purification using coals and water.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 19,
    isPremium: false,
  },
  {
    id: "aura-cleansing-floorwash",
    slug: "aura-cleansing-floorwash",
    title: "Aura Cleansing Floorwash",
    summary: "Repel hexes and aggressive cleanse your space with a powerful floorwash.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 20,
    isPremium: false,
  },
  {
    id: "dragons-tears-floorwash",
    slug: "dragons-tears-floorwash",
    title: "Dragon\'s Tears Floorwash",
    summary: "A protective floorwash made from annatto seeds.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 21,
    isPremium: false,
  },
  {
    id: "ocean-floorwash",
    slug: "ocean-floorwash",
    title: "Ocean Water Floorwash",
    summary: "Use ocean water and cascarilla for a deep magical space cleansing.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 22,
    isPremium: false,
  },
  {
    id: "coconut-house-cleansing",
    slug: "coconut-house-cleansing",
    title: "Coconut House Cleansing Spell",
    summary: "Roll a coconut through the house to absorb negativity.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "waning-moon",
    durationMinutes: 45,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 23,
    isPremium: false,
  },
  {
    id: "jessamine-flowers-cleansing",
    slug: "jessamine-flowers-cleansing",
    title: "Jessamine Flowers House Cleansing",
    summary: "Spread jessamine to remove residues of malevolent spells.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 24,
    isPremium: false,
  },
  {
    id: "lodestone-cleansing",
    slug: "lodestone-cleansing",
    title: "Lodestone Cleansing",
    summary: "Use lodestones to magnetically absorb negativity from an area.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 25,
    isPremium: false,
  },
  {
    id: "mother-holles-cleansing",
    slug: "mother-holles-cleansing",
    title: "Mother Holles Cleansing Spell",
    summary: "Burn a blend of herbs associated with Mother Holle for intensive winter cleansing.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 26,
    isPremium: false,
  },
  {
    id: "salt-cleansing-spell",
    slug: "salt-cleansing-spell",
    title: "Salt Cleansing Spell",
    summary: "Sprinkle empowered salt around the home to absorb negativity.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 27,
    isPremium: false,
  },
  {
    id: "florida-water-stationary",
    slug: "florida-water-stationary",
    title: "Florida Water Stationary Cleanser",
    summary: "A stationary liquid trap to absorb negativity.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 28,
    isPremium: false,
  },
  {
    id: "onion-space-cleansing",
    slug: "onion-space-cleansing",
    title: "Onion Space Cleansing Spell",
    summary: "Use onions to vacuum up spiritual dirt from a room.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 29,
    isPremium: false,
  },
  {
    id: "rice-cleansing-spell",
    slug: "rice-cleansing-spell",
    title: "Rice Cleansing Spell",
    summary: "Use raw white rice to absorb spiritual debris.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 30,
    isPremium: false,
  },
  {
    id: "vinegar-cleanser",
    slug: "vinegar-cleanser",
    title: "Vinegar Cleanser",
    summary: "Use plain vinegar as a cheap and strong cleansing agent.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 31,
    isPremium: false,
  },
  {
    id: "desert-sage-bath",
    slug: "desert-sage-bath",
    title: "Desert Sage Bath",
    summary: "Bathe with desert sage to purify and alleviate feeling psychically unclean.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 25,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 32,
    isPremium: false,
  },
  {
    id: "earth-smoke-bath",
    slug: "earth-smoke-bath",
    title: "Earth Smoke Bath",
    summary: "Use fumitory to take a spiritually cleansing bath.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 25,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 33,
    isPremium: false,
  },
  {
    id: "florida-water-personal-cleanser",
    slug: "florida-water-personal-cleanser",
    title: "Florida Water Personal Cleansing Spell",
    summary: "A fast, spontaneous personal cleansing without a tub.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 5,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 34,
    isPremium: false,
  },
  {
    id: "indigo-cleansing-bath",
    slug: "indigo-cleansing-bath",
    title: "Indigo Cleansing Bath",
    summary: "A powerful blue bath to remove negativity.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 35,
    isPremium: false,
  },
  {
    id: "lavender-bath",
    slug: "lavender-bath",
    title: "Lavender Bath",
    summary: "A soothing bath dedicated to Hecate for spiritual washing.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 36,
    isPremium: false,
  },
  {
    id: "lovage-bath",
    slug: "lovage-bath",
    title: "Lovage Bath",
    summary: "Cleanse off degrading traces of failed relationships.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "waning-moon",
    durationMinutes: 25,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 37,
    isPremium: false,
  },
  {
    id: "mandrake-bath",
    slug: "mandrake-bath",
    title: "Mandrake Bath",
    summary: "An emergency, heavy-duty spiritual cleansing bath.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 38,
    isPremium: false,
  },
  {
    id: "mate-cleansing-bath",
    slug: "mate-cleansing-bath",
    title: "Maté Cleansing Bath",
    summary: "Remove minor hexes and the lesser Evil Eye with maté tea.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 39,
    isPremium: false,
  },
  {
    id: "oak-leaf-bath",
    slug: "oak-leaf-bath",
    title: "Oak Leaf Bath",
    summary: "A grounding bath to remove negativity.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 40,
    isPremium: false,
  },
  {
    id: "parsley-bath",
    slug: "parsley-bath",
    title: "Parsley Bath",
    summary: "A cleansing bath (not for use during pregnancy) using parsley.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 25,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 41,
    isPremium: false,
  },
  {
    id: "pine-bay-bath",
    slug: "pine-bay-bath",
    title: "Pine-Bay Bath",
    summary: "A protective and cleansing bath combining pine, bay, vinegar, and lemon.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 42,
    isPremium: false,
  },
  {
    id: "yucca-bath",
    slug: "yucca-bath",
    title: "Yucca Bath",
    summary: "Create cleansing suds from yucca roots to physically and magically clean the body.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 43,
    isPremium: false,
  },
  {
    id: "sacred-cleansing-incense",
    slug: "sacred-cleansing-incense",
    title: "Sacred Cleansing Incense",
    summary: "A personal fumigation spell using sacred resins to leave an aura of holiness.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 15,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 44,
    isPremium: false,
  },
  {
    id: "purification-bath",
    slug: "purification-bath",
    title: "Purification Bath",
    summary: "Bathe with bay leaves and anise for thorough aura purification.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 45,
    isPremium: false,
  },
  {
    id: "quick-fix-aura-cleanser",
    slug: "quick-fix-aura-cleanser",
    title: "Quick Fix Aura Cleanser",
    summary: "A fast bath recipe when you need immediate cleansing.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 20,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 46,
    isPremium: false,
  },
  {
    id: "sage-cleansing-spell",
    slug: "sage-cleansing-spell",
    title: "Sage Cleansing Spell",
    summary: "Use powdered garden sage for a profound spiritual fumigation.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 10,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 47,
    isPremium: false,
  },
  {
    id: "salt-cleansing-bath",
    slug: "salt-cleansing-bath",
    title: "Salt Cleansing Bath",
    summary: "A simple salt bath that creates a powerful psychic shield.",
    category: "cleansing",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 25,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 48,
    isPremium: false,
  },
  {
    id: "seven-roses-bath",
    slug: "seven-roses-bath",
    title: "Seven Roses Bath",
    summary: "A rejuvenating bath to regain innocence and optimism after hardship.",
    category: "cleansing",
    difficulty: "intermediate",
    moonPhase: "any",
    durationMinutes: 30,
    coverImage: "",
    incantation: "With focused breath and steady heart, I now call in cleansing. As I will it, so mote it be.",
    safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
    createdAt: Date.now() + 49,
    isPremium: false,
  },
];

export const RITUAL_STEP_SEEDS = [
  {
    id: "egg-personal-cleansing-step-1",
    ritualId: "egg-personal-cleansing",
    stepOrder: 1,
    title: "Cleanse the Body",
    content: "Pass a whole raw egg over your body, moving from the top downwards, mentally focusing on eliminating any negative psychic debris.",
  },
  {
    id: "egg-personal-cleansing-step-2",
    ritualId: "egg-personal-cleansing",
    stepOrder: 2,
    title: "Dispose of the Egg",
    content: "Take the egg outside, far from your home, and smash it on the ground. Return home via a different, circuitous route without looking back.",
  },
  {
    id: "destroy-all-evil-bath-step-1",
    ritualId: "destroy-all-evil-bath",
    stepOrder: 1,
    title: "Prepare the Water",
    content: "Add at least one cup of Florida Water and one cup of sea salt to a tub filled with warm water.",
  },
  {
    id: "destroy-all-evil-bath-step-2",
    ritualId: "destroy-all-evil-bath",
    stepOrder: 2,
    title: "Add Vinegar",
    content: "Add a generous splash of Four Thieves Vinegar into the tub.",
  },
  {
    id: "destroy-all-evil-bath-step-3",
    ritualId: "destroy-all-evil-bath",
    stepOrder: 3,
    title: "Add Essential Oil",
    content: "Just before you enter the water, add nine drops of essential oil of rosemary.",
  },
  {
    id: "destroy-all-evil-bath-step-4",
    ritualId: "destroy-all-evil-bath",
    stepOrder: 4,
    title: "Bathe",
    content: "Submerge yourself completely to destroy all evil influences.",
  },
  {
    id: "ocean-water-asperging-step-1",
    ritualId: "ocean-water-asperging",
    stepOrder: 1,
    title: "Gather Water",
    content: "Carry ocean water to the area to be cleansed in a glass or metal flask.",
  },
  {
    id: "ocean-water-asperging-step-2",
    ritualId: "ocean-water-asperging",
    stepOrder: 2,
    title: "Asperge",
    content: "Asperge the space as needed, ideally using a fresh rosemary wand to flick the water.",
  },
  {
    id: "pine-asperging-spell-step-1",
    ritualId: "pine-asperging-spell",
    stepOrder: 1,
    title: "Soak Pine",
    content: "Soak pine needles in warm water until the water is infused.",
  },
  {
    id: "pine-asperging-spell-step-2",
    ritualId: "pine-asperging-spell",
    stepOrder: 2,
    title: "Asperge",
    content: "Sprinkle the infused water throughout your home as needed.",
  },
  {
    id: "yarrow-juniper-cleanser-step-1",
    ritualId: "yarrow-juniper-cleanser",
    stepOrder: 1,
    title: "Blend Hydrosols",
    content: "Blend equal parts of juniper berry hydrosol and yarrow hydrosol.",
  },
  {
    id: "yarrow-juniper-cleanser-step-2",
    ritualId: "yarrow-juniper-cleanser",
    stepOrder: 2,
    title: "Add Berries",
    content: "Add a small handful of slightly bruised dried juniper berries to the liquid.",
  },
  {
    id: "yarrow-juniper-cleanser-step-3",
    ritualId: "yarrow-juniper-cleanser",
    stepOrder: 3,
    title: "Cleanse",
    content: "Sprinkle or wipe your altar, aura, or crystals with the liquid.",
  },
  {
    id: "broom-cleansing-spell-step-1",
    ritualId: "broom-cleansing-spell",
    stepOrder: 1,
    title: "Sweep",
    content: "Use a broom to sweep the dust of your home from the west to the east.",
  },
  {
    id: "broom-cleansing-spell-step-2",
    ritualId: "broom-cleansing-spell",
    stepOrder: 2,
    title: "Dispose",
    content: "Collect the gathered dust, burn it, and toss the ashes outdoors.",
  },
  {
    id: "coconut-candle-cleanser-step-1",
    ritualId: "coconut-candle-cleanser",
    stepOrder: 1,
    title: "Light Candle",
    content: "Light a coconut-scented candle in the space needing purification.",
  },
  {
    id: "coconut-candle-cleanser-step-2",
    ritualId: "coconut-candle-cleanser",
    stepOrder: 2,
    title: "Purify",
    content: "Allow the scent of the coconut to permeate the air, releasing long-term spiritual purification in a relaxed manner.",
  },
  {
    id: "exorcism-powder-step-1",
    ritualId: "exorcism-powder",
    stepOrder: 1,
    title: "Grind Herbs",
    content: "Blend dried basil, frankincense, rosemary, rue, and yarrow, and grind into a fine powder.",
  },
  {
    id: "exorcism-powder-step-2",
    ritualId: "exorcism-powder",
    stepOrder: 2,
    title: "Blend Base",
    content: "Blend the herbal powder into a base of arrowroot powder.",
  },
  {
    id: "exorcism-powder-step-3",
    ritualId: "exorcism-powder",
    stepOrder: 3,
    title: "Sprinkle",
    content: "Sprinkle the powder lightly through the area to absorb malignancies in the air.",
  },
  {
    id: "basic-botanic-fumigation-step-1",
    ritualId: "basic-botanic-fumigation",
    stepOrder: 1,
    title: "Prepare Coals",
    content: "Light charcoal in a fireproof dish or censer.",
  },
  {
    id: "basic-botanic-fumigation-step-2",
    ritualId: "basic-botanic-fumigation",
    stepOrder: 2,
    title: "Burn Botanicals",
    content: "Sprinkle frankincense, myrrh, or sage on the lit charcoal.",
  },
  {
    id: "basic-botanic-fumigation-step-3",
    ritualId: "basic-botanic-fumigation",
    stepOrder: 3,
    title: "Waft Smoke",
    content: "Direct the cleansing smoke towards whatever needs cleansing.",
  },
  {
    id: "betony-cleansing-incense-step-1",
    ritualId: "betony-cleansing-incense",
    stepOrder: 1,
    title: "Burn",
    content: "Burn the dried herb betony on hot charcoals.",
  },
  {
    id: "betony-cleansing-incense-step-2",
    ritualId: "betony-cleansing-incense",
    stepOrder: 2,
    title: "Fumigate",
    content: "Let the smoke disperse negative energy, especially if you fear the negativity emanates from yourself.",
  },
  {
    id: "birch-cleansing-incense-step-1",
    ritualId: "birch-cleansing-incense",
    stepOrder: 1,
    title: "Burn Birch",
    content: "Light birch bark and twigs on fire.",
  },
  {
    id: "birch-cleansing-incense-step-2",
    ritualId: "birch-cleansing-incense",
    stepOrder: 2,
    title: "Cleanse",
    content: "Allow the smoke to permeate the area to remove negative energy.",
  },
  {
    id: "cast-out-evil-incense-step-1",
    ritualId: "cast-out-evil-incense",
    stepOrder: 1,
    title: "Blend Ingredients",
    content: "Blend camphor, cinnamon, frankincense, myrrh, and sandalwood together.",
  },
  {
    id: "cast-out-evil-incense-step-2",
    ritualId: "cast-out-evil-incense",
    stepOrder: 2,
    title: "Powder",
    content: "Grind the blended ingredients into a fine powder.",
  },
  {
    id: "cast-out-evil-incense-step-3",
    ritualId: "cast-out-evil-incense",
    stepOrder: 3,
    title: "Burn",
    content: "Sprinkle the powder onto lit charcoal and burn.",
  },
  {
    id: "dragons-blood-cleansing-incense-step-1",
    ritualId: "dragons-blood-cleansing-incense",
    stepOrder: 1,
    title: "Burn Resin",
    content: "Burn dragon\'s blood powder or resin on lit charcoals to provide a potent cleansing.",
  },
  {
    id: "garlic-cleansing-spell-step-1",
    ritualId: "garlic-cleansing-spell",
    stepOrder: 1,
    title: "Grind Peel",
    content: "Place reserved garlic peel in a mortar and pestle, add brown sugar, and pound them together.",
  },
  {
    id: "garlic-cleansing-spell-step-2",
    ritualId: "garlic-cleansing-spell",
    stepOrder: 2,
    title: "Burn",
    content: "Sprinkle the mixture onto lit charcoal or a cast iron pan.",
  },
  {
    id: "garlic-cleansing-spell-step-3",
    ritualId: "garlic-cleansing-spell",
    stepOrder: 3,
    title: "Waft Fumes",
    content: "Waft the fumes over the areas to be cleansed, allowing the aroma to settle.",
  },
  {
    id: "liquidambar-cleansing-incense-step-1",
    ritualId: "liquidambar-cleansing-incense",
    stepOrder: 1,
    title: "Blend",
    content: "Blend frankincense, liquidambar, mastic, and sandalwood.",
  },
  {
    id: "liquidambar-cleansing-incense-step-2",
    ritualId: "liquidambar-cleansing-incense",
    stepOrder: 2,
    title: "Burn",
    content: "Burn the mixture on lit charcoals and waft the smoke as desired.",
  },
  {
    id: "sacred-purification-incense-step-1",
    ritualId: "sacred-purification-incense",
    stepOrder: 1,
    title: "Grind Ingredients",
    content: "Blend and grind benzoin, dragon\'s blood, frankincense, myrrh, sandalwood, and sea salt into a fine powder.",
  },
  {
    id: "sacred-purification-incense-step-2",
    ritualId: "sacred-purification-incense",
    stepOrder: 2,
    title: "Burn",
    content: "Sprinkle the powder onto a lit charcoal and burn.",
  },
  {
    id: "cleansed-by-the-bell-step-1",
    ritualId: "cleansed-by-the-bell",
    stepOrder: 1,
    title: "Ring Bell",
    content: "Ring a silver, iron, or brass bell loudly throughout the space to disperse malevolent entities and negative debris.",
  },
  {
    id: "singing-bowls-cleansing-step-1",
    ritualId: "singing-bowls-cleansing",
    stepOrder: 1,
    title: "Play Bowl",
    content: "Play a Himalayan singing bowl to wash the space and balance yin and yang energies before ritual.",
  },
  {
    id: "chinese-vinegar-steam-cleanser-step-1",
    ritualId: "chinese-vinegar-steam-cleanser",
    stepOrder: 1,
    title: "Boil Vinegar",
    content: "Boil rice vinegar in a shallow pan until it is steaming.",
  },
  {
    id: "chinese-vinegar-steam-cleanser-step-2",
    ritualId: "chinese-vinegar-steam-cleanser",
    stepOrder: 2,
    title: "Carry Steam",
    content: "Very carefully carry the steaming pan through all the rooms, letting the vapors cleanse corners and closets.",
  },
  {
    id: "glittering-coals-vapor-cleanser-step-1",
    ritualId: "glittering-coals-vapor-cleanser",
    stepOrder: 1,
    title: "Toss Coals",
    content: "Toss burning coals into a bowl of water to create a sizzling steam for quick purification.",
  },
  {
    id: "aura-cleansing-floorwash-step-1",
    ritualId: "aura-cleansing-floorwash",
    stepOrder: 1,
    title: "Make Infusion",
    content: "Make a strong infusion from dried agrimony and peppermint using boiling water.",
  },
  {
    id: "aura-cleansing-floorwash-step-2",
    ritualId: "aura-cleansing-floorwash",
    stepOrder: 2,
    title: "Prepare Bucket",
    content: "Strain out the herbs and add the infusion liquid to a bucket of water, along with white vinegar.",
  },
  {
    id: "aura-cleansing-floorwash-step-3",
    ritualId: "aura-cleansing-floorwash",
    stepOrder: 3,
    title: "Wash Floors",
    content: "Cleanse the floors and surfaces with the wash.",
  },
  {
    id: "dragons-tears-floorwash-step-1",
    ritualId: "dragons-tears-floorwash",
    stepOrder: 1,
    title: "Make Infusion",
    content: "Pour boiling water over dragon\'s tears (annatto seeds) to make a strong infusion.",
  },
  {
    id: "dragons-tears-floorwash-step-2",
    ritualId: "dragons-tears-floorwash",
    stepOrder: 2,
    title: "Wash Floors",
    content: "Add the infusion to a bucket of rinse water with vinegar and scrub the floors.",
  },
  {
    id: "ocean-floorwash-step-1",
    ritualId: "ocean-floorwash",
    stepOrder: 1,
    title: "Prepare Water",
    content: "Fill a bucket with ocean water. Add Cascarilla Powder, agar-agar, and powdered kelp.",
  },
  {
    id: "ocean-floorwash-step-2",
    ritualId: "ocean-floorwash",
    stepOrder: 2,
    title: "Wash Floors",
    content: "Use this water to wash your space and magically cleanse the area.",
  },
  {
    id: "coconut-house-cleansing-step-1",
    ritualId: "coconut-house-cleansing",
    stepOrder: 1,
    title: "Prepare Coconut",
    content: "Take a mouthful of rum and spray it over a whole coconut. Sprinkle Cascarilla Powder on the coconut.",
  },
  {
    id: "coconut-house-cleansing-step-2",
    ritualId: "coconut-house-cleansing",
    stepOrder: 2,
    title: "Roll Through House",
    content: "Roll the coconut from the back corner of your home out through the main entrance.",
  },
  {
    id: "coconut-house-cleansing-step-3",
    ritualId: "coconut-house-cleansing",
    stepOrder: 3,
    title: "Dispose at Crossroads",
    content: "Take the coconut to a remote four-way crossroads, throw it hard to crack it open, and walk away without looking back.",
  },
  {
    id: "jessamine-flowers-cleansing-step-1",
    ritualId: "jessamine-flowers-cleansing",
    stepOrder: 1,
    title: "Spread Petals",
    content: "Spread day Jessamine petals throughout the house for spiritual cleansing and to remove malevolent magic.",
  },
  {
    id: "lodestone-cleansing-step-1",
    ritualId: "lodestone-cleansing",
    stepOrder: 1,
    title: "Hold Lodestones",
    content: "Hold two matched pairs of lodestones (four total) in your hands.",
  },
  {
    id: "lodestone-cleansing-step-2",
    ritualId: "lodestone-cleansing",
    stepOrder: 2,
    title: "Absorb Negativity",
    content: "Slowly move through the area in a sunwise direction, encouraging the lodestones to absorb all negativity.",
  },
  {
    id: "lodestone-cleansing-step-3",
    ritualId: "lodestone-cleansing",
    stepOrder: 3,
    title: "Cleanse Lodestones",
    content: "Cleanse the lodestones intensively or bury them in the earth afterward.",
  },
  {
    id: "mother-holles-cleansing-step-1",
    ritualId: "mother-holles-cleansing",
    stepOrder: 1,
    title: "Grind Herbs",
    content: "Grind chamomile, elder, mint, mugwort, yarrow, and other herbs into a powder.",
  },
  {
    id: "mother-holles-cleansing-step-2",
    ritualId: "mother-holles-cleansing",
    stepOrder: 2,
    title: "Burn",
    content: "Burn the powder and waft the smoke into all corners and crevices of the home.",
  },
  {
    id: "salt-cleansing-spell-step-1",
    ritualId: "salt-cleansing-spell",
    stepOrder: 1,
    title: "Infuse",
    content: "Make an infusion by pouring boiling water over High John the Conqueror roots.",
  },
  {
    id: "salt-cleansing-spell-step-2",
    ritualId: "salt-cleansing-spell",
    stepOrder: 2,
    title: "Moisten Salt",
    content: "Sprinkle the infusion lightly on salt to moisten it, and let it dry out.",
  },
  {
    id: "salt-cleansing-spell-step-3",
    ritualId: "salt-cleansing-spell",
    stepOrder: 3,
    title: "Scatter",
    content: "Sprinkle the salt around your home to absorb negativity.",
  },
  {
    id: "florida-water-stationary-step-1",
    ritualId: "florida-water-stationary",
    stepOrder: 1,
    title: "Prepare Pan",
    content: "Fill a pan with equal parts Florida Water and Holy Water. Add one camphor square.",
  },
  {
    id: "florida-water-stationary-step-2",
    ritualId: "florida-water-stationary",
    stepOrder: 2,
    title: "Position",
    content: "Keep the pan under the bed or in a strategic location to absorb negativity.",
  },
  {
    id: "florida-water-stationary-step-3",
    ritualId: "florida-water-stationary",
    stepOrder: 3,
    title: "Replace",
    content: "Change the water once a week or if it starts to smell off.",
  },
  {
    id: "onion-space-cleansing-step-1",
    ritualId: "onion-space-cleansing",
    stepOrder: 1,
    title: "Chop Onion",
    content: "Chop one unpeeled onion into quarters by hand.",
  },
  {
    id: "onion-space-cleansing-step-2",
    ritualId: "onion-space-cleansing",
    stepOrder: 2,
    title: "Place",
    content: "Place one piece in each corner of a room overnight.",
  },
  {
    id: "onion-space-cleansing-step-3",
    ritualId: "onion-space-cleansing",
    stepOrder: 3,
    title: "Bury",
    content: "Bury them outside the following day. Repeat for five consecutive nights.",
  },
  {
    id: "rice-cleansing-spell-step-1",
    ritualId: "rice-cleansing-spell",
    stepOrder: 1,
    title: "Place Rice",
    content: "Place an uncovered bowl of raw white rice out to absorb negative energy.",
  },
  {
    id: "rice-cleansing-spell-step-2",
    ritualId: "rice-cleansing-spell",
    stepOrder: 2,
    title: "Discard",
    content: "Replace with fresh rice weekly, discarding the old rice outside the house.",
  },
  {
    id: "vinegar-cleanser-step-1",
    ritualId: "vinegar-cleanser",
    stepOrder: 1,
    title: "Place Vinegar",
    content: "Place plain vinegar in shallow uncovered pans throughout an area.",
  },
  {
    id: "vinegar-cleanser-step-2",
    ritualId: "vinegar-cleanser",
    stepOrder: 2,
    title: "Replace",
    content: "Replace weekly or when the liquid looks odd to maintain the absorbent cleansing effect.",
  },
  {
    id: "desert-sage-bath-step-1",
    ritualId: "desert-sage-bath",
    stepOrder: 1,
    title: "Infuse",
    content: "Make an infusion of desert sage.",
  },
  {
    id: "desert-sage-bath-step-2",
    ritualId: "desert-sage-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Add it to your bath to cleanse and purify yourself.",
  },
  {
    id: "earth-smoke-bath-step-1",
    ritualId: "earth-smoke-bath",
    stepOrder: 1,
    title: "Infuse",
    content: "Make a strong infusion by pouring boiling water over Earth Smoke (Fumitory).",
  },
  {
    id: "earth-smoke-bath-step-2",
    ritualId: "earth-smoke-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Strain and add the liquid to your bath.",
  },
  {
    id: "florida-water-personal-cleanser-step-1",
    ritualId: "florida-water-personal-cleanser",
    stepOrder: 1,
    title: "Apply",
    content: "Undress completely and rub or sprinkle Florida Water all over yourself, including the soles of the feet and top of the head.",
  },
  {
    id: "florida-water-personal-cleanser-step-2",
    ritualId: "florida-water-personal-cleanser",
    stepOrder: 2,
    title: "Dry",
    content: "Allow yourself to air-dry before getting dressed.",
  },
  {
    id: "indigo-cleansing-bath-step-1",
    ritualId: "indigo-cleansing-bath",
    stepOrder: 1,
    title: "Prepare Indigo Water",
    content: "Place Turkish blue eye beads into a bottle of Indigo Water to boost power.",
  },
  {
    id: "indigo-cleansing-bath-step-2",
    ritualId: "indigo-cleansing-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Strain the Indigo Water into your bathwater and soak.",
  },
  {
    id: "lavender-bath-step-1",
    ritualId: "lavender-bath",
    stepOrder: 1,
    title: "Add Lavender",
    content: "Add essential oil of lavender, lavender hydrosol, or an infusion to the bath.",
  },
  {
    id: "lavender-bath-step-2",
    ritualId: "lavender-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Soak in the water for spiritual and physical cleansing.",
  },
  {
    id: "lovage-bath-step-1",
    ritualId: "lovage-bath",
    stepOrder: 1,
    title: "Grind Root",
    content: "Grind and powder a dried lovage root.",
  },
  {
    id: "lovage-bath-step-2",
    ritualId: "lovage-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Sprinkle the powder onto your bathwater, distribute well, and soak.",
  },
  {
    id: "mandrake-bath-step-1",
    ritualId: "mandrake-bath",
    stepOrder: 1,
    title: "Soak Mandrake",
    content: "Soak a true mandrake root in warm water overnight or for three days. Remove the root.",
  },
  {
    id: "mandrake-bath-step-2",
    ritualId: "mandrake-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Add the soaking liquid to a tub filled with water and bathe.",
  },
  {
    id: "mate-cleansing-bath-step-1",
    ritualId: "mate-cleansing-bath",
    stepOrder: 1,
    title: "Infuse Tea",
    content: "Create a strong infusion by pouring boiling water over dried maté tea.",
  },
  {
    id: "mate-cleansing-bath-step-2",
    ritualId: "mate-cleansing-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Strain the cooled liquid and add it to your bath, or sponge it over yourself. Air dry.",
  },
  {
    id: "oak-leaf-bath-step-1",
    ritualId: "oak-leaf-bath",
    stepOrder: 1,
    title: "Prepare Faucet Bag",
    content: "Crumble five oak leaves into a muslin bag and attach it to the tub\'s faucet so water runs through it.",
  },
  {
    id: "oak-leaf-bath-step-2",
    ritualId: "oak-leaf-bath",
    stepOrder: 2,
    title: "Float Leaves",
    content: "Float five whole oak leaves in the bath water.",
  },
  {
    id: "oak-leaf-bath-step-3",
    ritualId: "oak-leaf-bath",
    stepOrder: 3,
    title: "Bathe",
    content: "Enter the bath and rub your body with the floating leaves.",
  },
  {
    id: "parsley-bath-step-1",
    ritualId: "parsley-bath",
    stepOrder: 1,
    title: "Infuse",
    content: "Make an infusion by pouring boiling water over an entire bunch of parsley and one sliced parsley root.",
  },
  {
    id: "parsley-bath-step-2",
    ritualId: "parsley-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Add the infusion to bathwater and soak.",
  },
  {
    id: "pine-bay-bath-step-1",
    ritualId: "pine-bay-bath",
    stepOrder: 1,
    title: "Infuse",
    content: "Make a strong infusion by pouring boiling water over combined pine needles and bay leaves.",
  },
  {
    id: "pine-bay-bath-step-2",
    ritualId: "pine-bay-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Add the strained water to your bath, together with a splash of vinegar and slices of lemon.",
  },
  {
    id: "yucca-bath-step-1",
    ritualId: "yucca-bath",
    stepOrder: 1,
    title: "Pound Roots",
    content: "Pound dry yucca roots.",
  },
  {
    id: "yucca-bath-step-2",
    ritualId: "yucca-bath",
    stepOrder: 2,
    title: "Make Suds",
    content: "Whisk them into cold water to create suds.",
  },
  {
    id: "yucca-bath-step-3",
    ritualId: "yucca-bath",
    stepOrder: 3,
    title: "Cleanse",
    content: "Use to cleanse yourself, especially your head and hair.",
  },
  {
    id: "sacred-cleansing-incense-step-1",
    ritualId: "sacred-cleansing-incense",
    stepOrder: 1,
    title: "Blend",
    content: "Blend benzoin, dragon\'s blood, and sandalwood.",
  },
  {
    id: "sacred-cleansing-incense-step-2",
    ritualId: "sacred-cleansing-incense",
    stepOrder: 2,
    title: "Fumigate",
    content: "Burn the blend on hot charcoals and pass yourself through the smoke.",
  },
  {
    id: "purification-bath-step-1",
    ritualId: "purification-bath",
    stepOrder: 1,
    title: "Infuse",
    content: "Make a strong infusion by pouring boiling water over nine bay laurel leaves and two tablespoons of anise seeds.",
  },
  {
    id: "purification-bath-step-2",
    ritualId: "purification-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Let it cool, strain out the botanicals, and add the liquid to your tub of water.",
  },
  {
    id: "quick-fix-aura-cleanser-step-1",
    ritualId: "quick-fix-aura-cleanser",
    stepOrder: 1,
    title: "Prepare Bath",
    content: "Add one cup of salt and one cup of vinegar (lemon, apple cider, or rice) to a bath.",
  },
  {
    id: "quick-fix-aura-cleanser-step-2",
    ritualId: "quick-fix-aura-cleanser",
    stepOrder: 2,
    title: "Bathe",
    content: "Soak in the water to remove psychic debris quickly.",
  },
  {
    id: "sage-cleansing-spell-step-1",
    ritualId: "sage-cleansing-spell",
    stepOrder: 1,
    title: "Powder",
    content: "Dry garden sage and grind it into a fine powder with a mortar and pestle.",
  },
  {
    id: "sage-cleansing-spell-step-2",
    ritualId: "sage-cleansing-spell",
    stepOrder: 2,
    title: "Fumigate",
    content: "Sprinkle the powder onto a charcoal and use it to fumigate the body.",
  },
  {
    id: "salt-cleansing-bath-step-1",
    ritualId: "salt-cleansing-bath",
    stepOrder: 1,
    title: "Blend Salts",
    content: "Blend two cups of sea salt with one-half cup of baking soda.",
  },
  {
    id: "salt-cleansing-bath-step-2",
    ritualId: "salt-cleansing-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Add the mixture to the bath to simultaneously provide spiritual cleansing and create a psychic shield.",
  },
  {
    id: "seven-roses-bath-step-1",
    ritualId: "seven-roses-bath",
    stepOrder: 1,
    title: "Prepare Tub",
    content: "Fill the tub with water and throw in seven red roses, a handful of sea salt, a splash of vinegar, and a squeeze of lemon juice.",
  },
  {
    id: "seven-roses-bath-step-2",
    ritualId: "seven-roses-bath",
    stepOrder: 2,
    title: "Bathe",
    content: "Spend exactly seven minutes in the bath, rubbing yourself with the roses and submerging periodically.",
  },
  {
    id: "seven-roses-bath-step-3",
    ritualId: "seven-roses-bath",
    stepOrder: 3,
    title: "Dry",
    content: "Dry off with a clean towel and leave the tub uncleaned for at least an hour while your aura stabilizes.",
  },
];

export const RITUAL_MATERIAL_SEEDS = [
  { ritualId: "egg-personal-cleansing", materialId: "egg", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "destroy-all-evil-bath", materialId: "florida-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "destroy-all-evil-bath", materialId: "sea-salt", quantityLabel: null, sortOrder: 2 },
  { ritualId: "destroy-all-evil-bath", materialId: "four-thieves-vinegar", quantityLabel: null, sortOrder: 3 },
  { ritualId: "destroy-all-evil-bath", materialId: "rosemary-essential-oil", quantityLabel: null, sortOrder: 4 },
  { ritualId: "ocean-water-asperging", materialId: "ocean-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "ocean-water-asperging", materialId: "frankincense", quantityLabel: null, sortOrder: 2 },
  { ritualId: "pine-asperging-spell", materialId: "pine-needles", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "yarrow-juniper-cleanser", materialId: "juniper-hydrosol", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "yarrow-juniper-cleanser", materialId: "yarrow-hydrosol", quantityLabel: null, sortOrder: 2 },
  { ritualId: "yarrow-juniper-cleanser", materialId: "dried-juniper-berries", quantityLabel: null, sortOrder: 3 },
  { ritualId: "broom-cleansing-spell", materialId: "broom", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "coconut-candle-cleanser", materialId: "coconut-candle", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "exorcism-powder", materialId: "dried-basil", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "exorcism-powder", materialId: "frankincense", quantityLabel: null, sortOrder: 2 },
  { ritualId: "exorcism-powder", materialId: "rosemary", quantityLabel: null, sortOrder: 3 },
  { ritualId: "exorcism-powder", materialId: "rue", quantityLabel: null, sortOrder: 4 },
  { ritualId: "exorcism-powder", materialId: "yarrow", quantityLabel: null, sortOrder: 5 },
  { ritualId: "exorcism-powder", materialId: "arrowroot-powder", quantityLabel: null, sortOrder: 6 },
  { ritualId: "basic-botanic-fumigation", materialId: "frankincense", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "basic-botanic-fumigation", materialId: "myrrh", quantityLabel: null, sortOrder: 2 },
  { ritualId: "basic-botanic-fumigation", materialId: "glowing-coals", quantityLabel: null, sortOrder: 3 },
  { ritualId: "betony-cleansing-incense", materialId: "dried-betony", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "betony-cleansing-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 2 },
  { ritualId: "birch-cleansing-incense", materialId: "birch-bark-twigs", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "birch-cleansing-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 2 },
  { ritualId: "cast-out-evil-incense", materialId: "camphor", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "cast-out-evil-incense", materialId: "cinnamon", quantityLabel: null, sortOrder: 2 },
  { ritualId: "cast-out-evil-incense", materialId: "frankincense", quantityLabel: null, sortOrder: 3 },
  { ritualId: "cast-out-evil-incense", materialId: "myrrh", quantityLabel: null, sortOrder: 4 },
  { ritualId: "cast-out-evil-incense", materialId: "sandalwood", quantityLabel: null, sortOrder: 5 },
  { ritualId: "cast-out-evil-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 6 },
  { ritualId: "dragons-blood-cleansing-incense", materialId: "dragons-blood-resin", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "dragons-blood-cleansing-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 2 },
  { ritualId: "garlic-cleansing-spell", materialId: "garlic-peel", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "garlic-cleansing-spell", materialId: "brown-sugar", quantityLabel: null, sortOrder: 2 },
  { ritualId: "garlic-cleansing-spell", materialId: "glowing-coals", quantityLabel: null, sortOrder: 3 },
  { ritualId: "liquidambar-cleansing-incense", materialId: "frankincense", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "liquidambar-cleansing-incense", materialId: "liquidambar", quantityLabel: null, sortOrder: 2 },
  { ritualId: "liquidambar-cleansing-incense", materialId: "mastic", quantityLabel: null, sortOrder: 3 },
  { ritualId: "liquidambar-cleansing-incense", materialId: "sandalwood", quantityLabel: null, sortOrder: 4 },
  { ritualId: "liquidambar-cleansing-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 5 },
  { ritualId: "sacred-purification-incense", materialId: "yucca-root", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "sacred-purification-incense", materialId: "dragons-blood-resin", quantityLabel: null, sortOrder: 2 },
  { ritualId: "sacred-purification-incense", materialId: "frankincense", quantityLabel: null, sortOrder: 3 },
  { ritualId: "sacred-purification-incense", materialId: "myrrh", quantityLabel: null, sortOrder: 4 },
  { ritualId: "sacred-purification-incense", materialId: "sandalwood", quantityLabel: null, sortOrder: 5 },
  { ritualId: "sacred-purification-incense", materialId: "sea-salt", quantityLabel: null, sortOrder: 6 },
  { ritualId: "sacred-purification-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 7 },
  { ritualId: "cleansed-by-the-bell", materialId: "silver-bell", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "singing-bowls-cleansing", materialId: "singing-bowl", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "chinese-vinegar-steam-cleanser", materialId: "rice-vinegar", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "glittering-coals-vapor-cleanser", materialId: "glowing-coals", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "aura-cleansing-floorwash", materialId: "dried-agrimony", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "aura-cleansing-floorwash", materialId: "peppermint", quantityLabel: null, sortOrder: 2 },
  { ritualId: "aura-cleansing-floorwash", materialId: "white-vinegar", quantityLabel: null, sortOrder: 3 },
  { ritualId: "dragons-tears-floorwash", materialId: "dragons-tears", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "dragons-tears-floorwash", materialId: "white-vinegar", quantityLabel: null, sortOrder: 2 },
  { ritualId: "ocean-floorwash", materialId: "ocean-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "ocean-floorwash", materialId: "cascarilla-powder", quantityLabel: null, sortOrder: 2 },
  { ritualId: "ocean-floorwash", materialId: "kelp-powder", quantityLabel: null, sortOrder: 3 },
  { ritualId: "coconut-house-cleansing", materialId: "rum", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "coconut-house-cleansing", materialId: "cascarilla-powder", quantityLabel: null, sortOrder: 2 },
  { ritualId: "coconut-house-cleansing", materialId: "whole-coconut", quantityLabel: null, sortOrder: 3 },
  { ritualId: "jessamine-flowers-cleansing", materialId: "jessamine-petals", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "lodestone-cleansing", materialId: "lodestones", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "mother-holles-cleansing", materialId: "chamomile", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "mother-holles-cleansing", materialId: "elder", quantityLabel: null, sortOrder: 2 },
  { ritualId: "mother-holles-cleansing", materialId: "mint", quantityLabel: null, sortOrder: 3 },
  { ritualId: "mother-holles-cleansing", materialId: "mugwort", quantityLabel: null, sortOrder: 4 },
  { ritualId: "mother-holles-cleansing", materialId: "yarrow", quantityLabel: null, sortOrder: 5 },
  { ritualId: "salt-cleansing-spell", materialId: "high-john-root", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "salt-cleansing-spell", materialId: "sea-salt", quantityLabel: null, sortOrder: 2 },
  { ritualId: "florida-water-stationary", materialId: "florida-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "florida-water-stationary", materialId: "camphor", quantityLabel: null, sortOrder: 2 },
  { ritualId: "onion-space-cleansing", materialId: "white-onion", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "rice-cleansing-spell", materialId: "raw-white-rice", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "vinegar-cleanser", materialId: "white-vinegar", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "desert-sage-bath", materialId: "desert-sage", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "earth-smoke-bath", materialId: "fumitory", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "florida-water-personal-cleanser", materialId: "florida-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "indigo-cleansing-bath", materialId: "indigo-water", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "indigo-cleansing-bath", materialId: "blue-eye-beads", quantityLabel: null, sortOrder: 2 },
  { ritualId: "lavender-bath", materialId: "lavender-essential-oil", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "lovage-bath", materialId: "lovage-root", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "mandrake-bath", materialId: "mandrake-root", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "mate-cleansing-bath", materialId: "mate-tea", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "oak-leaf-bath", materialId: "oak-leaves", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "parsley-bath", materialId: "parsley", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "pine-bay-bath", materialId: "pine-needles", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "pine-bay-bath", materialId: "bay-leaves", quantityLabel: null, sortOrder: 2 },
  { ritualId: "pine-bay-bath", materialId: "white-vinegar", quantityLabel: null, sortOrder: 3 },
  { ritualId: "yucca-bath", materialId: "yucca-root", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "sacred-cleansing-incense", materialId: "benzoin", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "sacred-cleansing-incense", materialId: "dragons-blood-resin", quantityLabel: null, sortOrder: 2 },
  { ritualId: "sacred-cleansing-incense", materialId: "sandalwood", quantityLabel: null, sortOrder: 3 },
  { ritualId: "sacred-cleansing-incense", materialId: "glowing-coals", quantityLabel: null, sortOrder: 4 },
  { ritualId: "purification-bath", materialId: "bay-leaves", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "purification-bath", materialId: "anise-seeds", quantityLabel: null, sortOrder: 2 },
  { ritualId: "quick-fix-aura-cleanser", materialId: "sea-salt", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "quick-fix-aura-cleanser", materialId: "white-vinegar", quantityLabel: null, sortOrder: 2 },
  { ritualId: "sage-cleansing-spell", materialId: "glowing-coals", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "salt-cleansing-bath", materialId: "sea-salt", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "salt-cleansing-bath", materialId: "baking-soda", quantityLabel: null, sortOrder: 2 },
  { ritualId: "seven-roses-bath", materialId: "red-roses", quantityLabel: "1x", sortOrder: 1 },
  { ritualId: "seven-roses-bath", materialId: "sea-salt", quantityLabel: null, sortOrder: 2 },
  { ritualId: "seven-roses-bath", materialId: "white-vinegar", quantityLabel: null, sortOrder: 3 },
  { ritualId: "seven-roses-bath", materialId: "lemon-juice", quantityLabel: null, sortOrder: 4 },
];

export const ENTITY_LINK_SEEDS = [
  {
    id: "link-exorcism-powder-rosemary",
    sourceEntityType: "ritual",
    sourceEntityId: "exorcism-powder",
    targetEntityType: "library_entry",
    targetEntityId: "rosemary",
    relationType: "uses",
  },
  {
    id: "link-cast-out-evil-incense-cinnamon",
    sourceEntityType: "ritual",
    sourceEntityId: "cast-out-evil-incense",
    targetEntityType: "library_entry",
    targetEntityId: "cinnamon",
    relationType: "uses",
  },
  {
    id: "link-mother-holles-cleansing-elder",
    sourceEntityType: "ritual",
    sourceEntityId: "mother-holles-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "elder",
    relationType: "uses",
  },
  {
    id: "link-sacred-cleansing-incense-benzoin",
    sourceEntityType: "ritual",
    sourceEntityId: "sacred-cleansing-incense",
    targetEntityType: "library_entry",
    targetEntityId: "benzoin",
    relationType: "uses",
  },
  // egg
  {
    id: "link-egg-personal-cleansing-egg",
    sourceEntityType: "ritual",
    sourceEntityId: "egg-personal-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "egg",
    relationType: "uses",
  },
  // florida-water
  {
    id: "link-destroy-all-evil-bath-florida-water",
    sourceEntityType: "ritual",
    sourceEntityId: "destroy-all-evil-bath",
    targetEntityType: "library_entry",
    targetEntityId: "florida-water",
    relationType: "uses",
  },
  {
    id: "link-florida-water-stationary-florida-water",
    sourceEntityType: "ritual",
    sourceEntityId: "florida-water-stationary",
    targetEntityType: "library_entry",
    targetEntityId: "florida-water",
    relationType: "uses",
  },
  {
    id: "link-florida-water-personal-cleanser-florida-water",
    sourceEntityType: "ritual",
    sourceEntityId: "florida-water-personal-cleanser",
    targetEntityType: "library_entry",
    targetEntityId: "florida-water",
    relationType: "uses",
  },
  // sea-salt
  {
    id: "link-destroy-all-evil-bath-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "destroy-all-evil-bath",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  {
    id: "link-sacred-purification-incense-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "sacred-purification-incense",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  {
    id: "link-salt-cleansing-spell-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "salt-cleansing-spell",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  {
    id: "link-quick-fix-aura-cleanser-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "quick-fix-aura-cleanser",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  {
    id: "link-salt-cleansing-bath-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "salt-cleansing-bath",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  {
    id: "link-seven-roses-bath-sea-salt",
    sourceEntityType: "ritual",
    sourceEntityId: "seven-roses-bath",
    targetEntityType: "library_entry",
    targetEntityId: "sea-salt",
    relationType: "uses",
  },
  // ocean-water
  {
    id: "link-ocean-water-asperging-ocean-water",
    sourceEntityType: "ritual",
    sourceEntityId: "ocean-water-asperging",
    targetEntityType: "library_entry",
    targetEntityId: "ocean-water",
    relationType: "uses",
  },
  {
    id: "link-ocean-floorwash-ocean-water",
    sourceEntityType: "ritual",
    sourceEntityId: "ocean-floorwash",
    targetEntityType: "library_entry",
    targetEntityId: "ocean-water",
    relationType: "uses",
  },
  // broom-besom
  {
    id: "link-broom-cleansing-spell-broom-besom",
    sourceEntityType: "ritual",
    sourceEntityId: "broom-cleansing-spell",
    targetEntityType: "library_entry",
    targetEntityId: "broom-besom",
    relationType: "uses",
  },
  // basil
  {
    id: "link-exorcism-powder-basil",
    sourceEntityType: "ritual",
    sourceEntityId: "exorcism-powder",
    targetEntityType: "library_entry",
    targetEntityId: "basil",
    relationType: "uses",
  },
  // wood-betony
  {
    id: "link-betony-cleansing-incense-wood-betony",
    sourceEntityType: "ritual",
    sourceEntityId: "betony-cleansing-incense",
    targetEntityType: "library_entry",
    targetEntityId: "wood-betony",
    relationType: "uses",
  },
  // birch
  {
    id: "link-birch-cleansing-incense-birch",
    sourceEntityType: "ritual",
    sourceEntityId: "birch-cleansing-incense",
    targetEntityType: "library_entry",
    targetEntityId: "birch",
    relationType: "uses",
  },
  // camphor
  {
    id: "link-cast-out-evil-incense-camphor",
    sourceEntityType: "ritual",
    sourceEntityId: "cast-out-evil-incense",
    targetEntityType: "library_entry",
    targetEntityId: "camphor",
    relationType: "uses",
  },
  {
    id: "link-florida-water-stationary-camphor",
    sourceEntityType: "ritual",
    sourceEntityId: "florida-water-stationary",
    targetEntityType: "library_entry",
    targetEntityId: "camphor",
    relationType: "uses",
  },
  // dragons-blood
  {
    id: "link-dragons-blood-cleansing-incense-dragons-blood",
    sourceEntityType: "ritual",
    sourceEntityId: "dragons-blood-cleansing-incense",
    targetEntityType: "library_entry",
    targetEntityId: "dragons-blood",
    relationType: "uses",
  },
  {
    id: "link-sacred-purification-incense-dragons-blood",
    sourceEntityType: "ritual",
    sourceEntityId: "sacred-purification-incense",
    targetEntityType: "library_entry",
    targetEntityId: "dragons-blood",
    relationType: "uses",
  },
  {
    id: "link-sacred-cleansing-incense-dragons-blood",
    sourceEntityType: "ritual",
    sourceEntityId: "sacred-cleansing-incense",
    targetEntityType: "library_entry",
    targetEntityId: "dragons-blood",
    relationType: "uses",
  },
  // singing-bowl
  {
    id: "link-singing-bowls-cleansing-singing-bowl",
    sourceEntityType: "ritual",
    sourceEntityId: "singing-bowls-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "singing-bowl",
    relationType: "uses",
  },
  // agrimony
  {
    id: "link-aura-cleansing-floorwash-agrimony",
    sourceEntityType: "ritual",
    sourceEntityId: "aura-cleansing-floorwash",
    targetEntityType: "library_entry",
    targetEntityId: "agrimony",
    relationType: "uses",
  },
  // cascarilla-powder
  {
    id: "link-ocean-floorwash-cascarilla-powder",
    sourceEntityType: "ritual",
    sourceEntityId: "ocean-floorwash",
    targetEntityType: "library_entry",
    targetEntityId: "cascarilla-powder",
    relationType: "uses",
  },
  {
    id: "link-coconut-house-cleansing-cascarilla-powder",
    sourceEntityType: "ritual",
    sourceEntityId: "coconut-house-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "cascarilla-powder",
    relationType: "uses",
  },
  // lodestone
  {
    id: "link-lodestone-cleansing-lodestone",
    sourceEntityType: "ritual",
    sourceEntityId: "lodestone-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "lodestone",
    relationType: "uses",
  },
  // roman-chamomile
  {
    id: "link-mother-holles-cleansing-roman-chamomile",
    sourceEntityType: "ritual",
    sourceEntityId: "mother-holles-cleansing",
    targetEntityType: "library_entry",
    targetEntityId: "roman-chamomile",
    relationType: "uses",
  },
  // sage
  {
    id: "link-desert-sage-bath-sage",
    sourceEntityType: "ritual",
    sourceEntityId: "desert-sage-bath",
    targetEntityType: "library_entry",
    targetEntityId: "sage",
    relationType: "uses",
  },
  // indigo-water
  {
    id: "link-indigo-cleansing-bath-indigo-water",
    sourceEntityType: "ritual",
    sourceEntityId: "indigo-cleansing-bath",
    targetEntityType: "library_entry",
    targetEntityId: "indigo-water",
    relationType: "uses",
  },
  // lavender
  {
    id: "link-lavender-bath-lavender",
    sourceEntityType: "ritual",
    sourceEntityId: "lavender-bath",
    targetEntityType: "library_entry",
    targetEntityId: "lavender",
    relationType: "uses",
  },
  // bay
  {
    id: "link-pine-bay-bath-bay",
    sourceEntityType: "ritual",
    sourceEntityId: "pine-bay-bath",
    targetEntityType: "library_entry",
    targetEntityId: "bay",
    relationType: "uses",
  },
  {
    id: "link-purification-bath-bay",
    sourceEntityType: "ritual",
    sourceEntityId: "purification-bath",
    targetEntityType: "library_entry",
    targetEntityId: "bay",
    relationType: "uses",
  },
  // anise
  {
    id: "link-purification-bath-anise",
    sourceEntityType: "ritual",
    sourceEntityId: "purification-bath",
    targetEntityType: "library_entry",
    targetEntityId: "anise",
    relationType: "uses",
  },
];
