type TarotCardSeed = {
  id: string;
  name: string;
  arcana: "major" | "minor";
  suit: string | null;
  rank: number;
  uprightMeaning: string;
  reversedMeaning: string;
  keywords: string;
  description: string;
};

const MAJOR_ARCANA: TarotCardSeed[] = [
  {
    id: "major-0",
    name: "The Fool",
    arcana: "major",
    suit: null,
    rank: 0,
    uprightMeaning: "A leap of faith into the unknown. Trust the journey even without a map — innocence and spontaneity open doors that caution keeps shut.",
    reversedMeaning: "Recklessness disguised as courage. Ignoring obvious warnings or refusing to learn from past mistakes leads to avoidable falls.",
    keywords: "beginnings, innocence, spontaneity, leap of faith",
    description: "A carefree figure stands at the edge of a cliff, gazing upward with a white rose in hand and a small dog at their heels.",
  },
  {
    id: "major-1",
    name: "The Magician",
    arcana: "major",
    suit: null,
    rank: 1,
    uprightMeaning: "You have every tool you need. Channel willpower and focused intention to manifest real change — the elements are already on your table.",
    reversedMeaning: "Scattered energy or manipulation. Talents are being wasted on illusions rather than genuine creation.",
    keywords: "willpower, manifestation, skill, resourcefulness",
    description: "A figure stands before a table bearing a cup, pentacle, sword, and wand, one hand raised to the sky and the other pointing to earth.",
  },
  {
    id: "major-2",
    name: "The High Priestess",
    arcana: "major",
    suit: null,
    rank: 2,
    uprightMeaning: "Trust your inner knowing. The answers you seek are already within — be still, listen to your intuition, and honor what lies beneath the surface.",
    reversedMeaning: "Disconnection from intuition. Secrets kept too long become burdens; ignoring inner wisdom creates confusion.",
    keywords: "intuition, mystery, inner wisdom, subconscious",
    description: "A serene figure sits between two pillars, a crescent moon at her feet and a scroll of hidden knowledge in her lap.",
  },
  {
    id: "major-3",
    name: "The Empress",
    arcana: "major",
    suit: null,
    rank: 3,
    uprightMeaning: "Abundance flows when you nurture what matters. Creativity, fertility, and sensual pleasure remind you that growth comes from care and presence.",
    reversedMeaning: "Neglecting self-care or creative stagnation. Over-dependence on others or smothering love blocks natural growth.",
    keywords: "abundance, nurturing, fertility, creativity",
    description: "A crowned figure reclines in a lush garden surrounded by grain, flowing water, and a heart-shaped shield bearing the Venus symbol.",
  },
  {
    id: "major-4",
    name: "The Emperor",
    arcana: "major",
    suit: null,
    rank: 4,
    uprightMeaning: "Structure and authority bring stability. Lead with confidence, set clear boundaries, and build something lasting through disciplined action.",
    reversedMeaning: "Rigidity or abuse of power. Excessive control stifles growth; stubbornness masquerades as strength.",
    keywords: "authority, structure, stability, leadership",
    description: "An armored figure sits on a stone throne decorated with ram heads, holding an ankh scepter and an orb of dominion.",
  },
  {
    id: "major-5",
    name: "The Hierophant",
    arcana: "major",
    suit: null,
    rank: 5,
    uprightMeaning: "Seek guidance from tradition and trusted mentors. Spiritual teachings and shared beliefs offer a foundation for your path forward.",
    reversedMeaning: "Blind conformity or rejection of all structure. Questioning dogma is healthy, but rebellion without purpose leads nowhere.",
    keywords: "tradition, spiritual guidance, conformity, mentorship",
    description: "A robed figure sits between two pillars, raising a hand in blessing while two acolytes kneel before a pair of crossed keys.",
  },
  {
    id: "major-6",
    name: "The Lovers",
    arcana: "major",
    suit: null,
    rank: 6,
    uprightMeaning: "A meaningful choice rooted in values and authentic connection. Alignment between head and heart creates union that transforms.",
    reversedMeaning: "Misalignment or avoidance of a necessary choice. Temptation, disharmony, or fear of commitment clouds the heart.",
    keywords: "love, harmony, choices, alignment",
    description: "Two figures stand beneath an angel's outstretched wings, a tree of flame behind one and a tree of fruit behind the other.",
  },
  {
    id: "major-7",
    name: "The Chariot",
    arcana: "major",
    suit: null,
    rank: 7,
    uprightMeaning: "Victory through determination. Harness opposing forces with willpower and move forward — confidence and control carry you past obstacles.",
    reversedMeaning: "Loss of direction or inner conflict pulling you apart. Aggression without aim wastes momentum.",
    keywords: "determination, triumph, willpower, control",
    description: "A warrior stands in a chariot drawn by a black and a white sphinx, a canopy of stars overhead and a city behind.",
  },
  {
    id: "major-8",
    name: "Strength",
    arcana: "major",
    suit: null,
    rank: 8,
    uprightMeaning: "True power is gentle. Courage, patience, and compassion tame what brute force cannot — meet challenges with quiet confidence.",
    reversedMeaning: "Self-doubt or raw emotion overwhelming reason. Inner turmoil left unaddressed drains your reserves.",
    keywords: "courage, patience, compassion, inner strength",
    description: "A figure gently closes the jaws of a lion, an infinity symbol hovering above, surrounded by a garland of flowers.",
  },
  {
    id: "major-9",
    name: "The Hermit",
    arcana: "major",
    suit: null,
    rank: 9,
    uprightMeaning: "Withdraw to find clarity. Solitude and introspection illuminate truths that noise obscures — your inner lantern lights the way.",
    reversedMeaning: "Isolation turning into loneliness. Withdrawing too far from others or refusing guidance keeps you stuck in the dark.",
    keywords: "solitude, introspection, wisdom, guidance",
    description: "A cloaked figure stands on a mountain peak, holding a lantern containing a six-pointed star and leaning on a staff.",
  },
  {
    id: "major-10",
    name: "Wheel of Fortune",
    arcana: "major",
    suit: null,
    rank: 10,
    uprightMeaning: "Cycles are turning in your favor. Embrace change, trust timing, and know that fate and free will dance together.",
    reversedMeaning: "Resistance to inevitable change or a downturn in luck. Clinging to what was prevents what could be.",
    keywords: "cycles, destiny, turning point, luck",
    description: "A great wheel turns in the sky bearing mystical creatures at each corner, with a sphinx atop and a serpent descending.",
  },
  {
    id: "major-11",
    name: "Justice",
    arcana: "major",
    suit: null,
    rank: 11,
    uprightMeaning: "Truth and fairness prevail. Accept accountability, weigh decisions carefully, and trust that integrity brings balanced outcomes.",
    reversedMeaning: "Dishonesty or avoidance of consequences. Unfair treatment or refusal to see the truth distorts the scales.",
    keywords: "fairness, truth, accountability, balance",
    description: "A robed figure sits on a throne holding an upright sword in one hand and balanced scales in the other.",
  },
  {
    id: "major-12",
    name: "The Hanged Man",
    arcana: "major",
    suit: null,
    rank: 12,
    uprightMeaning: "Surrender brings perspective. Pause, release control, and let a new viewpoint emerge — sacrifice now creates wisdom later.",
    reversedMeaning: "Stalling or martyrdom without purpose. Refusing to let go keeps you suspended indefinitely.",
    keywords: "surrender, new perspective, pause, sacrifice",
    description: "A serene figure hangs upside-down from a living tree by one foot, a golden halo shining around the head.",
  },
  {
    id: "major-13",
    name: "Death",
    arcana: "major",
    suit: null,
    rank: 13,
    uprightMeaning: "Transformation is not an ending but a threshold. Release what has completed its cycle so renewal and rebirth can begin.",
    reversedMeaning: "Resistance to necessary endings. Fear of change traps you in patterns that have already expired.",
    keywords: "transformation, endings, rebirth, release",
    description: "An armored skeletal rider carries a black banner emblazoned with a white rose, as figures of all ages stand before the rising sun.",
  },
  {
    id: "major-14",
    name: "Temperance",
    arcana: "major",
    suit: null,
    rank: 14,
    uprightMeaning: "Balance and patience create alchemy. Blend opposing forces with moderation and purpose — the middle path leads to healing.",
    reversedMeaning: "Excess or imbalance. Rushing the process or losing your center disrupts the harmony you are trying to build.",
    keywords: "balance, moderation, patience, alchemy",
    description: "A winged angel stands with one foot on land and one in water, pouring liquid between two cups in an endless flow.",
  },
  {
    id: "major-15",
    name: "The Devil",
    arcana: "major",
    suit: null,
    rank: 15,
    uprightMeaning: "Examine what binds you. Shadow patterns, attachments, and illusions of powerlessness can be broken once you see them clearly.",
    reversedMeaning: "Breaking free from addiction or toxic patterns. The chains were always loose — liberation begins with awareness.",
    keywords: "shadow, bondage, attachment, illusion",
    description: "A horned figure perches above two chained humans whose bonds hang loosely, an inverted pentagram glowing behind.",
  },
  {
    id: "major-16",
    name: "The Tower",
    arcana: "major",
    suit: null,
    rank: 16,
    uprightMeaning: "Sudden upheaval clears false foundations. What crumbles was never built to last — truth emerges from the rubble.",
    reversedMeaning: "Avoiding inevitable collapse or internalizing the shock. Delayed reckoning only deepens the eventual fall.",
    keywords: "upheaval, revelation, sudden change, breakthrough",
    description: "Lightning strikes a tall tower, shattering its crown as two figures fall through the night sky amid flames and debris.",
  },
  {
    id: "major-17",
    name: "The Star",
    arcana: "major",
    suit: null,
    rank: 17,
    uprightMeaning: "Hope returns after the storm. Pour your faith into healing and renewal — the universe is replenishing what was lost.",
    reversedMeaning: "Loss of faith or disconnection from hope. Despair clouds vision, but the stars remain even when unseen.",
    keywords: "hope, renewal, inspiration, serenity",
    description: "A kneeling figure pours water onto land and into a pool beneath a sky of eight radiant stars.",
  },
  {
    id: "major-18",
    name: "The Moon",
    arcana: "major",
    suit: null,
    rank: 18,
    uprightMeaning: "Navigate the uncertain terrain of dreams and emotions. Illusions may confuse, but your intuition can find the path through the fog.",
    reversedMeaning: "Fears and anxieties surfacing for release. Clarity begins to return as the subconscious reveals its secrets.",
    keywords: "illusion, intuition, dreams, the subconscious",
    description: "A full moon gazes down on a winding path between two towers, a dog and wolf howling while a crayfish emerges from the water.",
  },
  {
    id: "major-19",
    name: "The Sun",
    arcana: "major",
    suit: null,
    rank: 19,
    uprightMeaning: "Joy, vitality, and success shine upon you. Celebrate openly, embrace optimism, and let your authentic self radiate outward.",
    reversedMeaning: "Temporary clouds over happiness. Inner child feels dimmed by self-doubt or external pressure, but the warmth is still there.",
    keywords: "joy, success, vitality, optimism",
    description: "A radiant sun shines over a joyful child riding a white horse, sunflowers blooming on a garden wall behind.",
  },
  {
    id: "major-20",
    name: "Judgement",
    arcana: "major",
    suit: null,
    rank: 20,
    uprightMeaning: "A call to rise and answer your higher purpose. Evaluate your journey honestly, forgive the past, and step into your true calling.",
    reversedMeaning: "Self-doubt blocking your awakening. Ignoring the inner call or harsh self-judgment prevents transformation.",
    keywords: "awakening, purpose, reflection, calling",
    description: "An angel sounds a trumpet above rising figures who emerge from coffins with arms outstretched toward the heavens.",
  },
  {
    id: "major-21",
    name: "The World",
    arcana: "major",
    suit: null,
    rank: 21,
    uprightMeaning: "Completion and wholeness. A cycle has fulfilled itself — celebrate integration, achievement, and the wisdom gained through the journey.",
    reversedMeaning: "Incomplete closure or fear of the next chapter. Almost there, but lingering attachments delay the final step.",
    keywords: "completion, wholeness, fulfillment, integration",
    description: "A dancing figure is encircled by a laurel wreath, holding twin wands, with the four fixed signs of the zodiac at each corner.",
  },
];

function minorCard(
  suit: string,
  rank: number,
  name: string,
  upright: string,
  reversed: string,
  keywords: string,
  description: string
): TarotCardSeed {
  return {
    id: `${suit}-${rank}`,
    name,
    arcana: "minor",
    suit,
    rank,
    uprightMeaning: upright,
    reversedMeaning: reversed,
    keywords,
    description,
  };
}

const WANDS: TarotCardSeed[] = [
  minorCard("wands", 1, "Ace of Wands",
    "A spark of creative inspiration and raw potential. Seize the moment — passion and new ventures call you forward.",
    "Delays, false starts, or creative blocks. The spark exists but the timing or direction needs refinement.",
    "inspiration, potential, new venture, passion",
    "A hand emerges from a cloud gripping a budding wand, leaves drifting in the breeze above a lush landscape."),
  minorCard("wands", 2, "Two of Wands",
    "Planning and vision expand your horizon. Step beyond comfort, explore your options, and commit to a bold direction.",
    "Fear of the unknown or poor planning. Hesitation at the threshold prevents progress.",
    "planning, vision, decisions, exploration",
    "A figure holds a globe and gazes from a castle battlement across the sea, a second wand mounted beside them."),
  minorCard("wands", 3, "Three of Wands",
    "Expansion and foresight pay off. Your ships are sailing — trust the momentum and prepare for what returns.",
    "Frustrating delays or lack of foresight. Opportunities stall when preparation was insufficient.",
    "expansion, foresight, momentum, progress",
    "A cloaked figure watches three merchant ships cross the horizon from a clifftop, three wands standing tall behind."),
  minorCard("wands", 4, "Four of Wands",
    "Celebration and harmony mark a milestone. Enjoy stability, community, and the warmth of what you have built together.",
    "Tension at home or incomplete celebrations. The foundation is present but appreciation is missing.",
    "celebration, harmony, homecoming, milestone",
    "Four wands form a canopy decorated with garlands and flowers as two joyful figures raise bouquets before a welcoming castle."),
  minorCard("wands", 5, "Five of Wands",
    "Healthy competition and creative friction. Diverse opinions clash, but the struggle sharpens your approach if you stay engaged.",
    "Avoidance of necessary conflict or pointless bickering. Energy is wasted on ego rather than resolution.",
    "competition, conflict, tension, growth through challenge",
    "Five figures brandish wands in a chaotic mock battle, each pushing in a different direction under an open sky."),
  minorCard("wands", 6, "Six of Wands",
    "Victory and public recognition reward your effort. Ride the wave of success with confidence and share the triumph.",
    "Ego inflation or hollow victory. External praise without inner satisfaction rings empty.",
    "victory, recognition, confidence, triumph",
    "A laurel-crowned rider holds a wand topped with a wreath, cheered by a crowd bearing five more wands."),
  minorCard("wands", 7, "Seven of Wands",
    "Stand your ground against challenge. Courage and conviction defend what you have built — do not yield to pressure.",
    "Feeling overwhelmed or giving in too easily. Defensiveness without strategy leads to burnout.",
    "courage, defense, perseverance, standing firm",
    "A determined figure on high ground fends off six wands rising from below, holding the advantage of position."),
  minorCard("wands", 8, "Eight of Wands",
    "Swift movement and rapid communication. Events accelerate — align yourself and ride the momentum with clear intention.",
    "Delays, miscommunication, or scattered energy. Rushing without direction creates chaos instead of speed.",
    "speed, momentum, swift action, communication",
    "Eight wands fly through a clear sky in parallel, angled toward the ground as if nearing their destination."),
  minorCard("wands", 9, "Nine of Wands",
    "Resilience after repeated trials. You are bruised but not broken — one last push is all that stands between you and completion.",
    "Chronic exhaustion or paranoid defensiveness. Guarding against threats that may no longer exist wastes your reserves.",
    "resilience, persistence, endurance, near completion",
    "A bandaged figure leans on a wand before a wall of eight others, watchful but weary, braced for one final challenge."),
  minorCard("wands", 10, "Ten of Wands",
    "Carrying too heavy a load. Responsibility has become burden — delegate, prioritize, or set down what is not truly yours.",
    "Learning to release unnecessary burdens. The weight lifts when you stop proving yourself through suffering.",
    "burden, responsibility, overwhelm, hard work",
    "A bent figure struggles to carry ten heavy wands toward a distant town, back straining under the excessive load."),
  minorCard("wands", 11, "Page of Wands",
    "Enthusiastic exploration of a new passion. Curiosity and a free spirit fuel discovery — say yes to the adventure.",
    "Lack of direction or restless energy without focus. Excitement without follow-through fizzles quickly.",
    "exploration, enthusiasm, curiosity, free spirit",
    "A youthful figure studies a tall wand with fascination, standing in a desert landscape ready for adventure."),
  minorCard("wands", 12, "Knight of Wands",
    "Bold, passionate action charges forward. Pursue your vision with daring energy and charisma — adventure rewards the courageous.",
    "Impulsiveness or reckless haste. Charging ahead without thinking scatters resources and burns bridges.",
    "action, adventure, daring, passion",
    "An armored knight on a rearing horse brandishes a wand, a cloak of flames trailing behind as pyramids rise in the distance."),
  minorCard("wands", 13, "Queen of Wands",
    "Confident, warm, and magnetically creative. Lead with passion and generosity — your enthusiasm uplifts everyone around you.",
    "Jealousy, self-doubt, or overbearing energy. Confidence turns to control when insecurity lurks beneath the surface.",
    "confidence, warmth, creativity, determination",
    "A radiant queen sits on a throne of lions and sunflowers, holding a wand in one hand and a black cat at her feet."),
  minorCard("wands", 14, "King of Wands",
    "Visionary leadership grounded in experience. Inspire others with bold direction, integrity, and the courage to take calculated risks.",
    "Tyrannical control or unfulfilled vision. Authority without empathy creates fear instead of loyalty.",
    "leadership, vision, entrepreneurship, honor",
    "A powerful king sits on a salamander-carved throne, a living wand in hand, gazing forward with commanding clarity."),
];

const CUPS: TarotCardSeed[] = [
  minorCard("cups", 1, "Ace of Cups",
    "An overflow of emotional and spiritual potential. Open your heart to love, compassion, and creative inspiration — new feelings emerge.",
    "Emotional blockage or repressed feelings. The cup is full but you are not allowing yourself to drink.",
    "love, new feelings, compassion, emotional opening",
    "A radiant hand extends a golden chalice overflowing with five streams of water, a dove descending with a communion wafer."),
  minorCard("cups", 2, "Two of Cups",
    "Mutual connection and partnership built on respect. Hearts meet in balance — honor the bond that reflects your deepest self.",
    "Imbalance in a relationship or broken trust. One side gives while the other takes, disrupting harmony.",
    "partnership, unity, mutual respect, connection",
    "Two figures exchange cups beneath a caduceus and a winged lion, pledging mutual devotion and balanced partnership."),
  minorCard("cups", 3, "Three of Cups",
    "Friendship, celebration, and communal joy. Gather with your circle, share abundance, and let gratitude amplify the moment.",
    "Overindulgence or social exclusion. The party continues but someone feels left out or the celebration masks avoidance.",
    "celebration, friendship, community, joy",
    "Three figures dance and raise their cups in a harvest celebration, flowers and fruit spilling around their feet."),
  minorCard("cups", 4, "Four of Cups",
    "Contemplation and emotional withdrawal. Reassess what truly fulfills you — apathy may be disguising a deeper longing for meaning.",
    "Emerging from apathy and recognizing new opportunities. A fresh perspective breaks the cycle of dissatisfaction.",
    "contemplation, apathy, reevaluation, discontent",
    "A figure sits beneath a tree with crossed arms, ignoring a cup offered by a mysterious hand while three cups sit before them."),
  minorCard("cups", 5, "Five of Cups",
    "Grief and regret over what has been lost. Allow yourself to mourn, but remember — two cups still stand behind you, untouched.",
    "Acceptance begins and healing follows. Turning around reveals what was saved, not just what was spilled.",
    "grief, loss, regret, partial loss",
    "A cloaked figure stares at three spilled cups while two upright cups remain behind, a bridge in the background leading home."),
  minorCard("cups", 6, "Six of Cups",
    "Nostalgia and innocent generosity bring warmth. Revisit the simplicity of the past and let kindness flow without condition.",
    "Clinging to the past or refusing to grow up. Sweet memories become chains when they prevent present engagement.",
    "nostalgia, innocence, generosity, childhood",
    "A young child offers a cup full of flowers to another in a quaint garden, five more cups arrayed with blooms nearby."),
  minorCard("cups", 7, "Seven of Cups",
    "A dazzling array of choices and fantasies. Discern what is real from what is illusion before you commit — not every vision is grounded.",
    "Clarity after confusion. Cutting through fantasy to find the one path that is actually attainable and meaningful.",
    "fantasy, choices, illusion, daydreaming",
    "A silhouetted figure gazes at seven cups floating in clouds, each holding a different vision — jewels, a dragon, a veiled figure."),
  minorCard("cups", 8, "Eight of Cups",
    "Walking away from what no longer nourishes. The courage to leave behind emotional comfort for deeper purpose marks true maturity.",
    "Fear of abandoning the familiar or directionless wandering. Leaving without knowing what you are walking toward.",
    "departure, seeking deeper meaning, letting go, courage",
    "A cloaked figure walks away from eight neatly stacked cups under a moonlit sky, heading toward distant mountains."),
  minorCard("cups", 9, "Nine of Cups",
    "Emotional satisfaction and contentment. Your wishes are manifesting — savor the fulfillment and gratitude of this abundant moment.",
    "Superficial satisfaction or smugness. Material comfort without emotional depth leaves a quiet emptiness.",
    "contentment, satisfaction, wishes fulfilled, gratitude",
    "A well-dressed figure sits before a curved display of nine golden cups, arms crossed with a satisfied smile."),
  minorCard("cups", 10, "Ten of Cups",
    "Emotional wholeness and lasting harmony. Love shared with family and community creates the rainbow bridge between earth and spirit.",
    "Broken family harmony or unmet emotional ideals. The picture-perfect scene cracks under unresolved tensions.",
    "harmony, family, emotional fulfillment, lasting joy",
    "A joyous couple raises their arms beneath a rainbow of ten cups, children playing beside a peaceful river and home."),
  minorCard("cups", 11, "Page of Cups",
    "A tender message from the heart or a creative surprise. Stay open to emotional discovery — wonder and imagination knock softly.",
    "Emotional immaturity or creative blocks. Sensitivity without grounding leaves feelings unanchored.",
    "creativity, intuition, emotional message, wonder",
    "A young figure stands by the sea, surprised as a fish pops out of the golden cup in their hand, offering an unexpected message."),
  minorCard("cups", 12, "Knight of Cups",
    "A romantic, idealistic quest driven by the heart. Follow your emotional truth with grace — the offer being made is sincere.",
    "Unrealistic romanticism or emotional manipulation. Charm without substance leads to disappointment.",
    "romance, idealism, charm, following the heart",
    "A knight in shining armor rides slowly on a white horse, extending a cup like an offering, a river flowing gently below."),
  minorCard("cups", 13, "Queen of Cups",
    "Deep emotional intelligence and compassionate presence. Hold space for others while honoring your own feelings — empathy is your gift.",
    "Emotional overwhelm or codependency. Absorbing others' pain without boundaries drains your own well.",
    "empathy, emotional depth, compassion, intuition",
    "A contemplative queen sits on a throne at the water's edge, gazing into an ornate closed cup, her feet touching the sea."),
  minorCard("cups", 14, "King of Cups",
    "Emotional mastery balanced with wisdom. Lead with heart and diplomacy — calm seas inside create calm seas around you.",
    "Emotional volatility hidden behind a composed exterior. Suppressed feelings eventually surface as storms.",
    "emotional balance, diplomacy, wisdom, composure",
    "A king sits on a throne amid turbulent seas, holding a cup steadily in one hand and a scepter in the other, calm amid the waves."),
];

const SWORDS: TarotCardSeed[] = [
  minorCard("swords", 1, "Ace of Swords",
    "A breakthrough of clarity and truth. A new idea cuts through confusion — wield this mental power with integrity and precision.",
    "Confusion or misuse of intellect. The blade is sharp but pointed inward, creating self-doubt instead of insight.",
    "clarity, truth, breakthrough, new idea",
    "A hand from the clouds grips a gleaming double-edged sword crowned with a laurel wreath, mountain peaks below."),
  minorCard("swords", 2, "Two of Swords",
    "A difficult decision held in stalemate. Blindfolded to external influence, you must turn inward to find the courage to choose.",
    "Information overload or forced choice. The blindfold comes off but the options feel equally painful.",
    "indecision, stalemate, difficult choice, avoidance",
    "A blindfolded figure sits at the water's edge, two crossed swords balanced on the shoulders, a crescent moon above."),
  minorCard("swords", 3, "Three of Swords",
    "Heartbreak and painful truth. Grief pierces the heart, but acknowledging the pain is the first step toward genuine healing.",
    "Recovery from sorrow and learning to release. The swords are being removed and the heart begins to mend.",
    "heartbreak, sorrow, painful truth, grief",
    "Three swords pierce a bright red heart as rain and storm clouds fill the sky behind."),
  minorCard("swords", 4, "Four of Swords",
    "Rest and mental recovery. Retreat from the noise and let your mind heal — contemplation and stillness restore what battle depleted.",
    "Restlessness or forced return to action before recovery is complete. Burnout deepens without adequate pause.",
    "rest, recovery, contemplation, retreat",
    "A knight lies in repose on a stone tomb, three swords on the wall and one beneath, hands in prayer inside a quiet chapel."),
  minorCard("swords", 5, "Five of Swords",
    "A hollow victory or unfair conflict. Winning at the cost of others' dignity leaves everyone diminished — choose your battles wisely.",
    "Reconciliation after conflict or acknowledging a no-win situation. Letting go of the need to be right.",
    "conflict, defeat, hollow victory, tension",
    "A smirking figure collects fallen swords while two defeated opponents walk away under a stormy sky."),
  minorCard("swords", 6, "Six of Swords",
    "Transition toward calmer waters. Leave troubled shores behind — the passage may be quiet and somber, but it leads to peace.",
    "Resistance to necessary transition or unresolved baggage. The boat moves but the weight of the past slows the crossing.",
    "transition, moving on, recovery, passage",
    "A ferryman guides a huddled figure and child across calm water, six swords planted in the bow of the small boat."),
  minorCard("swords", 7, "Seven of Swords",
    "Strategy that skirts the rules. Stealth, cunning, or avoidance may seem clever, but consider what you sacrifice in integrity.",
    "Getting caught or choosing honesty over deception. Returning what was taken restores trust and self-respect.",
    "strategy, deception, stealth, cunning",
    "A figure tiptoes away from a camp carrying five swords, two left behind, glancing back with a sly expression."),
  minorCard("swords", 8, "Eight of Swords",
    "Feeling trapped by thoughts and fears. The bindings are mental, not physical — you have more power to free yourself than you realize.",
    "Breaking free from self-imposed limitations. The blindfold loosens and options that were always there become visible.",
    "restriction, self-imposed limits, fear, helplessness",
    "A blindfolded, loosely bound figure stands surrounded by eight swords in muddy ground, water pooling at their feet."),
  minorCard("swords", 9, "Nine of Swords",
    "Anxiety, nightmares, and spiraling worry. The darkest hour is often in the mind — face the fears that haunt your sleepless nights.",
    "Beginning to process anxiety and finding support. The night terrors ease when shared or examined in daylight.",
    "anxiety, nightmares, worry, despair",
    "A figure sits upright in bed, face in hands, nine swords hanging horizontally on the dark wall behind."),
  minorCard("swords", 10, "Ten of Swords",
    "A painful but definitive ending. Rock bottom has been reached — there is nowhere to go but up. Dawn breaks on the horizon.",
    "Survival and the first signs of recovery. The worst is truly over; refuse to re-wound yourself with the same blades.",
    "ending, rock bottom, finality, new dawn",
    "A prone figure lies face-down with ten swords in their back, yet a golden dawn glows on the distant horizon."),
  minorCard("swords", 11, "Page of Swords",
    "Alert, curious, and ready to learn. A sharp mind seeks truth — gather information, ask bold questions, and stay mentally agile.",
    "Gossip, hasty conclusions, or all talk and no action. Mental energy scatters without discipline.",
    "curiosity, vigilance, mental agility, truth-seeking",
    "A young figure stands on windswept ground, holding a sword upright with both hands, scanning the sky with keen eyes."),
  minorCard("swords", 12, "Knight of Swords",
    "Charging forward with intellectual conviction. Direct, ambitious, and unstoppable — but speed without thought risks collateral damage.",
    "Reckless aggression or verbal cruelty. The blade of words cuts deeper than intended when empathy is absent.",
    "ambition, directness, speed, intellectual force",
    "A knight charges at full gallop through stormy clouds, sword raised high, cape and horse mane streaming in the wind."),
  minorCard("swords", 13, "Queen of Swords",
    "Clear perception paired with hard-won wisdom. Speak truth with precision and compassion — boundaries protect without cruelty.",
    "Cold detachment or bitterness from past pain. Sharpness without warmth isolates you from those who mean well.",
    "perception, clarity, independence, boundaries",
    "A crowned queen sits on a cloud-carved throne, one hand extended and the other raising a sword to the sky, butterflies nearby."),
  minorCard("swords", 14, "King of Swords",
    "Intellectual authority and ethical judgment. Lead with clear logic, fair standards, and principled decision-making.",
    "Abuse of intellectual power or emotional coldness. Authority without humanity becomes tyranny.",
    "authority, intellect, ethics, clear judgment",
    "A stern king sits on a high-backed throne, holding an upright sword, trees bending in the wind behind his composed presence."),
];

const PENTACLES: TarotCardSeed[] = [
  minorCard("pentacles", 1, "Ace of Pentacles",
    "A seed of material and physical potential. A tangible opportunity appears — nurture it with practical effort and grounded intention.",
    "Missed opportunity or poor financial planning. The seed is there but the soil has not been prepared.",
    "opportunity, prosperity, new venture, manifestation",
    "A hand from the clouds offers a golden pentacle above a lush garden with an archway leading to distant green mountains."),
  minorCard("pentacles", 2, "Two of Pentacles",
    "Juggling priorities with adaptability. Multiple demands compete for your attention — flexibility and humor keep the balance alive.",
    "Overwhelm from too many commitments. Dropping a ball is inevitable when you refuse to simplify.",
    "balance, adaptability, juggling priorities, flexibility",
    "A dancing figure juggles two pentacles linked by an infinity loop, two ships riding rolling waves in the background."),
  minorCard("pentacles", 3, "Three of Pentacles",
    "Collaboration and skilled craftsmanship. Working with others who share your standards elevates the final result beyond what any one person could achieve.",
    "Lack of teamwork or mediocre effort. Poor collaboration or cutting corners undermines quality.",
    "teamwork, craftsmanship, collaboration, skill",
    "A stonemason works on cathedral arches while two figures — a monk and an architect — review plans together."),
  minorCard("pentacles", 4, "Four of Pentacles",
    "Security through control and conservation. Holding tight to what you have provides stability, but too tight a grip blocks circulation.",
    "Releasing attachment to material control. Generosity flows when the fear of scarcity is examined honestly.",
    "security, control, conservation, possessiveness",
    "A figure sits with a pentacle on the crown, two under the arms, and one beneath the feet, clutching everything tightly."),
  minorCard("pentacles", 5, "Five of Pentacles",
    "Material hardship and feeling left out in the cold. Help exists nearby — look up and you will see the warmth shining through the window.",
    "Recovery from financial or health setback. Accepting support and finding resources that were overlooked.",
    "hardship, loss, isolation, perseverance",
    "Two ragged figures trudge through snow past a brightly lit stained-glass church window, five pentacles glowing above."),
  minorCard("pentacles", 6, "Six of Pentacles",
    "Generosity and fair exchange. Give and receive with an open hand — true abundance circulates through sharing, not hoarding.",
    "Strings-attached generosity or power imbalance. Charity that creates dependency rather than empowerment.",
    "generosity, charity, balance of giving, fairness",
    "A wealthy merchant holds balanced scales while distributing coins to two kneeling figures, six pentacles surrounding the scene."),
  minorCard("pentacles", 7, "Seven of Pentacles",
    "Patience while awaiting results. The seeds are planted and growing — trust the process even when the harvest is not yet visible.",
    "Impatience or wasted investment. Digging up seeds to check progress destroys the growth you are waiting for.",
    "patience, investment, long-term view, assessment",
    "A gardener leans on a hoe, gazing thoughtfully at a bush bearing seven pentacles, evaluating the season's growth."),
  minorCard("pentacles", 8, "Eight of Pentacles",
    "Dedicated practice and skill refinement. Mastery comes through repetition with intention — each piece you craft improves on the last.",
    "Perfectionism or monotonous labor without growth. Going through the motions without engagement dulls the craft.",
    "diligence, mastery, apprenticeship, dedication",
    "A focused artisan carves pentacles at a workbench, six completed pieces displayed on a post, one in hand and one in progress."),
  minorCard("pentacles", 9, "Nine of Pentacles",
    "Self-sufficiency and well-earned luxury. Enjoy the fruits of disciplined effort — independence and refinement are your reward.",
    "Over-reliance on material comforts or financial dependence on others. Luxury without autonomy feels hollow.",
    "abundance, self-sufficiency, luxury, discipline",
    "An elegant figure stands in a lush vineyard with a hooded falcon on one hand, nine golden pentacles ripening on the vines."),
  minorCard("pentacles", 10, "Ten of Pentacles",
    "Lasting legacy and multi-generational wealth. Family, tradition, and accumulated wisdom create a foundation that endures beyond one lifetime.",
    "Family financial disputes or loss of inheritance. Legacy crumbles when values are not passed down with the wealth.",
    "legacy, wealth, family, long-term success",
    "An elder sits beneath an archway with two dogs, watching a young family enter a grand estate, ten pentacles woven into the scene."),
  minorCard("pentacles", 11, "Page of Pentacles",
    "Eager study and the first steps toward a goal. A diligent beginner plants seeds with care — curiosity combined with effort grows results.",
    "Lack of focus on studies or procrastination. Ambition without action leaves plans forever in draft form.",
    "study, ambition, diligence, new skill",
    "A young figure stands in a green field, holding a single pentacle at eye level, studying it with earnest concentration."),
  minorCard("pentacles", 12, "Knight of Pentacles",
    "Steady, reliable progress through methodical effort. Slow and consistent wins the long game — dependability is your greatest asset.",
    "Stubbornness or being stuck in routine. Over-caution and rigidity prevent adaptation when change is needed.",
    "reliability, routine, patience, methodical effort",
    "A patient knight sits atop a heavy draft horse in a plowed field, holding a single pentacle, surveying the work ahead."),
  minorCard("pentacles", 13, "Queen of Pentacles",
    "Nurturing abundance and practical wisdom. Create a life of comfort and care through grounded generosity and resourceful warmth.",
    "Neglecting personal needs while caring for everyone else. Practical support turns to resentment without self-nourishment.",
    "nurturing, practical wisdom, abundance, comfort",
    "A serene queen sits in a garden bower, cradling a pentacle in her lap, surrounded by roses, a rabbit at her feet."),
  minorCard("pentacles", 14, "King of Pentacles",
    "Material mastery and prosperous stewardship. Build lasting wealth through patience, integrity, and wise management of resources.",
    "Greed, materialism, or financial recklessness. The throne crumbles when wealth becomes the only measure of worth.",
    "prosperity, security, stewardship, material mastery",
    "A richly robed king sits on a throne carved with bull heads, pentacle in lap, grapevines and a castle in the background."),
];

export const TAROT_CARD_SEEDS: TarotCardSeed[] = [
  ...MAJOR_ARCANA,
  ...WANDS,
  ...CUPS,
  ...SWORDS,
  ...PENTACLES,
];
