type RitualBlueprint = {
  id: string;
  slug: string;
  title: string;
  summary: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  moonPhase: string;
  durationMinutes: number;
  coverImage: string;
  focus: string;
  materials: string[];
};

type LibraryEntrySeed = {
  id: string;
  slug: string;
  title: string;
  entityType: "crystal" | "herb" | "candle" | "symbol" | "deity";
  summary: string;
  spiritualProperties: string;
  correspondences: string;
  cleansingMethod: string;
  careNote: string;
};

export const MATERIAL_SEEDS = [
  { id: "white-candle", slug: "white-candle", name: "White Candle", linkedEntryId: "white-candle" },
  { id: "green-candle", slug: "green-candle", name: "Green Candle", linkedEntryId: "green-candle" },
  { id: "black-candle", slug: "black-candle", name: "Black Candle", linkedEntryId: "black-candle" },
  { id: "pink-candle", slug: "pink-candle", name: "Pink Candle", linkedEntryId: "pink-candle" },
  { id: "blue-candle", slug: "blue-candle", name: "Blue Candle", linkedEntryId: "blue-candle" },
  { id: "rose-quartz", slug: "rose-quartz", name: "Rose Quartz", linkedEntryId: "rose-quartz" },
  { id: "amethyst", slug: "amethyst", name: "Amethyst", linkedEntryId: "amethyst" },
  { id: "clear-quartz", slug: "clear-quartz", name: "Clear Quartz", linkedEntryId: "clear-quartz" },
  { id: "obsidian", slug: "obsidian", name: "Obsidian", linkedEntryId: "obsidian" },
  { id: "selenite", slug: "selenite", name: "Selenite Wand", linkedEntryId: "selenite" },
  { id: "rosemary", slug: "rosemary", name: "Rosemary", linkedEntryId: "rosemary" },
  { id: "lavender", slug: "lavender", name: "Lavender", linkedEntryId: "lavender" },
  { id: "mugwort", slug: "mugwort", name: "Mugwort", linkedEntryId: "mugwort" },
  { id: "bay-leaf", slug: "bay-leaf", name: "Bay Leaf", linkedEntryId: "bay-leaf" },
  { id: "basil", slug: "basil", name: "Basil", linkedEntryId: "basil" },
  { id: "sea-salt", slug: "sea-salt", name: "Sea Salt", linkedEntryId: null },
  { id: "moon-water", slug: "moon-water", name: "Moon Water", linkedEntryId: null },
  { id: "cinnamon-stick", slug: "cinnamon-stick", name: "Cinnamon Stick", linkedEntryId: "cinnamon" },
  { id: "frankincense", slug: "frankincense", name: "Frankincense", linkedEntryId: "frankincense" },
  { id: "myrrh", slug: "myrrh", name: "Myrrh", linkedEntryId: "myrrh" },
  { id: "journal", slug: "journal", name: "Journal", linkedEntryId: null },
  { id: "small-mirror", slug: "small-mirror", name: "Small Mirror", linkedEntryId: null },
] as const;

const ritualBlueprints: RitualBlueprint[] = [
  {
    id: "full-moon-release",
    slug: "full-moon-release",
    title: "Full Moon Release",
    summary: "Release stagnant patterns and close cycles under full moon light.",
    category: "moon",
    difficulty: "beginner",
    moonPhase: "full",
    durationMinutes: 24,
    coverImage: "https://images.unsplash.com/photo-1527482797697-8795b05a13fe?q=80&w=1740&auto=format&fit=crop",
    focus: "release and emotional closure",
    materials: ["white-candle", "sea-salt", "moon-water"],
  },
  {
    id: "new-moon-intention",
    slug: "new-moon-intention",
    title: "New Moon Intention",
    summary: "Set a clear intention and plant a fresh energetic seed.",
    category: "moon",
    difficulty: "beginner",
    moonPhase: "new",
    durationMinutes: 18,
    coverImage: "https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=80&w=1887&auto=format&fit=crop",
    focus: "starting a new chapter",
    materials: ["white-candle", "journal", "bay-leaf"],
  },
  {
    id: "self-love-anointing",
    slug: "self-love-anointing",
    title: "Self Love Anointing",
    summary: "Soften self-talk and invite compassion into your daily rhythm.",
    category: "love",
    difficulty: "beginner",
    moonPhase: "waxing-crescent",
    durationMinutes: 16,
    coverImage: "https://images.unsplash.com/photo-1518893494013-481c1d8ed3fd?q=80&w=1200&auto=format&fit=crop",
    focus: "self-worth and tenderness",
    materials: ["pink-candle", "rose-quartz", "lavender"],
  },
  {
    id: "hearth-protection-circle",
    slug: "hearth-protection-circle",
    title: "Hearth Protection Circle",
    summary: "Shield your home and reinforce your energetic boundaries.",
    category: "protection",
    difficulty: "intermediate",
    moonPhase: "waning-gibbous",
    durationMinutes: 28,
    coverImage: "https://images.unsplash.com/photo-1565514020179-026b92b2d5f5?q=80&w=1200&auto=format&fit=crop",
    focus: "home protection and grounded safety",
    materials: ["black-candle", "rosemary", "sea-salt"],
  },
  {
    id: "dream-clarity-tea",
    slug: "dream-clarity-tea",
    title: "Dream Clarity Tea",
    summary: "Prepare your sleep space for symbolic dreams and insight.",
    category: "healing",
    difficulty: "beginner",
    moonPhase: "waning-crescent",
    durationMinutes: 14,
    coverImage: "https://images.unsplash.com/photo-1593487568720-92097fb460fb?q=80&w=1200&auto=format&fit=crop",
    focus: "clear dream messages",
    materials: ["mugwort", "amethyst", "blue-candle"],
  },
  {
    id: "money-bowl-prosperity",
    slug: "money-bowl-prosperity",
    title: "Money Bowl Prosperity",
    summary: "Call in aligned opportunities and practical abundance.",
    category: "abundance",
    difficulty: "intermediate",
    moonPhase: "waxing-gibbous",
    durationMinutes: 30,
    coverImage: "https://images.unsplash.com/photo-1610375461246-83df859d849d?q=80&w=1200&auto=format&fit=crop",
    focus: "abundance through disciplined action",
    materials: ["green-candle", "cinnamon-stick", "bay-leaf"],
  },
  {
    id: "cord-cutting-boundary",
    slug: "cord-cutting-boundary",
    title: "Cord Cutting Boundary",
    summary: "Detach from draining ties while honoring lessons learned.",
    category: "protection",
    difficulty: "advanced",
    moonPhase: "waning-moon",
    durationMinutes: 36,
    coverImage: "https://images.unsplash.com/photo-1556702571-3e11dd2b1a92?q=80&w=1200&auto=format&fit=crop",
    focus: "energetic boundary restoration",
    materials: ["black-candle", "small-mirror", "obsidian"],
  },
  {
    id: "confidence-solar-rise",
    slug: "confidence-solar-rise",
    title: "Confidence Solar Rise",
    summary: "Strengthen your voice before important conversations.",
    category: "healing",
    difficulty: "beginner",
    moonPhase: "waxing-crescent",
    durationMinutes: 12,
    coverImage: "https://images.unsplash.com/photo-1520256862855-398228c41684?q=80&w=1200&auto=format&fit=crop",
    focus: "confidence and healthy expression",
    materials: ["blue-candle", "clear-quartz", "basil"],
  },
  {
    id: "ancestor-gratitude",
    slug: "ancestor-gratitude",
    title: "Ancestor Gratitude",
    summary: "Honor your lineage and request wisdom with respect.",
    category: "ritual",
    difficulty: "intermediate",
    moonPhase: "full",
    durationMinutes: 22,
    coverImage: "https://images.unsplash.com/photo-1495584816685-4bdbf1b5057e?q=80&w=1200&auto=format&fit=crop",
    focus: "ancestral gratitude and guidance",
    materials: ["white-candle", "frankincense", "myrrh"],
  },
  {
    id: "creative-spark",
    slug: "creative-spark",
    title: "Creative Spark",
    summary: "Unlock flow for writing, design, and artistic projects.",
    category: "abundance",
    difficulty: "beginner",
    moonPhase: "waxing-gibbous",
    durationMinutes: 15,
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=1200&auto=format&fit=crop",
    focus: "creative momentum",
    materials: ["green-candle", "clear-quartz", "journal"],
  },
  {
    id: "gentle-heart-healing",
    slug: "gentle-heart-healing",
    title: "Gentle Heart Healing",
    summary: "Soothe emotional fatigue and rebuild trust in yourself.",
    category: "healing",
    difficulty: "beginner",
    moonPhase: "waning-crescent",
    durationMinutes: 20,
    coverImage: "https://images.unsplash.com/photo-1519834785169-98be25ec3f84?q=80&w=1200&auto=format&fit=crop",
    focus: "heart healing",
    materials: ["pink-candle", "rose-quartz", "moon-water"],
  },
  {
    id: "home-cleansing-smoke",
    slug: "home-cleansing-smoke",
    title: "Home Cleansing Smoke",
    summary: "Refresh heavy rooms and invite clear movement.",
    category: "protection",
    difficulty: "beginner",
    moonPhase: "waning-gibbous",
    durationMinutes: 18,
    coverImage: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?q=80&w=1200&auto=format&fit=crop",
    focus: "space purification",
    materials: ["rosemary", "frankincense", "selenite"],
  },
  {
    id: "luck-doorway-ritual",
    slug: "luck-doorway-ritual",
    title: "Luck Doorway Ritual",
    summary: "Open a symbolic doorway for fortunate timing.",
    category: "abundance",
    difficulty: "intermediate",
    moonPhase: "waxing-moon",
    durationMinutes: 26,
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop",
    focus: "synchronized opportunities",
    materials: ["green-candle", "basil", "bay-leaf"],
  },
  {
    id: "focus-and-study",
    slug: "focus-and-study",
    title: "Focus and Study",
    summary: "Sharpen concentration before deep work sessions.",
    category: "beginner",
    difficulty: "beginner",
    moonPhase: "first-quarter",
    durationMinutes: 10,
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=1200&auto=format&fit=crop",
    focus: "mental clarity and memory",
    materials: ["blue-candle", "amethyst", "rosemary"],
  },
  {
    id: "relationship-harmony",
    slug: "relationship-harmony",
    title: "Relationship Harmony",
    summary: "Re-center communication with kindness and patience.",
    category: "love",
    difficulty: "intermediate",
    moonPhase: "waxing-gibbous",
    durationMinutes: 24,
    coverImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1200&auto=format&fit=crop",
    focus: "mutual understanding",
    materials: ["pink-candle", "lavender", "rose-quartz"],
  },
  {
    id: "winter-grounding",
    slug: "winter-grounding",
    title: "Winter Grounding",
    summary: "Stabilize your energy during low-light seasons.",
    category: "healing",
    difficulty: "beginner",
    moonPhase: "new",
    durationMinutes: 14,
    coverImage: "https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?q=80&w=1200&auto=format&fit=crop",
    focus: "grounded calm",
    materials: ["black-candle", "obsidian", "sea-salt"],
  },
  {
    id: "manifestation-letter",
    slug: "manifestation-letter",
    title: "Manifestation Letter",
    summary: "Write future memories as if they already happened.",
    category: "abundance",
    difficulty: "beginner",
    moonPhase: "waxing-crescent",
    durationMinutes: 19,
    coverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=1200&auto=format&fit=crop",
    focus: "intentional manifestation",
    materials: ["green-candle", "journal", "cinnamon-stick"],
  },
  {
    id: "return-to-self",
    slug: "return-to-self",
    title: "Return to Self",
    summary: "Recover your center after over-giving to others.",
    category: "protection",
    difficulty: "intermediate",
    moonPhase: "waning-crescent",
    durationMinutes: 21,
    coverImage: "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?q=80&w=1200&auto=format&fit=crop",
    focus: "self-reclamation",
    materials: ["white-candle", "selenite", "small-mirror"],
  },
  {
    id: "moon-bath-blessing",
    slug: "moon-bath-blessing",
    title: "Moon Bath Blessing",
    summary: "Reset your nervous system with water and moonlight.",
    category: "moon",
    difficulty: "beginner",
    moonPhase: "full",
    durationMinutes: 25,
    coverImage: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?q=80&w=1200&auto=format&fit=crop",
    focus: "energetic reset",
    materials: ["moon-water", "lavender", "white-candle"],
  },
  {
    id: "career-path-divination",
    slug: "career-path-divination",
    title: "Career Path Divination",
    summary: "Use symbols and journaling to reveal the next right step.",
    category: "ritual",
    difficulty: "advanced",
    moonPhase: "first-quarter",
    durationMinutes: 32,
    coverImage: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=1200&auto=format&fit=crop",
    focus: "career direction",
    materials: ["blue-candle", "journal", "clear-quartz"],
  },
  {
    id: "gratitude-closing",
    slug: "gratitude-closing",
    title: "Gratitude Closing",
    summary: "Complete the day with grounded gratitude and peace.",
    category: "beginner",
    difficulty: "beginner",
    moonPhase: "any",
    durationMinutes: 8,
    coverImage: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?q=80&w=1200&auto=format&fit=crop",
    focus: "daily gratitude",
    materials: ["white-candle", "journal", "amethyst"],
  },
];

export const RITUAL_SEEDS = ritualBlueprints.map((ritual, index) => ({
  id: ritual.id,
  slug: ritual.slug,
  title: ritual.title,
  summary: ritual.summary,
  category: ritual.category,
  difficulty: ritual.difficulty,
  moonPhase: ritual.moonPhase,
  durationMinutes: ritual.durationMinutes,
  coverImage: ritual.coverImage,
  incantation: `With focused breath and steady heart, I now call in ${ritual.focus}. As I will it, so mote it be.`,
  safetyNote: "Practice with consent, grounded intentions, and stop if you feel overwhelmed.",
  createdAt: Date.now() + index,
}));

export const RITUAL_STEP_SEEDS = ritualBlueprints.flatMap((ritual) => [
  {
    id: `${ritual.id}-step-1`,
    ritualId: ritual.id,
    stepOrder: 1,
    title: "Set the Space",
    content: `Clean your space, silence distractions, and state that this ritual is for ${ritual.focus}.`,
  },
  {
    id: `${ritual.id}-step-2`,
    ritualId: ritual.id,
    stepOrder: 2,
    title: "Prepare the Tools",
    content: "Arrange your materials in a small circle and light your candle with steady breathing.",
  },
  {
    id: `${ritual.id}-step-3`,
    ritualId: ritual.id,
    stepOrder: 3,
    title: "Speak the Intention",
    content: `Repeat your intention three times and visualize ${ritual.focus} as already present in your life.`,
  },
  {
    id: `${ritual.id}-step-4`,
    ritualId: ritual.id,
    stepOrder: 4,
    title: "Close and Ground",
    content: "Thank the energies you invited, extinguish the candle safely, and drink water to ground.",
  },
]);

export const RITUAL_MATERIAL_SEEDS = ritualBlueprints.flatMap((ritual) =>
  ritual.materials.map((materialId, index) => ({
    ritualId: ritual.id,
    materialId,
    quantityLabel: index === 0 ? "1x" : null,
    sortOrder: index + 1,
  }))
);

export const LIBRARY_ENTRY_SEEDS: LibraryEntrySeed[] = [
  {
    id: "rose-quartz",
    slug: "rose-quartz",
    title: "Rose Quartz",
    entityType: "crystal",
    summary: "Soft, heart-opening crystal for emotional repair and self-kindness.",
    spiritualProperties: "Love, compassion, trust, emotional healing",
    correspondences: "Chakra: Heart | Element: Water | Planet: Venus",
    cleansingMethod: "Moonlight or smoke cleanse",
    careNote: "Avoid prolonged direct sun to preserve color.",
  },
  {
    id: "amethyst",
    slug: "amethyst",
    title: "Amethyst",
    entityType: "crystal",
    summary: "Calming stone used for intuition, dreamwork, and protection.",
    spiritualProperties: "Calm, intuition, spiritual insight",
    correspondences: "Chakra: Third Eye, Crown | Element: Air",
    cleansingMethod: "Sound bowl or moonlight",
    careNote: "Keep in soft pouch to prevent chipping.",
  },
  {
    id: "clear-quartz",
    slug: "clear-quartz",
    title: "Clear Quartz",
    entityType: "crystal",
    summary: "Amplifier crystal used to boost intention and clarity.",
    spiritualProperties: "Amplification, clarity, energetic focus",
    correspondences: "Chakra: Crown | Element: Storm",
    cleansingMethod: "Running water or smoke",
    careNote: "Program with one clear intention at a time.",
  },
  {
    id: "obsidian",
    slug: "obsidian",
    title: "Obsidian",
    entityType: "crystal",
    summary: "Grounding volcanic glass for shielding and boundary work.",
    spiritualProperties: "Protection, grounding, boundary setting",
    correspondences: "Chakra: Root | Element: Earth",
    cleansingMethod: "Smoke or brief running water",
    careNote: "Can feel intense; pair with gentle practices.",
  },
  {
    id: "selenite",
    slug: "selenite",
    title: "Selenite",
    entityType: "crystal",
    summary: "High-vibration crystal for energetic clearing and uplift.",
    spiritualProperties: "Purification, clarity, peace",
    correspondences: "Chakra: Crown | Element: Air",
    cleansingMethod: "No water; use moonlight or sound",
    careNote: "Keep dry; selenite can soften with moisture.",
  },
  {
    id: "citrine",
    slug: "citrine",
    title: "Citrine",
    entityType: "crystal",
    summary: "Solar crystal associated with confidence and abundance.",
    spiritualProperties: "Vitality, prosperity, confidence",
    correspondences: "Chakra: Solar Plexus | Element: Fire",
    cleansingMethod: "Smoke cleanse or visualization",
    careNote: "Place near workspace for motivation.",
  },
  {
    id: "labradorite",
    slug: "labradorite",
    title: "Labradorite",
    entityType: "crystal",
    summary: "Mystic shimmer stone for transition and intuitive trust.",
    spiritualProperties: "Transformation, intuition, resilience",
    correspondences: "Chakra: Third Eye | Element: Wind",
    cleansingMethod: "Smoke or moonlight",
    careNote: "Carry during times of change.",
  },
  {
    id: "black-tourmaline",
    slug: "black-tourmaline",
    title: "Black Tourmaline",
    entityType: "crystal",
    summary: "Classic protective stone for energetic filtering.",
    spiritualProperties: "Protection, grounding, psychic hygiene",
    correspondences: "Chakra: Root | Element: Earth",
    cleansingMethod: "Smoke or salt bed nearby",
    careNote: "Set near entryways for protective support.",
  },
  {
    id: "rosemary",
    slug: "rosemary",
    title: "Rosemary",
    entityType: "herb",
    summary: "Purifying herb linked to protection and memory.",
    spiritualProperties: "Protection, clarity, remembrance",
    correspondences: "Element: Fire | Planet: Sun",
    cleansingMethod: "Dry and keep in sealed jar",
    careNote: "Use small amounts; aroma can be strong.",
  },
  {
    id: "lavender",
    slug: "lavender",
    title: "Lavender",
    entityType: "herb",
    summary: "Soothing herb for calm, rest, and gentle love work.",
    spiritualProperties: "Peace, emotional ease, rest",
    correspondences: "Element: Air | Planet: Mercury",
    cleansingMethod: "Store away from humidity",
    careNote: "Excellent for pillow sachets and baths.",
  },
  {
    id: "mugwort",
    slug: "mugwort",
    title: "Mugwort",
    entityType: "herb",
    summary: "Dream and intuition herb used in divination rituals.",
    spiritualProperties: "Dreamwork, psychic vision, liminal awareness",
    correspondences: "Element: Water | Planet: Moon",
    cleansingMethod: "Keep dry and in darkness",
    careNote: "Avoid if pregnant; use responsibly.",
  },
  {
    id: "bay-leaf",
    slug: "bay-leaf",
    title: "Bay Leaf",
    entityType: "herb",
    summary: "Leaf of victory, wishes, and intention writing.",
    spiritualProperties: "Success, wishes, confidence",
    correspondences: "Element: Fire | Planet: Sun",
    cleansingMethod: "Sun dry and sealed storage",
    careNote: "Write one intention per leaf.",
  },
  {
    id: "basil",
    slug: "basil",
    title: "Basil",
    entityType: "herb",
    summary: "Bright herb for prosperity and household harmony.",
    spiritualProperties: "Abundance, luck, peace",
    correspondences: "Element: Fire | Planet: Mars",
    cleansingMethod: "Dry bundle and keep cool",
    careNote: "Works well in doorway spells.",
  },
  {
    id: "cinnamon",
    slug: "cinnamon",
    title: "Cinnamon",
    entityType: "herb",
    summary: "Warming bark used for speed, abundance, and attraction.",
    spiritualProperties: "Activation, magnetism, prosperity",
    correspondences: "Element: Fire | Planet: Sun",
    cleansingMethod: "Store dry in airtight jar",
    careNote: "Use lightly to avoid overpowering blends.",
  },
  {
    id: "frankincense",
    slug: "frankincense",
    title: "Frankincense",
    entityType: "herb",
    summary: "Sacred resin for purification and prayerful focus.",
    spiritualProperties: "Purification, devotion, elevation",
    correspondences: "Element: Air | Planet: Sun",
    cleansingMethod: "Keep away from heat",
    careNote: "Burn with proper ventilation.",
  },
  {
    id: "myrrh",
    slug: "myrrh",
    title: "Myrrh",
    entityType: "herb",
    summary: "Ancient resin used for grounding and ancestral rites.",
    spiritualProperties: "Grounding, reverence, banishing",
    correspondences: "Element: Earth | Planet: Saturn",
    cleansingMethod: "Store in dark glass",
    careNote: "Blend with frankincense for temple-like scent.",
  },
  {
    id: "white-candle",
    slug: "white-candle",
    title: "White Candle",
    entityType: "candle",
    summary: "Universal candle for clarity, peace, and blessing.",
    spiritualProperties: "Purity, healing, spiritual reset",
    correspondences: "Element: Spirit | Planet: Moon",
    cleansingMethod: "Wipe with saltwater cloth",
    careNote: "Can substitute for most candle colors.",
  },
  {
    id: "green-candle",
    slug: "green-candle",
    title: "Green Candle",
    entityType: "candle",
    summary: "Candle color used for prosperity and growth.",
    spiritualProperties: "Abundance, growth, fertility",
    correspondences: "Element: Earth | Planet: Venus",
    cleansingMethod: "Smoke cleanse before use",
    careNote: "Use in practical money and career rituals.",
  },
  {
    id: "black-candle",
    slug: "black-candle",
    title: "Black Candle",
    entityType: "candle",
    summary: "Protective candle for banishing and boundary work.",
    spiritualProperties: "Protection, release, grounding",
    correspondences: "Element: Earth | Planet: Saturn",
    cleansingMethod: "Salt circle before lighting",
    careNote: "Ideal for waning moon rituals.",
  },
  {
    id: "pink-candle",
    slug: "pink-candle",
    title: "Pink Candle",
    entityType: "candle",
    summary: "Gentle candle for friendship, self-love, and harmony.",
    spiritualProperties: "Love, sweetness, emotional healing",
    correspondences: "Element: Water | Planet: Venus",
    cleansingMethod: "Anoint lightly with floral oil",
    careNote: "Use for non-obsessive love intentions.",
  },
  {
    id: "blue-candle",
    slug: "blue-candle",
    title: "Blue Candle",
    entityType: "candle",
    summary: "Calm candle for truth, communication, and serenity.",
    spiritualProperties: "Wisdom, truthful speech, peace",
    correspondences: "Element: Air | Planet: Jupiter",
    cleansingMethod: "Breath blessing and smoke",
    careNote: "Great before difficult conversations.",
  },
  {
    id: "gold-candle",
    slug: "gold-candle",
    title: "Gold Candle",
    entityType: "candle",
    summary: "Solar candle for confidence, success, and honor.",
    spiritualProperties: "Victory, charisma, power",
    correspondences: "Element: Fire | Planet: Sun",
    cleansingMethod: "Sunlight charging",
    careNote: "Use for leadership and recognition spells.",
  },
  {
    id: "triquetra",
    slug: "triquetra",
    title: "Triquetra",
    entityType: "symbol",
    summary: "Ancient knot symbol of interwoven cycles and unity.",
    spiritualProperties: "Balance, continuity, sacred triads",
    correspondences: "Element: Spirit",
    cleansingMethod: "Trace with smoke or moon water",
    careNote: "Use on journals for protection.",
  },
  {
    id: "pentacle",
    slug: "pentacle",
    title: "Pentacle",
    entityType: "symbol",
    summary: "Protective symbol representing elemental harmony.",
    spiritualProperties: "Protection, grounding, elemental balance",
    correspondences: "Elements: Earth, Air, Fire, Water, Spirit",
    cleansingMethod: "Salt and breath activation",
    careNote: "Keep altar pentacle clean and respected.",
  },
  {
    id: "ankh",
    slug: "ankh",
    title: "Ankh",
    entityType: "symbol",
    summary: "Egyptian symbol of life force and vitality.",
    spiritualProperties: "Vitality, life current, spiritual protection",
    correspondences: "Element: Air",
    cleansingMethod: "Sound cleansing",
    careNote: "Use during healing meditations.",
  },
  {
    id: "spiral",
    slug: "spiral",
    title: "Spiral",
    entityType: "symbol",
    summary: "Universal symbol of evolution and returning cycles.",
    spiritualProperties: "Growth, transformation, inner journey",
    correspondences: "Element: Water",
    cleansingMethod: "Moonlight and mindful tracing",
    careNote: "Draw clockwise to build energy.",
  },
  {
    id: "brigid",
    slug: "brigid",
    title: "Brigid",
    entityType: "deity",
    summary: "Goddess associated with hearth, creativity, and healing.",
    spiritualProperties: "Inspiration, protection, sacred fire",
    correspondences: "Season: Imbolc | Element: Fire",
    cleansingMethod: "Offer clean water and candlelight",
    careNote: "Approach with gratitude and service-minded intent.",
  },
  {
    id: "hekate",
    slug: "hekate",
    title: "Hekate",
    entityType: "deity",
    summary: "Liminal guide linked to crossroads and magic.",
    spiritualProperties: "Guidance, protection, threshold wisdom",
    correspondences: "Moon phase: Dark moon | Element: Spirit",
    cleansingMethod: "Crossroads prayer and smoke",
    careNote: "Use respectful boundary-based petitions.",
  },
  {
    id: "freya",
    slug: "freya",
    title: "Freya",
    entityType: "deity",
    summary: "Norse goddess tied to beauty, love, and sovereignty.",
    spiritualProperties: "Self-worth, courage, sensuality",
    correspondences: "Day: Friday | Element: Fire",
    cleansingMethod: "Rosewater and song",
    careNote: "Ask for empowered love, not attachment.",
  },
  {
    id: "thoth",
    slug: "thoth",
    title: "Thoth",
    entityType: "deity",
    summary: "Keeper of writing and wisdom in Egyptian tradition.",
    spiritualProperties: "Knowledge, communication, sacred study",
    correspondences: "Planet: Mercury | Element: Air",
    cleansingMethod: "Ink blessing and incense",
    careNote: "Excellent for study and writing rituals.",
  },
];

export const ENTITY_LINK_SEEDS = RITUAL_SEEDS.flatMap((ritual) => {
  const ritualBlueprint = ritualBlueprints.find((item) => item.id === ritual.id);

  if (!ritualBlueprint) {
    return [];
  }

  return ritualBlueprint.materials
    .map((materialId) => MATERIAL_SEEDS.find((material) => material.id === materialId)?.linkedEntryId)
    .filter((linkedEntryId) => linkedEntryId !== null && linkedEntryId !== undefined)
    .map((linkedEntryId) => ({
      id: `link-${ritual.id}-${linkedEntryId}`,
      sourceEntityType: "ritual",
      sourceEntityId: ritual.id,
      targetEntityType: "library_entry",
      targetEntityId: linkedEntryId,
      relationType: "uses",
    }));
});

export const DAILY_CARD_SEEDS = [
  {
    id: "daily-card-default",
    cardName: "The Star",
    arcana: "major",
    uprightMeaning: "Hope, renewal, and trust in your next chapter.",
    drawDate: "default",
  },
];

export const MOON_EVENT_SEEDS = [
  {
    id: "moon-event-1",
    eventDate: "2026-03-14",
    phase: "Full Moon",
    zodiacSign: "Virgo",
    summary: "Grounding full moon ideal for decluttering rituals.",
  },
  {
    id: "moon-event-2",
    eventDate: "2026-03-29",
    phase: "New Moon",
    zodiacSign: "Aries",
    summary: "Fresh cycle for confidence and initiative intentions.",
  },
  {
    id: "moon-event-3",
    eventDate: "2026-04-13",
    phase: "Full Moon",
    zodiacSign: "Libra",
    summary: "Balance-focused lunation supporting relationship clarity.",
  },
];

export const DEFAULT_USER_SEED = {
  id: "local-user",
  displayName: "Mystic Seeker",
  createdAt: Date.now(),
};

export const DEFAULT_SETTINGS_SEED = {
  id: "local-user-settings",
  userId: "local-user",
  themeMode: "system",
  notificationsEnabled: true,
  premiumActive: false,
};
